import { bank25 } from "./qcm-bank";
import type { SeedQuestion } from "../anatomie-quiz-helpers";

export const THEME_2_QUIZZES: SeedQuestion[][] = [
  bank25([
    [
      "Combien de chefs compose le quadriceps ?",
      "Quatre",
      ["Deux", "Trois", "Cinq"],
      "Vaste latéral, médial, intermédiaire et droit fémoral.",
    ],
    [
      "Les quatre chefs du quadriceps convergent d'abord vers…",
      "La rotule, puis le tibia",
      ["Le calcanéum via le tendon d'Achille", "Le grand trochanter", "L'ischion"],
      "Tous se réunissent vers la rotule avant de rejoindre le tibia.",
    ],
    [
      "L'action commune des quatre chefs du quadriceps est…",
      "Étendre le genou",
      ["Fléchir le genou", "Adduire la hanche", "Pointer le pied"],
      "Leg extension, squat, presse : le genou se tend grâce au quadriceps.",
    ],
    [
      "Quel chef du quadriceps croise aussi la hanche ?",
      "Le droit fémoral",
      ["Le vaste latéral", "Le vaste médial", "Le vaste intermédiaire"],
      "Seul le droit fémoral est bi-articulaire : genou et hanche.",
    ],
    [
      "Le droit fémoral aide aussi à…",
      "Fléchir la hanche",
      ["Étendre uniquement la hanche", "Supiner le pied", "Ouvrir l'omoplate"],
      "Il fléchit la hanche en plus d'étendre le genou.",
    ],
    [
      "Les vastes (latéral, médial, intermédiaire) n'agissent principalement que sur…",
      "Le genou",
      ["La hanche et le genou", "La cheville", "Le bassin seul"],
      "Contrairement au droit fémoral, ils ne croisent pas la hanche.",
    ],
    [
      "Quel muscle est le spécialiste de la flexion de hanche ?",
      "L'ilio-psoas",
      ["Le grand fessier", "Le soléaire", "Le biceps fémoral"],
      "Il relie lombaires et bassin au fémur et remonte le genou.",
    ],
    [
      "L'ilio-psoas relie surtout…",
      "Les lombaires et le bassin au fémur",
      ["La rotule au tibia", "Le sacrum au calcanéum", "L'omoplate à l'humérus"],
      "Ancrage profond : rachis lombaire / bassin → fémur.",
    ],
    [
      "Dans les relevés de jambes, le muscle qui remonte surtout le genou vers la poitrine est…",
      "L'ilio-psoas",
      ["Le tenseur du fascia lata", "Le gastrocnémien", "Le tibial antérieur"],
      "Flexion de hanche profonde = ilio-psoas.",
    ],
    [
      "Le TFL (tenseur du fascia lata) aide surtout à…",
      "Stabiliser le bassin",
      ["Étendre le genou comme le quadriceps", "Pointer le pied", "Tourner uniquement le cou"],
      "Il travaille sur le côté pour tenir le bassin.",
    ],
    [
      "Le sartorius traverse la cuisse…",
      "En écharpe jusqu'au tibia",
      ["Tout droit vers le calcanéum", "Vers le grand trochanter seulement", "Vers le sternum"],
      "Long muscle en bandoulière, face antérieure de cuisse.",
    ],
    [
      "Leg extension, squat et presse à cuisses ont en commun de…",
      "Tendre le genou contre une résistance",
      ["Fléchir uniquement la cheville", "Adduire la hanche sans genou", "Étendre le coude"],
      "Dès que le genou s'étend chargé, le quadriceps commande.",
    ],
    [
      "Le vaste médial se situe plutôt…",
      "Côté interne de la cuisse, près du genou",
      ["Côté externe comme le biceps fémoral", "Sous le soléaire", "Sur le sacrum"],
      "Les vastes encadrent le genou : médial en dedans, latéral en dehors.",
    ],
    [
      "Le vaste latéral se situe plutôt…",
      "Côté externe de la cuisse",
      ["Côté interne comme le gracile", "Derrière l'ischion seulement", "Devant le tibia"],
      "C'est le chef le plus externe du quadriceps.",
    ],
    [
      "Le vaste intermédiaire est surtout…",
      "Profond, sous le droit fémoral",
      ["Le plus superficiel de la fesse", "Un muscle de la cheville", "Un rotateur du sacrum"],
      "Il est caché sous le droit fémoral, entre les deux vastes.",
    ],
    [
      "Si tu veux distinguer droit fémoral et vastes, retiens que…",
      "Seul le droit fémoral fléchit aussi la hanche",
      ["Seuls les vastes fléchissent la hanche", "Le droit fémoral n'étend jamais le genou", "Les vastes s'insèrent sur le calcanéum"],
      "Même extension de genou ; la hanche trahit le droit fémoral.",
    ],
    [
      "Devant de cuisse, le muscle extenseur de genou dominant est…",
      "Le quadriceps",
      ["Les ischio-jambiers", "Le grand fessier", "Le soléaire"],
      "Les ischios fléchissent le genou ; le quadriceps l'étend.",
    ],
    [
      "Un muscle bi-articulaire du devant de cuisse, c'est surtout…",
      "Le droit fémoral",
      ["Le vaste intermédiaire", "Le soléaire", "Le petit fessier"],
      "Hanche + genou : droit fémoral (et sartorius, plus latéral).",
    ],
    [
      "Le TFL n'est pas…",
      "Le chef principal d'extension du genou",
      ["Un muscle du côté de la hanche", "Un aide à la stabilité du bassin", "Un muscle de la face latérale"],
      "L'extension du genou reste l'affaire du quadriceps.",
    ],
    [
      "Le sartorius se termine vers…",
      "Le tibia",
      ["Le calcanéum", "La rotule uniquement", "Le sacrum"],
      "Il descend en écharpe jusqu'au tibia.",
    ],
    [
      "L'ilio-psoas n'est pas…",
      "Un extenseur de genou comme le quadriceps",
      ["Un fléchisseur de hanche", "Un muscle profond", "Relié aux lombaires"],
      "Il fléchit la hanche ; ce n'est pas un chef du quadriceps.",
    ],
    [
      "En squat, quand le genou se tend pour remonter, le moteur principal côté cuisse avant est…",
      "Le quadriceps",
      ["Le tibial antérieur", "Le piriforme", "Le long fibulaire"],
      "Extension de genou chargée = quadriceps.",
    ],
    [
      "Quel couple décrit le mieux le devant de cuisse ?",
      "Quadriceps (genou) + fléchisseurs de hanche",
      ["Ischios + grand fessier uniquement", "Gastrocnémien + soléaire", "Piriforme + obturateurs"],
      "Extenseur de genou dominant, épaulé par les fléchisseurs de hanche.",
    ],
    [
      "Le droit fémoral se distingue des vastes parce qu'il…",
      "Croise deux articulations",
      ["S'arrête sur le calcanéum", "Naît sur l'ischion", "Ne touche jamais le genou"],
      "Hanche et genou : un muscle, deux articulations.",
    ],
    [
      "Lequel n'est pas un chef du quadriceps ?",
      "Le sartorius",
      ["Le vaste latéral", "Le vaste médial", "Le droit fémoral"],
      "Le sartorius est à part, en écharpe ; les quatre chefs sont VL, VM, VI, DF.",
    ],
  ]),

  bank25([
    [
      "Combien d'ischio-jambiers compte-t-on classiquement ?",
      "Trois",
      ["Deux", "Quatre comme le quadriceps", "Un seul muscle massif"],
      "Biceps fémoral, semi-tendineux et semi-membraneux.",
    ],
    [
      "Côté externe de l'arrière de cuisse, on trouve surtout…",
      "Le biceps fémoral",
      ["Le semi-tendineux", "Le semi-membraneux", "Le gracile"],
      "Le biceps fémoral est l'ischio latéral.",
    ],
    [
      "Côté interne de l'arrière de cuisse, on trouve…",
      "Le semi-tendineux et le semi-membraneux",
      ["Le biceps fémoral seul", "Le vaste latéral", "Le long fibulaire"],
      "Les deux « semi » occupent le versant médial.",
    ],
    [
      "Les ischios naissent presque tous sur…",
      "L'ischion",
      ["La rotule", "Le calcanéum", "Les lombaires"],
      "L'ischion : l'os sur lequel tu t'assois.",
    ],
    [
      "Les deux actions principales des ischios sont…",
      "Fléchir le genou et étendre la hanche",
      ["Étendre le genou et fléchir la hanche", "Adduire uniquement la cheville", "Dorsiflexer le pied"],
      "Leg curl d'un côté, RDL de l'autre.",
    ],
    [
      "Le leg curl cible surtout…",
      "La flexion du genou par les ischios",
      ["L'extension du genou par le quadriceps", "Les mollets assis", "Le tibial antérieur"],
      "Genou qui plie contre une résistance = ischios.",
    ],
    [
      "Le soulevé de terre roumain (RDL) nourrit surtout…",
      "L'extension de hanche des ischios",
      ["La dorsiflexion", "L'abduction du moyen fessier seule", "Les relevés de jambes de l'ilio-psoas"],
      "Ramener la cuisse en arrière : deuxième métier des ischios.",
    ],
    [
      "En RDL, la sensation d'étirement intense derrière la cuisse vient du fait que les ischios…",
      "S'allongent sur deux articulations à la fois",
      ["Ne croisent qu'une articulation", "Travaillent comme le soléaire", "Se raccourcissent au genou et à la hanche"],
      "Hanche qui plie, genou qui reste tendu : double allongement.",
    ],
    [
      "Pour étirer fort les ischios en RDL, le genou doit plutôt…",
      "Rester tendu (ou presque)",
      ["Être complètement fléchi comme au leg curl", "Pointer en rotation interne forcée", "Être verrouillé en dorsiflexion"],
      "Genou tendu + hanche qui fléchit = ischios allongés aux deux bouts.",
    ],
    [
      "Sous les ischios, côté interne, le muscle massif à retenir est…",
      "Le grand adducteur",
      ["Le droit fémoral", "Le piriforme", "Le tibial antérieur"],
      "Il rapproche la cuisse de l'axe et charge fort en squat large.",
    ],
    [
      "Le grand adducteur sert surtout à…",
      "Ramener la cuisse en dedans",
      ["Étendre le coude", "Relever le pied", "Tourner la tête"],
      "Adduction = rapprocher la cuisse de la ligne médiane.",
    ],
    [
      "Les squats larges sollicitent particulièrement…",
      "Le grand adducteur",
      ["Le biceps brachial", "Le deltoïde antérieur", "Le tibial antérieur"],
      "Stance large = face interne de cuisse davantage au travail.",
    ],
    [
      "Ischios et quadriceps s'opposent surtout sur…",
      "La flexion versus l'extension du genou",
      ["La dorsiflexion versus la flexion plantaire", "L'abduction versus l'adduction d'épaule", "La rotation du cou"],
      "Ischios plient le genou ; quadriceps le tend.",
    ],
    [
      "Le biceps fémoral n'est pas…",
      "Un chef du quadriceps",
      ["Un ischio côté externe", "Un fléchisseur de genou", "Un extenseur de hanche possible"],
      "Même mot « biceps », autre région : c'est un ischio, pas un vaste.",
    ],
    [
      "Un programme complet pour les ischios nourrit…",
      "Les deux fonctions : genou et hanche",
      ["Uniquement le leg curl", "Uniquement les relevés de mollets", "Uniquement l'abduction de hanche"],
      "Leg curl + RDL (ou équivalent) plutôt qu'un seul pattern.",
    ],
    [
      "Étendre la hanche, pour les ischios, signifie…",
      "Ramener la cuisse en arrière",
      ["Monter le genou vers la poitrine", "Écarter la cuisse sur le côté", "Pointer le pied"],
      "C'est le geste du RDL et du verrouillage de hanche.",
    ],
    [
      "Le semi-tendineux se situe plutôt…",
      "Côté interne, avec le semi-membraneux",
      ["Côté externe, avec le vaste latéral", "Sous le tendon d'Achille", "Sur le sacrum"],
      "Les deux « semi » = versant médial de l'arrière de cuisse.",
    ],
    [
      "Lequel n'est pas un ischio-jambier ?",
      "Le droit fémoral",
      ["Le biceps fémoral", "Le semi-tendineux", "Le semi-membraneux"],
      "Le droit fémoral est un chef du quadriceps, devant.",
    ],
    [
      "Naissance des ischios et insertion basse se jouent surtout…",
      "De l'ischion vers l'arrière du genou",
      ["Du pubis vers la rotule", "Du sacrum vers le calcanéum", "Des lombaires vers le petit trochanter"],
      "Ischion → derrière le genou : d'où flexion de genou et extension de hanche.",
    ],
    [
      "Le grand adducteur n'est pas classé parmi…",
      "Les trois ischio-jambiers",
      ["Les muscles de la face interne", "Les adducteurs", "Les muscles utiles en squat large"],
      "Il côtoie les ischios, mais son métier phare reste l'adduction.",
    ],
    [
      "Un leg curl ne remplace pas un RDL parce que…",
      "L'un fléchit surtout le genou, l'autre étend surtout la hanche",
      ["Les deux ciblent uniquement le soléaire", "Le RDL travaille le tibial antérieur", "Le leg curl étend le genou"],
      "Mêmes muscles, deux fonctions à nourrir.",
    ],
    [
      "Si le genou reste tendu pendant que la hanche fléchit, tu allonges surtout…",
      "Les ischio-jambiers",
      ["Le quadriceps entier", "Le soléaire seul", "Le moyen fessier"],
      "C'est le schéma du RDL : double articulation des ischios.",
    ],
    [
      "Le biceps fémoral se distingue des deux « semi » par…",
      "Sa position externe",
      ["Son insertion sur le calcanéum", "Le fait qu'il n'existe pas", "Son rôle de releveur du pied"],
      "Externe = biceps fémoral ; interne = semi-tendineux et semi-membraneux.",
    ],
    [
      "« Presque tous partent de l'ischion » rappelle que les ischios…",
      "Partagent une origine pelvienne commune",
      ["Naissent tous sur la rotule", "Partent du tibia distal", "S'accrochent au sternum"],
      "L'ischion est l'ancrage haut de la plupart des ischios.",
    ],
    [
      "Arrière de cuisse, en une phrase : les ischios…",
      "Plient le genou et aident à étendre la hanche",
      ["Étendent le genou comme le quadriceps", "Relèvent surtout le pied", "Stabilisent uniquement la cheville"],
      "Deux métiers, un même groupe musculaire.",
    ],
  ]),

  bank25([
    [
      "La fonction phare du grand fessier est…",
      "L'extension de hanche",
      ["La dorsiflexion", "L'extension du genou seule", "La flexion de hanche de l'ilio-psoas"],
      "Ramener la cuisse en arrière, redresser le bassin.",
    ],
    [
      "Squat (sortie), soulevé de terre et hip thrust ont en commun…",
      "L'extension de hanche contre résistance",
      ["La flexion plantaire isolée", "L'abduction d'épaule", "La dorsiflexion"],
      "Chaque fois que les hanches avancent chargées, le grand fessier pousse.",
    ],
    [
      "Le hip thrust cible surtout…",
      "Le grand fessier",
      ["Le moyen fessier uniquement", "Le tibial antérieur", "Le droit fémoral"],
      "Extension de hanche horizontale = grand fessier.",
    ],
    [
      "Le moyen fessier se situe plutôt…",
      "Plus haut, sur le côté du bassin",
      ["Tout en profondeur sous le soléaire", "Devant, avec le quadriceps", "Derrière le genou"],
      "C'est le fessier latéral, au-dessus du grand sur le côté.",
    ],
    [
      "L'action d'écarter la cuisse s'appelle…",
      "L'abduction (moyen fessier)",
      ["L'adduction (grand adducteur)", "La flexion plantaire", "L'extension de genou"],
      "Moyen fessier = abduction ; ne pas confondre avec l'adduction interne.",
    ],
    [
      "Le rôle clé du moyen fessier en fente ou montée de marche est…",
      "Stabiliser le bassin en unipodal",
      ["Étendre le genou comme le quadriceps", "Pointer le pied", "Remplacer le tendon d'Achille"],
      "Dès qu'une jambe porte, il tient le bassin.",
    ],
    [
      "Si le moyen fessier est faible, on voit souvent…",
      "Le genou plonger vers l'intérieur",
      ["Le pied se relever tout seul", "Une hyperextension isolée du coude", "Une rotation du rachis cervical"],
      "Perte de stabilité latérale → genou qui rentre.",
    ],
    [
      "Le petit fessier se trouve…",
      "Sous le moyen fessier",
      ["Au-dessus du grand fessier en surface", "Devant la rotule", "Dans le mollet"],
      "Il est profond, caché sous le moyen.",
    ],
    [
      "Moyen et petit fessiers s'insèrent tous deux sur…",
      "Le grand trochanter",
      ["La rotule", "Le calcanéum", "Le pubis uniquement"],
      "La bosse externe du fémur : même destination.",
    ],
    [
      "Puissance derrière, stabilité sur le côté : cela oppose surtout…",
      "Grand fessier et moyen fessier",
      ["Gastrocnémien et soléaire", "Vaste médial et vaste latéral", "Piriforme et tibial antérieur"],
      "Grand = extension ; moyen = abduction / bassin unipodal.",
    ],
    [
      "Lequel n'est pas un fessier ?",
      "Le piriforme",
      ["Le grand fessier", "Le moyen fessier", "Le petit fessier"],
      "Le piriforme est un rotateur profond, sous les fessiers.",
    ],
    [
      "Le grand fessier n'est pas surtout…",
      "Le stabilisateur unipodal du bassin",
      ["Un puissant extenseur de hanche", "Sollicité en hip thrust", "Actif en sortie de squat"],
      "La stabilité unipodale latérale, c'est surtout le moyen fessier.",
    ],
    [
      "Le moyen fessier n'est pas surtout…",
      "Le moteur principal du hip thrust",
      ["Un abducteur de hanche", "Un stabilisateur du bassin", "Situé sur le côté"],
      "Le hip thrust charge l'extension : grand fessier.",
    ],
    [
      "Le petit fessier assiste surtout…",
      "Le moyen fessier comme gardien de la hanche",
      ["Le soléaire en mollets assis", "Le droit fémoral en leg extension", "Le biceps fémoral en curl"],
      "Même famille : abduction et contrôle de hanche.",
    ],
    [
      "Le grand trochanter est…",
      "La bosse externe du fémur",
      ["La rotule", "L'os du talon", "Une vertèbre lombaire"],
      "Point d'arrivée du moyen et du petit fessier.",
    ],
    [
      "En appui sur une jambe, le bassin qui bascule du côté opposé trahit souvent…",
      "Un moyen fessier qui ne tient pas",
      ["Un quadriceps trop fort", "Un soléaire trop court seulement", "Un tibial antérieur hypertrophié"],
      "Le moyen fessier est le gardien latéral du bassin.",
    ],
    [
      "Verrouiller un soulevé de terre en haut, hanches en avant, c'est surtout…",
      "L'extension de hanche du grand fessier",
      ["L'abduction du moyen fessier isolée", "La flexion de hanche de l'ilio-psoas", "La dorsiflexion"],
      "Les hanches avancent contre la barre : grand fessier.",
    ],
    [
      "Les fessiers sont autant des muscles de performance que d'esthétique parce qu'ils…",
      "Produisent de la force et de la stabilité de hanche",
      ["Ne servent qu'à s'asseoir", "Remplacent les mollets", "Étendent uniquement les doigts"],
      "Extension + contrôle latéral : squat, fentes, courses.",
    ],
    [
      "Le petit fessier n'est pas…",
      "Superficiel au moyen fessier",
      ["Plus profond que le moyen", "Inséré sur le grand trochanter", "Un aide à la hanche"],
      "Le petit est sous le moyen, pas au-dessus.",
    ],
    [
      "Abduction de hanche, ce n'est pas…",
      "Rapprocher la cuisse de l'axe (adduction)",
      ["Écarter la cuisse", "Le métier du moyen fessier", "Utile à la stabilité unipodale"],
      "Écarter ≠ rapprocher : moyen fessier vs adducteurs.",
    ],
    [
      "En fente, si le genou avant rentre, tu penses d'abord au…",
      "Moyen fessier",
      ["Grand fessier uniquement comme volume", "Gastrocnémien", "Droit fémoral isolé"],
      "Contrôle frontal du genou : stabilité latérale du moyen fessier.",
    ],
    [
      "Le grand fessier se distingue du moyen par…",
      "Sa puissance d'extension plutôt que l'abduction",
      ["Son insertion sur la rotule", "Le fait qu'il relève le pied", "Son origine sur le tibia"],
      "Même région, métiers différents.",
    ],
    [
      "Moyen et petit fessiers partagent…",
      "Une insertion sur le grand trochanter",
      ["Le tendon d'Achille", "Une insertion sur la rotule", "Une origine sur le calcanéum"],
      "Tous deux rejoignent la bosse externe du fémur.",
    ],
    [
      "Lequel décrit le mieux le trio fessier ?",
      "Grand = poussée ; moyen et petit = côté et stabilité",
      ["Tous les trois étendent uniquement le genou", "Tous les trois sont des mollets", "Tous les trois naissent sur l'ischion comme les ischios seuls"],
      "Puissance derrière, gardiens sur le flanc.",
    ],
    [
      "Le grand fessier n'est pas un simple coussin : sa vraie force, c'est…",
      "Pousser les hanches en extension",
      ["Fléchir le genou comme un ischio isolé", "Dorsiflexer", "Serrer uniquement les omoplates"],
      "Sortie de squat, DL, hip thrust : hanches qui avancent.",
    ],
  ]),

  bank25([
    [
      "Pourquoi faire des mollets assis ET debout ?",
      "Parce que le mollet, ce sont deux muscles",
      ["Parce que le quadriceps a quatre chefs", "Parce que le tendon d'Achille n'existe qu'assis", "Parce que le tibial antérieur travaille assis"],
      "Gastrocnémien debout, soléaire assis : deux cibles.",
    ],
    [
      "Le gastrocnémien part du…",
      "Fémur, donc il croise le genou",
      ["Tibia et fibula seulement, comme le soléaire", "Calcanéum uniquement", "Sacrum"],
      "Origine fémorale : le genou compte pour lui.",
    ],
    [
      "Debout, jambes tendues, le mollet qui travaille à plein est surtout…",
      "Le gastrocnémien",
      ["Le soléaire (genou fléchi)", "Le tibial antérieur", "Le droit fémoral"],
      "Genou tendu = gastroc disponible.",
    ],
    [
      "Le soléaire part du…",
      "Tibia et de la fibula",
      ["Fémur, comme le gastrocnémien", "Ischion", "Rotule"],
      "Le genou ne le concerne pas : origine sous le genou.",
    ],
    [
      "Assis, genou fléchi, les mollets ciblent surtout…",
      "Le soléaire",
      ["Le gastrocnémien", "Le quadriceps", "Le grand fessier"],
      "Gastroc raccourci / détendu ; le soléaire fournit l'effort.",
    ],
    [
      "Gastrocnémien et soléaire partagent…",
      "Le tendon d'Achille",
      ["La rotule", "La patte d'oie", "Le grand trochanter"],
      "Deux muscles, un même tendon vers le talon.",
    ],
    [
      "Le tibial antérieur sert surtout à…",
      "Relever le pied (dorsiflexion)",
      ["La flexion plantaire des mollets", "L'extension de hanche", "L'adduction de cuisse"],
      "C'est le grand releveur, devant la jambe.",
    ],
    [
      "Quand tu marches, le tibial antérieur empêche surtout…",
      "La pointe du pied de traîner",
      ["Le genou de s'étendre", "La hanche de fléchir", "Les ischios de naître sur l'ischion"],
      "Dorsiflexion = pied qui décolle du sol.",
    ],
    [
      "Le long fibulaire, sur le bord externe, sert surtout à…",
      "Stabiliser la cheville et limiter les entorses",
      ["Étendre le genou", "Fléchir la hanche", "Remplacer le grand fessier"],
      "Petit muscle, gros enjeu de stabilité latérale.",
    ],
    [
      "Mollets assis : le gastrocnémien est moins efficace parce qu'il est…",
      "Raccourci / détendu, genou fléchi",
      ["Plus long qu'en RDL", "Inséré sur la rotule", "Un fléchisseur de hanche"],
      "Bi-articulaire : genou plié = il ne peut plus bien tirer.",
    ],
    [
      "Le soléaire n'est pas…",
      "Un muscle qui croise le genou depuis le fémur",
      ["Sous le gastrocnémien", "Actif en mollets assis", "Relié au tendon d'Achille"],
      "Origine tibia/fibula : le genou n'est pas son affaire.",
    ],
    [
      "Le gastrocnémien n'est pas…",
      "Le meilleur ciblage des mollets assis genou fléchi",
      ["Le muscle du galbe du mollet", "Croiseur du genou", "Partenaire du tendon d'Achille"],
      "Debout jambes tendues pour lui ; assis pour le soléaire.",
    ],
    [
      "Dorsiflexion et flexion plantaire opposent surtout…",
      "Tibial antérieur et mollets (gastroc / soléaire)",
      ["Quadriceps et ischios uniquement", "Moyen et grand fessier", "Piriforme et obturateurs"],
      "Devant on relève ; derrière on pousse vers le sol.",
    ],
    [
      "Toute la force des squats et des sauts finit par passer par…",
      "Les muscles du bas de jambe et le tendon d'Achille",
      ["Le sartorius seul", "Le piriforme seul", "Le vaste intermédiaire seul"],
      "Petits muscles, gros enjeu de transmission au sol.",
    ],
    [
      "Le tendon d'Achille relie les mollets surtout au…",
      "Calcanéum (talon)",
      ["Grand trochanter", "Ischion", "Rotule"],
      "Gastroc + soléaire → talon.",
    ],
    [
      "Lequel croise le genou ?",
      "Le gastrocnémien",
      ["Le soléaire", "Le tibial antérieur", "Le long fibulaire"],
      "Seul le gastroc part du fémur parmi ces mollets / jambe.",
    ],
    [
      "Lequel ne croise pas le genou ?",
      "Le soléaire",
      ["Le gastrocnémien", "Le droit fémoral", "Les ischio-jambiers"],
      "Tibia/fibula → Achille, sans passer par le genou.",
    ],
    [
      "En mollets debout, si tu fléchis trop les genoux, tu bascules vers…",
      "Un travail plus soléaire, moins gastroc",
      ["Un travail de droit fémoral isolé", "Une abduction de moyen fessier", "Un hip thrust"],
      "Genou plié = recette du soléaire.",
    ],
    [
      "Le long fibulaire n'est pas…",
      "Le muscle qui relève surtout le pied devant",
      ["Un stabilisateur de cheville", "Situé sur le bord externe", "Utile contre les entorses"],
      "Le releveur avant, c'est le tibial antérieur.",
    ],
    [
      "Le tibial antérieur n'est pas…",
      "Un fléchisseur plantaire via l'Achille",
      ["Un dorsiflexeur", "Situé devant la jambe", "Utile à la marche"],
      "Il s'oppose aux mollets, il ne les rejoint pas sur l'Achille.",
    ],
    [
      "Deux exercices, deux muscles, un tendon : c'est le duo…",
      "Gastrocnémien et soléaire",
      ["Moyen et petit fessier", "Semi-tendineux et semi-membraneux", "Vaste médial et vaste latéral"],
      "Debout / assis, même Achille.",
    ],
    [
      "La fibula sert d'origine notamment au…",
      "Soléaire (avec le tibia)",
      ["Droit fémoral", "Grand fessier", "Ilio-psoas"],
      "Tibia + fibula = ancrage du soléaire.",
    ],
    [
      "Une entorse de cheville met souvent en cause le contrôle du…",
      "Long fibulaire (parmi d'autres stabilisateurs)",
      ["Vaste intermédiaire", "Piriforme seul", "Sartorius"],
      "Bord externe : stabilité face aux inversions.",
    ],
    [
      "Le galbe visible du mollet correspond surtout au…",
      "Gastrocnémien",
      ["Soléaire profond seul", "Tibial antérieur", "Long fibulaire"],
      "Le gastroc donne le relief ; le soléaire est dessous.",
    ],
    [
      "Pour isoler le soléaire, le geste clé est…",
      "Fléchir le genou (mollets assis)",
      ["Tendre le genou au maximum comme un RDL", "Écarter la hanche", "Relever la pointe du pied"],
      "Genou fléchi = gastroc hors-jeu relatif.",
    ],
  ])
];
