import { bank25 } from "./qcm-bank";
import type { SeedQuestion } from "../anatomie-quiz-helpers";

export const THEME_2_QUIZZES: SeedQuestion[][] = [
  bank25([
    [
      "Combien de chefs compose le quadriceps ?",
      "Quatre",
      ["Deux", "Trois", "Cinq"],
      "Vaste latéral, médial, intermédiaire et droit fémoral.",
    ],
    [
      "Les quatre chefs du quadriceps convergent d'abord vers…",
      "La rotule, puis le tibia",
      ["Le calcanéum via le tendon d'Achille", "Le grand trochanter", "L'ischion"],
      "Tous se réunissent vers la rotule avant de rejoindre le tibia.",
    ],
    [
      "L'action commune des quatre chefs du quadriceps est…",
      "Étendre le genou",
      ["Fléchir le genou", "Adduire la hanche", "Pointer le pied"],
      "Leg extension, squat, presse : le genou se tend grâce au quadriceps.",
    ],
    [
      "Quel chef du quadriceps croise aussi la hanche ?",
      "Le droit fémoral",
      ["Le vaste latéral", "Le vaste médial", "Le vaste intermédiaire"],
      "Seul le droit fémoral est bi-articulaire : genou et hanche.",
    ],
    [
      "Le droit fémoral aide aussi à…",
      "Fléchir la hanche",
      ["Étendre uniquement la hanche", "Supiner le pied", "Ouvrir l'omoplate"],
      "Il fléchit la hanche en plus d'étendre le genou.",
    ],
    [
      "Les vastes (latéral, médial, intermédiaire) n'agissent principalement que sur…",
      "Le genou",
      ["La hanche et le genou", "La cheville", "Le bassin seul"],
      "Contrairement au droit fémoral, ils ne croisent pas la hanche.",
    ],
    [
      "Quel muscle est le spécialiste de la flexion de hanche ?",
      "L'ilio-psoas",
      ["Le grand fessier", "Le soléaire", "Le biceps fémoral"],
      "Il relie lombaires et bassin au fémur et remonte le genou.",
    ],
    [
      "L'ilio-psoas relie surtout…",
      "Les lombaires et le bassin au fémur",
      ["La rotule au tibia", "Le sacrum au calcanéum", "L'omoplate à l'humérus"],
      "Ancrage profond : rachis lombaire / bassin → fémur.",
    ],
    [
      "Dans les relevés de jambes, le muscle qui remonte surtout le genou vers la poitrine est…",
      "L'ilio-psoas",
      ["Le tenseur du fascia lata", "Le gastrocnémien", "Le tibial antérieur"],
      "Flexion de hanche profonde = ilio-psoas.",
    ],
    [
      "Le TFL (tenseur du fascia lata) aide surtout à…",
      "Stabiliser le bassin",
      ["Étendre le genou comme le quadriceps", "Pointer le pied", "Tourner uniquement le cou"],
      "Il travaille sur le côté pour tenir le bassin.",
    ],
    [
      "Le sartorius traverse la cuisse…",
      "En écharpe jusqu'au tibia",
      ["Tout droit vers le calcanéum", "Vers le grand trochanter seulement", "Vers le sternum"],
      "Long muscle en bandoulière, face antérieure de cuisse.",
    ],
    [
      "Leg extension, squat et presse à cuisses ont en commun de…",
      "Tendre le genou contre une résistance",
      ["Fléchir uniquement la cheville", "Adduire la hanche sans genou", "Étendre le coude"],
      "Dès que le genou s'étend chargé, le quadriceps commande.",
    ],
    [
      "Le vaste médial se situe plutôt…",
      "Côté interne de la cuisse, près du genou",
      ["Côté externe comme le biceps fémoral", "Sous le soléaire", "Sur le sacrum"],
      "Les vastes encadrent le genou : médial en dedans, latéral en dehors.",
    ],
    [
      "Le vaste latéral se situe plutôt…",
      "Côté externe de la cuisse",
      ["Côté interne comme le gracile", "Derrière l'ischion seulement", "Devant le tibia"],
      "C'est le chef le plus externe du quadriceps.",
    ],
    [
      "Le vaste intermédiaire est surtout…",
      "Profond, sous le droit fémoral",
      ["Le plus superficiel de la fesse", "Un muscle de la cheville", "Un rotateur du sacrum"],
      "Il est caché sous le droit fémoral, entre les deux vastes.",
    ],
    [
      "Si tu veux distinguer droit fémoral et vastes, retiens que…",
      "Seul le droit fémoral fléchit aussi la hanche",
      ["Seuls les vastes fléchissent la hanche", "Le droit fémoral n'étend jamais le genou", "Les vastes s'insèrent sur le calcanéum"],
      "Même extension de genou ; la hanche trahit le droit fémoral.",
    ],
    [
      "Devant de cuisse, le muscle extenseur de genou dominant est…",
      "Le quadriceps",
      ["Les ischio-jambiers", "Le grand fessier", "Le soléaire"],
      "Les ischios fléchissent le genou ; le quadriceps l'étend.",
    ],
    [
      "Un muscle bi-articulaire du devant de cuisse, c'est surtout…",
      "Le droit fémoral",
      ["Le vaste intermédiaire", "Le soléaire", "Le petit fessier"],
      "Hanche + genou : droit fémoral (et sartorius, plus latéral).",
    ],
    [
      "Le TFL n'est pas…",
      "Le chef principal d'extension du genou",
      ["Un muscle du côté de la hanche", "Un aide à la stabilité du bassin", "Un muscle de la face latérale"],
      "L'extension du genou reste l'affaire du quadriceps.",
    ],
    [
      "Le sartorius se termine vers…",
      "Le tibia",
      ["Le calcanéum", "La rotule uniquement", "Le sacrum"],
      "Il descend en écharpe jusqu'au tibia.",
    ],
    [
      "L'ilio-psoas n'est pas…",
      "Un extenseur de genou comme le quadriceps",
      ["Un fléchisseur de hanche", "Un muscle profond", "Relié aux lombaires"],
      "Il fléchit la hanche ; ce n'est pas un chef du quadriceps.",
    ],
    [
      "En squat, quand le genou se tend pour remonter, le moteur principal côté cuisse avant est…",
      "Le quadriceps",
      ["Le tibial antérieur", "Le piriforme", "Le long fibulaire"],
      "Extension de genou chargée = quadriceps.",
    ],
    [
      "Quel couple décrit le mieux le devant de cuisse ?",
      "Quadriceps (genou) + fléchisseurs de hanche",
      ["Ischios + grand fessier uniquement", "Gastrocnémien + soléaire", "Piriforme + obturateurs"],
      "Extenseur de genou dominant, épaulé par les fléchisseurs de hanche.",
    ],
    [
      "Le droit fémoral se distingue des vastes parce qu'il…",
      "Croise deux articulations",
      ["S'arrête sur le calcanéum", "Naît sur l'ischion", "Ne touche jamais le genou"],
      "Hanche et genou : un muscle, deux articulations.",
    ],
    [
      "Lequel n'est pas un chef du quadriceps ?",
      "Le sartorius",
      ["Le vaste latéral", "Le vaste médial", "Le droit fémoral"],
      "Le sartorius est à part, en écharpe ; les quatre chefs sont VL, VM, VI, DF.",
    ],
  ]),

  bank25([
    [
      "Combien d'ischio-jambiers compte-t-on classiquement ?",
      "Trois",
      ["Deux", "Quatre comme le quadriceps", "Un seul muscle massif"],
      "Biceps fémoral, semi-tendineux et semi-membraneux.",
    ],
    [
      "Côté externe de l'arrière de cuisse, on trouve surtout…",
      "Le biceps fémoral",
      ["Le semi-tendineux", "Le semi-membraneux", "Le gracile"],
      "Le biceps fémoral est l'ischio latéral.",
    ],
    [
      "Côté interne de l'arrière de cuisse, on trouve…",
      "Le semi-tendineux et le semi-membraneux",
      ["Le biceps fémoral seul", "Le vaste latéral", "Le long fibulaire"],
      "Les deux « semi » occupent le versant médial.",
    ],
    [
      "Les ischios naissent presque tous sur…",
      "L'ischion",
      ["La rotule", "Le calcanéum", "Les lombaires"],
      "L'ischion : l'os sur lequel tu t'assois.",
    ],
    [
      "Les deux actions principales des ischios sont…",
      "Fléchir le genou et étendre la hanche",
      ["Étendre le genou et fléchir la hanche", "Adduire uniquement la cheville", "Dorsiflexer le pied"],
      "Leg curl d'un côté, RDL de l'autre.",
    ],
    [
      "Le leg curl cible surtout…",
      "La flexion du genou par les ischios",
      ["L'extension du genou par le quadriceps", "Les mollets assis", "Le tibial antérieur"],
      "Genou qui plie contre une résistance = ischios.",
    ],
    [
      "Le soulevé de terre roumain (RDL) nourrit surtout…",
      "L'extension de hanche des ischios",
      ["La dorsiflexion", "L'abduction du moyen fessier seule", "Les relevés de jambes de l'ilio-psoas"],
      "Ramener la cuisse en arrière : deuxième métier des ischios.",
    ],
    [
      "En RDL, la sensation d'étirement intense derrière la cuisse vient du fait que les ischios…",
      "S'allongent sur deux articulations à la fois",
      ["Ne croisent qu'une articulation", "Travaillent comme le soléaire", "Se raccourcissent au genou et à la hanche"],
      "Hanche qui plie, genou qui reste tendu : double allongement.",
    ],
    [
      "Pour étirer fort les ischios en RDL, le genou doit plutôt…",
      "Rester tendu (ou presque)",
      ["Être complètement fléchi comme au leg curl", "Pointer en rotation interne forcée", "Être verrouillé en dorsiflexion"],
      "Genou tendu + hanche qui fléchit = ischios allongés aux deux bouts.",
    ],
    [
      "Sous les ischios, côté interne, le muscle massif à retenir est…",
      "Le grand adducteur",
      ["Le droit fémoral", "Le piriforme", "Le tibial antérieur"],
      "Il rapproche la cuisse de l'axe et charge fort en squat large.",
    ],
    [
      "Le grand adducteur sert surtout à…",
      "Ramener la cuisse en dedans",
      ["Étendre le coude", "Relever le pied", "Tourner la tête"],
      "Adduction = rapprocher la cuisse de la ligne médiane.",
    ],
    [
      "Les squats larges sollicitent particulièrement…",
      "Le grand adducteur",
      ["Le biceps brachial", "Le deltoïde antérieur", "Le tibial antérieur"],
      "Stance large = face interne de cuisse davantage au travail.",
    ],
    [
      "Ischios et quadriceps s'opposent surtout sur…",
      "La flexion versus l'extension du genou",
      ["La dorsiflexion versus la flexion plantaire", "L'abduction versus l'adduction d'épaule", "La rotation du cou"],
      "Ischios plient le genou ; quadriceps le tend.",
    ],
    [
      "Le biceps fémoral n'est pas…",
      "Un chef du quadriceps",
      ["Un ischio côté externe", "Un fléchisseur de genou", "Un extenseur de hanche possible"],
      "Même mot « biceps », autre région : c'est un ischio, pas un vaste.",
    ],
    [
      "Un programme complet pour les ischios nourrit…",
      "Les deux fonctions : genou et hanche",
      ["Uniquement le leg curl", "Uniquement les relevés de mollets", "Uniquement l'abduction de hanche"],
      "Leg curl + RDL (ou équivalent) plutôt qu'un seul pattern.",
    ],
    [
      "Étendre la hanche, pour les ischios, signifie…",
      "Ramener la cuisse en arrière",
      ["Monter le genou vers la poitrine", "Écarter la cuisse sur le côté", "Pointer le pied"],
      "C'est le geste du RDL et du verrouillage de hanche.",
    ],
    [
      "Le semi-tendineux se situe plutôt…",
      "Côté interne, avec le semi-membraneux",
      ["Côté externe, avec le vaste latéral", "Sous le tendon d'Achille", "Sur le sacrum"],
      "Les deux « semi » = versant médial de l'arrière de cuisse.",
    ],
    [
      "Lequel n'est pas un ischio-jambier ?",
      "Le droit fémoral",
      ["Le biceps fémoral", "Le semi-tendineux", "Le semi-membraneux"],
      "Le droit fémoral est un chef du quadriceps, devant.",
    ],
    [
      "Naissance des ischios et insertion basse se jouent surtout…",
      "De l'ischion vers l'arrière du genou",
      ["Du pubis vers la rotule", "Du sacrum vers le calcanéum", "Des lombaires vers le petit trochanter"],
      "Ischion → derrière le genou : d'où flexion de genou et extension de hanche.",
    ],
    [
      "Le grand adducteur n'est pas classé parmi…",
      "Les trois ischio-jambiers",
      ["Les muscles de la face interne", "Les adducteurs", "Les muscles utiles en squat large"],
      "Il côtoie les ischios, mais son métier phare reste l'adduction.",
    ],
    [
      "Un leg curl ne remplace pas un RDL parce que…",
      "L'un fléchit surtout le genou, l'autre étend surtout la hanche",
      ["Les deux ciblent uniquement le soléaire", "Le RDL travaille le tibial antérieur", "Le leg curl étend le genou"],
      "Mêmes muscles, deux fonctions à nourrir.",
    ],
    [
      "Si le genou reste tendu pendant que la hanche fléchit, tu allonges surtout…",
      "Les ischio-jambiers",
      ["Le quadriceps entier", "Le soléaire seul", "Le moyen fessier"],
      "C'est le schéma du RDL : double articulation des ischios.",
    ],
    [
      "Le biceps fémoral se distingue des deux « semi » par…",
      "Sa position externe",
      ["Son insertion sur le calcanéum", "Le fait qu'il n'existe pas", "Son rôle de releveur du pied"],
      "Externe = biceps fémoral ; interne = semi-tendineux et semi-membraneux.",
    ],
    [
      "« Presque tous partent de l'ischion » rappelle que les ischios…",
      "Partagent une origine pelvienne commune",
      ["Naissent tous sur la rotule", "Partent du tibia distal", "S'accrochent au sternum"],
      "L'ischion est l'ancrage haut de la plupart des ischios.",
    ],
    [
      "Arrière de cuisse, en une phrase : les ischios…",
      "Plient le genou et aident à étendre la hanche",
      ["Étendent le genou comme le quadriceps", "Relèvent surtout le pied", "Stabilisent uniquement la cheville"],
      "Deux métiers, un même groupe musculaire.",
    ],
  ]),

  bank25([
    [
      "La fonction phare du grand fessier est…",
      "L'extension de hanche",
      ["La dorsiflexion", "L'extension du genou seule", "La flexion de hanche de l'ilio-psoas"],
      "Ramener la cuisse en arrière, redresser le bassin.",
    ],
    [
      "Squat (sortie), soulevé de terre et hip thrust ont en commun…",
      "L'extension de hanche contre résistance",
      ["La flexion plantaire isolée", "L'abduction d'épaule", "La dorsiflexion"],
      "Chaque fois que les hanches avancent chargées, le grand fessier pousse.",
    ],
    [
      "Le hip thrust cible surtout…",
      "Le grand fessier",
      ["Le moyen fessier uniquement", "Le tibial antérieur", "Le droit fémoral"],
      "Extension de hanche horizontale = grand fessier.",
    ],
    [
      "Le moyen fessier se situe plutôt…",
      "Plus haut, sur le côté du bassin",
      ["Tout en profondeur sous le soléaire", "Devant, avec le quadriceps", "Derrière le genou"],
      "C'est le fessier latéral, au-dessus du grand sur le côté.",
    ],
    [
      "L'action d'écarter la cuisse s'appelle…",
      "L'abduction (moyen fessier)",
      ["L'adduction (grand adducteur)", "La flexion plantaire", "L'extension de genou"],
      "Moyen fessier = abduction ; ne pas confondre avec l'adduction interne.",
    ],
    [
      "Le rôle clé du moyen fessier en fente ou montée de marche est…",
      "Stabiliser le bassin en unipodal",
      ["Étendre le genou comme le quadriceps", "Pointer le pied", "Remplacer le tendon d'Achille"],
      "Dès qu'une jambe porte, il tient le bassin.",
    ],
    [
      "Si le moyen fessier est faible, on voit souvent…",
      "Le genou plonger vers l'intérieur",
      ["Le pied se relever tout seul", "Une hyperextension isolée du coude", "Une rotation du rachis cervical"],
      "Perte de stabilité latérale → genou qui rentre.",
    ],
    [
      "Le petit fessier se trouve…",
      "Sous le moyen fessier",
      ["Au-dessus du grand fessier en surface", "Devant la rotule", "Dans le mollet"],
      "Il est profond, caché sous le moyen.",
    ],
    [
      "Moyen et petit fessiers s'insèrent tous deux sur…",
      "Le grand trochanter",
      ["La rotule", "Le calcanéum", "Le pubis uniquement"],
      "La bosse externe du fémur : même destination.",
    ],
    [
      "Puissance derrière, stabilité sur le côté : cela oppose surtout…",
      "Grand fessier et moyen fessier",
      ["Gastrocnémien et soléaire", "Vaste médial et vaste latéral", "Piriforme et tibial antérieur"],
      "Grand = extension ; moyen = abduction / bassin unipodal.",
    ],
    [
      "Lequel n'est pas un fessier ?",
      "Le piriforme",
      ["Le grand fessier", "Le moyen fessier", "Le petit fessier"],
      "Le piriforme est un rotateur profond, sous les fessiers.",
    ],
    [
      "Le grand fessier n'est pas surtout…",
      "Le stabilisateur unipodal du bassin",
      ["Un puissant extenseur de hanche", "Sollicité en hip thrust", "Actif en sortie de squat"],
      "La stabilité unipodale latérale, c'est surtout le moyen fessier.",
    ],
    [
      "Le moyen fessier n'est pas surtout…",
      "Le moteur principal du hip thrust",
      ["Un abducteur de hanche", "Un stabilisateur du bassin", "Situé sur le côté"],
      "Le hip thrust charge l'extension : grand fessier.",
    ],
    [
      "Le petit fessier assiste surtout…",
      "Le moyen fessier comme gardien de la hanche",
      ["Le soléaire en mollets assis", "Le droit fémoral en leg extension", "Le biceps fémoral en curl"],
      "Même famille : abduction et contrôle de hanche.",
    ],
    [
      "Le grand trochanter est…",
      "La bosse externe du fémur",
      ["La rotule", "L'os du talon", "Une vertèbre lombaire"],
      "Point d'arrivée du moyen et du petit fessier.",
    ],
    [
      "En appui sur une jambe, le bassin qui bascule du côté opposé trahit souvent…",
      "Un moyen fessier qui ne tient pas",
      ["Un quadriceps trop fort", "Un soléaire trop court seulement", "Un tibial antérieur hypertrophié"],
      "Le moyen fessier est le gardien latéral du bassin.",
    ],
    [
      "Verrouiller un soulevé de terre en haut, hanches en avant, c'est surtout…",
      "L'extension de hanche du grand fessier",
      ["L'abduction du moyen fessier isolée", "La flexion de hanche de l'ilio-psoas", "La dorsiflexion"],
      "Les hanches avancent contre la barre : grand fessier.",
    ],
    [
      "Les fessiers sont autant des muscles de performance que d'esthétique parce qu'ils…",
      "Produisent de la force et de la stabilité de hanche",
      ["Ne servent qu'à s'asseoir", "Remplacent les mollets", "Étendent uniquement les doigts"],
      "Extension + contrôle latéral : squat, fentes, courses.",
    ],
    [
      "Le petit fessier n'est pas…",
      "Superficiel au moyen fessier",
      ["Plus profond que le moyen", "Inséré sur le grand trochanter", "Un aide à la hanche"],
      "Le petit est sous le moyen, pas au-dessus.",
    ],
    [
      "Abduction de hanche, ce n'est pas…",
      "Rapprocher la cuisse de l'axe (adduction)",
      ["Écarter la cuisse", "Le métier du moyen fessier", "Utile à la stabilité unipodale"],
      "Écarter ≠ rapprocher : moyen fessier vs adducteurs.",
    ],
    [
      "En fente, si le genou avant rentre, tu penses d'abord au…",
      "Moyen fessier",
      ["Grand fessier uniquement comme volume", "Gastrocnémien", "Droit fémoral isolé"],
      "Contrôle frontal du genou : stabilité latérale du moyen fessier.",
    ],
    [
      "Le grand fessier se distingue du moyen par…",
      "Sa puissance d'extension plutôt que l'abduction",
      ["Son insertion sur la rotule", "Le fait qu'il relève le pied", "Son origine sur le tibia"],
      "Même région, métiers différents.",
    ],
    [
      "Moyen et petit fessiers partagent…",
      "Une insertion sur le grand trochanter",
      ["Le tendon d'Achille", "Une insertion sur la rotule", "Une origine sur le calcanéum"],
      "Tous deux rejoignent la bosse externe du fémur.",
    ],
    [
      "Lequel décrit le mieux le trio fessier ?",
      "Grand = poussée ; moyen et petit = côté et stabilité",
      ["Tous les trois étendent uniquement le genou", "Tous les trois sont des mollets", "Tous les trois naissent sur l'ischion comme les ischios seuls"],
      "Puissance derrière, gardiens sur le flanc.",
    ],
    [
      "Le grand fessier n'est pas un simple coussin : sa vraie force, c'est…",
      "Pousser les hanches en extension",
      ["Fléchir le genou comme un ischio isolé", "Dorsiflexer", "Serrer uniquement les omoplates"],
      "Sortie de squat, DL, hip thrust : hanches qui avancent.",
    ],
  ]),

  bank25([
    [
      "Pourquoi faire des mollets assis ET debout ?",
      "Parce que le mollet, ce sont deux muscles",
      ["Parce que le quadriceps a quatre chefs", "Parce que le tendon d'Achille n'existe qu'assis", "Parce que le tibial antérieur travaille assis"],
      "Gastrocnémien debout, soléaire assis : deux cibles.",
    ],
    [
      "Le gastrocnémien part du…",
      "Fémur, donc il croise le genou",
      ["Tibia et fibula seulement, comme le soléaire", "Calcanéum uniquement", "Sacrum"],
      "Origine fémorale : le genou compte pour lui.",
    ],
    [
      "Debout, jambes tendues, le mollet qui travaille à plein est surtout…",
      "Le gastrocnémien",
      ["Le soléaire (genou fléchi)", "Le tibial antérieur", "Le droit fémoral"],
      "Genou tendu = gastroc disponible.",
    ],
    [
      "Le soléaire part du…",
      "Tibia et de la fibula",
      ["Fémur, comme le gastrocnémien", "Ischion", "Rotule"],
      "Le genou ne le concerne pas : origine sous le genou.",
    ],
    [
      "Assis, genou fléchi, les mollets ciblent surtout…",
      "Le soléaire",
      ["Le gastrocnémien", "Le quadriceps", "Le grand fessier"],
      "Gastroc raccourci / détendu ; le soléaire fournit l'effort.",
    ],
    [
      "Gastrocnémien et soléaire partagent…",
      "Le tendon d'Achille",
      ["La rotule", "La patte d'oie", "Le grand trochanter"],
      "Deux muscles, un même tendon vers le talon.",
    ],
    [
      "Le tibial antérieur sert surtout à…",
      "Relever le pied (dorsiflexion)",
      ["La flexion plantaire des mollets", "L'extension de hanche", "L'adduction de cuisse"],
      "C'est le grand releveur, devant la jambe.",
    ],
    [
      "Quand tu marches, le tibial antérieur empêche surtout…",
      "La pointe du pied de traîner",
      ["Le genou de s'étendre", "La hanche de fléchir", "Les ischios de naître sur l'ischion"],
      "Dorsiflexion = pied qui décolle du sol.",
    ],
    [
      "Le long fibulaire, sur le bord externe, sert surtout à…",
      "Stabiliser la cheville et limiter les entorses",
      ["Étendre le genou", "Fléchir la hanche", "Remplacer le grand fessier"],
      "Petit muscle, gros enjeu de stabilité latérale.",
    ],
    [
      "Mollets assis : le gastrocnémien est moins efficace parce qu'il est…",
      "Raccourci / détendu, genou fléchi",
      ["Plus long qu'en RDL", "Inséré sur la rotule", "Un fléchisseur de hanche"],
      "Bi-articulaire : genou plié = il ne peut plus bien tirer.",
    ],
    [
      "Le soléaire n'est pas…",
      "Un muscle qui croise le genou depuis le fémur",
      ["Sous le gastrocnémien", "Actif en mollets assis", "Relié au tendon d'Achille"],
      "Origine tibia/fibula : le genou n'est pas son affaire.",
    ],
    [
      "Le gastrocnémien n'est pas…",
      "Le meilleur ciblage des mollets assis genou fléchi",
      ["Le muscle du galbe du mollet", "Croiseur du genou", "Partenaire du tendon d'Achille"],
      "Debout jambes tendues pour lui ; assis pour le soléaire.",
    ],
    [
      "Dorsiflexion et flexion plantaire opposent surtout…",
      "Tibial antérieur et mollets (gastroc / soléaire)",
      ["Quadriceps et ischios uniquement", "Moyen et grand fessier", "Piriforme et obturateurs"],
      "Devant on relève ; derrière on pousse vers le sol.",
    ],
    [
      "Toute la force des squats et des sauts finit par passer par…",
      "Les muscles du bas de jambe et le tendon d'Achille",
      ["Le sartorius seul", "Le piriforme seul", "Le vaste intermédiaire seul"],
      "Petits muscles, gros enjeu de transmission au sol.",
    ],
    [
      "Le tendon d'Achille relie les mollets surtout au…",
      "Calcanéum (talon)",
      ["Grand trochanter", "Ischion", "Rotule"],
      "Gastroc + soléaire → talon.",
    ],
    [
      "Lequel croise le genou ?",
      "Le gastrocnémien",
      ["Le soléaire", "Le tibial antérieur", "Le long fibulaire"],
      "Seul le gastroc part du fémur parmi ces mollets / jambe.",
    ],
    [
      "Lequel ne croise pas le genou ?",
      "Le soléaire",
      ["Le gastrocnémien", "Le droit fémoral", "Les ischio-jambiers"],
      "Tibia/fibula → Achille, sans passer par le genou.",
    ],
    [
      "En mollets debout, si tu fléchis trop les genoux, tu bascules vers…",
      "Un travail plus soléaire, moins gastroc",
      ["Un travail de droit fémoral isolé", "Une abduction de moyen fessier", "Un hip thrust"],
      "Genou plié = recette du soléaire.",
    ],
    [
      "Le long fibulaire n'est pas…",
      "Le muscle qui relève surtout le pied devant",
      ["Un stabilisateur de cheville", "Situé sur le bord externe", "Utile contre les entorses"],
      "Le releveur avant, c'est le tibial antérieur.",
    ],
    [
      "Le tibial antérieur n'est pas…",
      "Un fléchisseur plantaire via l'Achille",
      ["Un dorsiflexeur", "Situé devant la jambe", "Utile à la marche"],
      "Il s'oppose aux mollets, il ne les rejoint pas sur l'Achille.",
    ],
    [
      "Deux exercices, deux muscles, un tendon : c'est le duo…",
      "Gastrocnémien et soléaire",
      ["Moyen et petit fessier", "Semi-tendineux et semi-membraneux", "Vaste médial et vaste latéral"],
      "Debout / assis, même Achille.",
    ],
    [
      "La fibula sert d'origine notamment au…",
      "Soléaire (avec le tibia)",
      ["Droit fémoral", "Grand fessier", "Ilio-psoas"],
      "Tibia + fibula = ancrage du soléaire.",
    ],
    [
      "Une entorse de cheville met souvent en cause le contrôle du…",
      "Long fibulaire (parmi d'autres stabilisateurs)",
      ["Vaste intermédiaire", "Piriforme seul", "Sartorius"],
      "Bord externe : stabilité face aux inversions.",
    ],
    [
      "Le galbe visible du mollet correspond surtout au…",
      "Gastrocnémien",
      ["Soléaire profond seul", "Tibial antérieur", "Long fibulaire"],
      "Le gastroc donne le relief ; le soléaire est dessous.",
    ],
    [
      "Pour isoler le soléaire, le geste clé est…",
      "Fléchir le genou (mollets assis)",
      ["Tendre le genou au maximum comme un RDL", "Écarter la hanche", "Relever la pointe du pied"],
      "Genou fléchi = gastroc hors-jeu relatif.",
    ],
  ]),

  bank25([
    [
      "L'adduction, c'est…",
      "Rapprocher un membre de l'axe du corps",
      ["L'écarter (abduction)", "Étendre le genou", "Relever le pied"],
      "Face interne de cuisse : tout le groupe est bâti pour ça.",
    ],
    [
      "Les adducteurs naissent surtout sur…",
      "Le pubis et l'ischion",
      ["La rotule et le calcanéum", "Le sacrum uniquement", "L'omoplate"],
      "Pubis / ischion → fémur.",
    ],
    [
      "Le plus massif du groupe des adducteurs est…",
      "Le grand adducteur",
      ["Le gracile", "Le pectiné", "Le court adducteur"],
      "Volume majeur de la face interne ; déjà croisé à l'arrière de cuisse.",
    ],
    [
      "Selon ses fibres, le grand adducteur peut aussi…",
      "Aider à étendre la hanche",
      ["Dorsiflexer le pied", "Étendre le coude", "Remplacer le tibial antérieur"],
      "Pas seulement serrer : certaines fibres participent à l'extension.",
    ],
    [
      "Le gracile se distingue parce qu'il descend jusqu'au…",
      "Tibia, via la patte d'oie",
      ["Calcanéum", "Grand trochanter seulement", "Sternum"],
      "Long ruban : ce n'est pas un adducteur « fémur only ».",
    ],
    [
      "Outre l'adduction, le gracile participe un peu à…",
      "La flexion du genou",
      ["La flexion plantaire", "L'extension du genou comme le quadriceps", "La dorsiflexion"],
      "Insertion tibiale : il croise aussi le genou.",
    ],
    [
      "Lequel fait partie du groupe des adducteurs ?",
      "Le pectiné",
      ["Le moyen fessier", "Le soléaire", "Le droit fémoral"],
      "Long, court, pectiné, grand adducteur — et le gracile à part.",
    ],
    [
      "En squat, surtout avec une stance large, les adducteurs…",
      "Travaillent fort et aident à contrôler les genoux",
      ["Sont totalement au repos", "Remplacent le tendon d'Achille", "N'agissent que sur les orteils"],
      "Ils font plus que « serrer les cuisses » sur une machine.",
    ],
    [
      "Des adducteurs raides ou faibles se paient souvent sur…",
      "La profondeur du squat ou la stabilité du genou",
      ["La seule hauteur des épaules", "La pronation de l'avant-bras", "La dorsiflexion isolée"],
      "Amplitude de hanche et trajectoire du genou trinquent.",
    ],
    [
      "Adduction et abduction de hanche opposent surtout…",
      "Adducteurs et moyen fessier",
      ["Gastrocnémien et soléaire", "Droit fémoral et vastes", "Tibial antérieur et long fibulaire"],
      "Rapprocher (interne) versus écarter (moyen fessier).",
    ],
    [
      "Le grand adducteur n'est pas…",
      "Un abducteur comme le moyen fessier",
      ["Le plus massif du groupe", "Capable d'aider l'extension de hanche", "Ancré pubis/ischion vers le fémur"],
      "Interne = rapprocher ; le moyen écarte.",
    ],
    [
      "Le gracile n'est pas…",
      "Un muscle qui s'arrête uniquement sur le fémur",
      ["Un long ruban jusqu'au tibia", "Un participant à la patte d'oie", "Un peu fléchisseur de genou"],
      "C'est précisément sa descente tibiale qui le met à part.",
    ],
    [
      "Long adducteur, court adducteur, pectiné et grand adducteur vont surtout vers…",
      "Le fémur",
      ["Le calcanéum", "La rotule en chef unique", "Les lombaires"],
      "Le gracile est l'exception qui continue vers le tibia.",
    ],
    [
      "La patte d'oie, pour le gracile, se trouve sur…",
      "Le tibia",
      ["Le grand trochanter", "Le sacrum", "Le calcanéum"],
      "Terminaison distale interne, sous le genou.",
    ],
    [
      "Rapprocher la cuisse de la ligne médiane, ce n'est pas…",
      "L'abduction",
      ["L'adduction", "Le métier de la face interne", "Utile en squat large"],
      "Le vocabulaire inverse est le piège classique.",
    ],
    [
      "Le pectiné appartient à…",
      "La famille des adducteurs",
      ["Les trois ischios", "Les trois fessiers", "Les deux mollets"],
      "Petit, haut, près du pubis, mais bien du groupe interne.",
    ],
    [
      "Le court adducteur se situe plutôt…",
      "Plus profond / plus haut que le long, toujours interne",
      ["Sur le mollet externe", "Sous le moyen fessier", "Devant le tibia"],
      "Long, court, pectiné : étages de la face interne.",
    ],
    [
      "Contrôler la trajectoire des genoux en squat large, ce n'est pas seulement le quadriceps : il y a aussi…",
      "Les adducteurs",
      ["Le tibial antérieur seul", "Le piriforme comme volume de fesse", "Le soléaire isolé"],
      "Face interne = guide de hanche et de genou.",
    ],
    [
      "Le grand adducteur avait déjà été croisé dans la leçon…",
      "Arrière de cuisse",
      ["Bas de jambes (mollets)", "Rotateurs profonds uniquement", "Devant de cuisse comme chef du quadriceps"],
      "Même muscle, rappel interne sous les ischios.",
    ],
    [
      "Si la profondeur de squat bloque, une piste musculaire interne est…",
      "Des adducteurs raides",
      ["Un tibial antérieur trop fort seulement", "Un long fibulaire trop court uniquement", "Un droit fémoral qui n'existe pas"],
      "Raideur interne = hanche qui n'ouvre pas assez.",
    ],
    [
      "Faiblesse des adducteurs et genou instable : le lien, c'est…",
      "Le contrôle de la trajectoire en appui",
      ["La seule dorsiflexion", "L'insertion sur l'Achille", "Le volume du gastroc"],
      "Ils aident à tenir le membre sur l'axe.",
    ],
    [
      "Lequel n'est pas un adducteur de cuisse ?",
      "Le moyen fessier",
      ["Le long adducteur", "Le grand adducteur", "Le pectiné"],
      "Le moyen fessier écarte : c'est l'antagoniste logique.",
    ],
    [
      "Fibres du grand adducteur et extension de hanche : à retenir que…",
      "Certaines fibres peuvent y contribuer",
      ["Aucune fibre ne peut étendre la hanche", "Toutes les fibres dorsiflexent", "Il remplace le quadriceps"],
      "Selon les fibres, adduction et un peu d'extension.",
    ],
    [
      "Pubis et ischion, pour les adducteurs, c'est surtout…",
      "L'origine haute du groupe",
      ["L'insertion sur le talon", "La patte d'oie", "Le tendon d'Achille"],
      "Haut du groupe = bassin ; bas = fémur (sauf gracile).",
    ],
    [
      "En une phrase, la face interne de cuisse…",
      "Rapproche l'axe et aide squat large / genou",
      ["Étend uniquement le genou", "Relève uniquement le pied", "Tourne uniquement la tête fémorale comme le piriforme"],
      "Adduction, contrôle, et un peu d'extension via le grand.",
    ],
  ]),

  bank25([
    [
      "Le piriforme part du…",
      "Sacrum vers le grand trochanter",
      ["Ischion vers le tibia comme un ischio", "Fémur vers l'Achille", "Pubis vers la rotule"],
      "Petit trajet profond : sacrum → bosse externe du fémur.",
    ],
    [
      "Autour du piriforme, on trouve notamment…",
      "Les obturateurs, les jumeaux et le carré fémoral",
      ["Les quatre chefs du quadriceps", "Gastrocnémien et soléaire", "Vaste médial et vaste latéral"],
      "Tout l'étage des rotateurs profonds.",
    ],
    [
      "L'action commune de ces muscles profonds est surtout…",
      "La rotation externe de hanche",
      ["L'extension de genou", "La dorsiflexion", "L'adduction maximale isolée"],
      "Ils tournent la cuisse vers l'extérieur.",
    ],
    [
      "Leur vrai métier n'est pas la force visible, c'est…",
      "Le centrage de la tête du fémur dans sa cavité",
      ["Le volume de la fesse", "Le galbe du mollet", "L'épaisseur du quadriceps"],
      "Ils maintiennent la hanche et freinent les rotations parasites.",
    ],
    [
      "Le nerf sciatique passe juste à côté du…",
      "Piriforme",
      ["Grand fessier uniquement comme volume", "Soléaire", "Droit fémoral"],
      "Proximité anatomique : d'où le syndrome du piriforme.",
    ],
    [
      "Quand le piriforme est trop tendu, il peut…",
      "Irriter le nerf sciatique",
      ["Raccourcir le tendon d'Achille", "Bloquer la rotule en extension", "Atrophier le tibial antérieur d'emblée"],
      "C'est le syndrome du piriforme.",
    ],
    [
      "Face au syndrome du piriforme, on privilégie souvent…",
      "Mobilité et renforcement progressif plutôt que des étirements agressifs seuls",
      ["Uniquement des étirements forcés", "Uniquement des mollets assis", "L'abandon de toute hanche"],
      "L'agressivité d'étirement n'est pas la solution unique.",
    ],
    [
      "Le volume visible de la fesse vient surtout du…",
      "Grand fessier",
      ["Piriforme", "Carré fémoral", "Obturateur interne"],
      "Les profonds donnent la précision, pas le galbe.",
    ],
    [
      "La précision / le centrage de la hanche vient surtout des…",
      "Rotateurs profonds",
      ["Quatre vastes du quadriceps", "Deux mollets", "Tibial antérieur"],
      "Petit étage, gros rôle de guidage.",
    ],
    [
      "En fente ou en unipodal, les rotateurs profonds…",
      "Freinent les rotations parasites",
      ["Étendent le genou comme le quadriceps", "Remplacent le tendon d'Achille", "Font le volume du mollet"],
      "Changement de direction, appui instable : ils recentrent.",
    ],
    [
      "Le piriforme n'est pas…",
      "Le muscle qui fait le volume de la fesse",
      ["Un rotateur externe", "Tendu du sacrum au grand trochanter", "Voisin du nerf sciatique"],
      "Ne pas le confondre avec le grand fessier.",
    ],
    [
      "Le grand fessier n'est pas…",
      "Le voisin direct du nerf sciatique comme le piriforme",
      ["Un puissant extenseur de hanche", "Le volume de la fesse", "Sollicité en hip thrust"],
      "Sciatique / piriforme : étage profond, pas le galbe.",
    ],
    [
      "Les obturateurs font partie…",
      "Des rotateurs profonds de hanche",
      ["Des chefs du quadriceps", "Des ischio-jambiers", "Des mollets"],
      "Obturateur interne et externe, autour du piriforme.",
    ],
    [
      "Les jumeaux (de hanche) sont…",
      "Des rotateurs profonds, près du piriforme",
      ["Les deux chefs du gastrocnémien uniquement", "Deux vastes du quadriceps", "Les deux fessiers superficiels"],
      "Jumeaux supérieur et inférieur : étage profond.",
    ],
    [
      "Le carré fémoral est…",
      "Un rotateur externe profond",
      ["Un chef du quadriceps", "Un adducteur jusqu'au tibia", "Un dorsiflexeur"],
      "Même famille que piriforme, obturateurs et jumeaux.",
    ],
    [
      "Le grand trochanter, pour le piriforme, est…",
      "Son insertion sur le fémur",
      ["Son origine sur le sacrum", "Le talon", "La rotule"],
      "Départ sacrum, arrivée grand trochanter.",
    ],
    [
      "Centrer la tête fémorale, ce n'est pas…",
      "Produire le volume visible du grand fessier",
      ["Le métier des rotateurs profonds", "Utile en fente", "Utile aux changements de direction"],
      "Force visible ≠ centrage articulaire.",
    ],
    [
      "On parle peu de ces muscles en salle jusqu'au jour où…",
      "Ils se manifestent (douleur, sciatique, hanche instable)",
      ["Ils hypertrophient comme un quadriceps", "Ils remplacent les mollets", "Ils étendent le genou"],
      "Étage silencieux, jusqu'au symptôme.",
    ],
    [
      "Étirements agressifs comme seule solution : à retenir que…",
      "Ce n'est souvent pas la meilleure stratégie unique",
      ["C'est le protocole obligatoire", "Ça remplace le renforcement", "Ça soigne le tendon d'Achille"],
      "Mobilité + renforcement progressif font souvent mieux.",
    ],
    [
      "Rotation externe de cuisse, ce n'est pas le métier principal du…",
      "Grand fessier comme muscle de volume / extension",
      ["Piriforme", "Carré fémoral", "Obturateurs"],
      "Les profonds tournent ; le grand fessier pousse surtout en extension.",
    ],
    [
      "Moyen fessier et rotateurs profonds se rejoignent sur l'idée de…",
      "Contrôle de hanche, pas seulement de poussée",
      ["Dorsiflexion", "Extension de genou", "Flexion plantaire"],
      "Stabilité vs précision rotatoire : même hanche, autres fibres.",
    ],
    [
      "Lequel n'appartient pas à l'étage des rotateurs profonds ?",
      "Le grand fessier",
      ["Le piriforme", "Les obturateurs", "Le carré fémoral"],
      "Le grand fessier est superficiel et puissant.",
    ],
    [
      "Syndrome du piriforme : le piège est de…",
      "Le confondre avec une simple « fesse trop petite »",
      ["Ignorer le nerf sciatique tout près", "Oublier le sacrum comme origine", "Croire que le muscle va au grand trochanter"],
      "C'est un problème de proximité nerveuse, pas de volume.",
    ],
    [
      "En changement de direction, les profonds servent à…",
      "Freiner les rotations qui feraient déraper la tête fémorale",
      ["Tendre le genou comme un leg extension", "Pointer le pied", "Serrer uniquement les adducteurs"],
      "Frein rotatoire = hanche qui reste dans l'axe.",
    ],
    [
      "Volume = grand fessier ; précision = …",
      "Rotateurs profonds",
      ["Soléaire seul", "Vaste intermédiaire seul", "Long fibulaire"],
      "La formule de la leçon, à retenir telle quelle.",
    ],
  ]),
];
