import { CP } from "./checkpoints";
import { buildLesson } from "./build-lesson";

export const THEME_6_LESSONS = [
  buildLesson(
    "Le squat",
    "Hanche, genou, cheville et proportions.",
    [
      `Le **squat** implique principalement la hanche, le genou et la cheville.`,
      `La répartition des contraintes dépend notamment de la **profondeur**, de l'**inclinaison du tronc**, de la **position des pieds**, de la **mobilité de cheville**, des **proportions corporelles** et de la **charge**.`,
      `Il faut éviter les affirmations simplistes comme « le squat travaille uniquement les quadriceps ». Quadriceps, fessiers, adducteurs et stabilisateurs du tronc participent selon la technique.`,
      `À retenir : le squat est un mouvement multi-articulaire dont le profil dépend fortement de la géométrie individuelle.`,
    ],
    ["squat", "exercice"],
    CP.exercices,
    {
      q1: [
        "Le squat mobilise principalement…",
        "Hanche, genou et cheville",
        ["Uniquement le coude", "Seulement l'épaule", "Aucune articulation"],
        "Mouvement multi-articulaire des membres inférieurs.",
      ],
      q2: [
        "La répartition des contraintes au squat dépend notamment de…",
        "Profondeur, position des pieds et proportions",
        ["La couleur des chaussures", "L'heure du repas", "Le nom du coach"],
        "Technique et morphologie modifient le profil.",
      ],
      q3: [
        "Dire que le squat travaille uniquement les quadriceps est…",
        "Une simplification excessive",
        ["Toujours exact", "Faux car le squat ne sollicite rien", "Vrai sans nuance"],
        "Plusieurs groupes musculaires participent.",
      ],
      blank: [
        "Au squat, l'inclinaison du ___ influence les moments au niveau de la hanche.",
        "tronc",
        ["poignet", "cou", "orteil seul"],
        "Position du torse modifie la mécanique.",
      ],
      tf1: [
        "La mobilité de cheville peut influencer la technique de squat.",
        true,
        "Vrai : elle affecte la position du tibia et du tronc.",
      ],
      tf2: [
        "Tous les pratiquants doivent squatter avec exactement la même profondeur et le même stance.",
        false,
        "Faux : morphologie et mobilité varient.",
      ],
      multi: [
        "Quels facteurs influencent la biomécanique du squat ? (plusieurs réponses)",
        ["Profondeur", "Position des pieds", "Inclinaison du tronc", "Proportions corporelles"],
        ["Couleur des chaussures", "Musique en salle", "Prénom du coach"],
        "Squat multi-articulaire à géométrie variable.",
      ],
      order: [
        "Remets dans l'ordre la descente contrôlée au squat :",
        [
          "Flexion simultanée hanche et genou",
          "Contrôle excentrique avec tronc stable",
          "Cheville en dorsiflexion",
          "Atteinte de la profondeur visée",
        ],
        "Plusieurs articulations bougent ensemble.",
      ],
      match: [
        "Associe facteur et effet au squat :",
        [
          ["Stance large", "Plus d'abduction de hanche"],
          ["Tronc penché", "Plus de moment à la hanche"],
          ["Cheville mobile", "Tibia plus vertical possible"],
        ],
        "Technique modifie la répartition des contraintes.",
      ],
      scenario: [
        "Un pratiquant aux chevilles raides penche excessivement le tronc en squat bas. Cause biomécanique probable ?",
        "Compensation pour maintenir le centre de masse sur les pieds malgré mobilité cheville limitée",
        [
          "Manque de force des biceps",
          "Quadriceps trop développés",
          "Gravité absente en squat profond",
        ],
        "Mobilité cheville influence mécanique du squat.",
      ],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Le soulevé de terre",
    "Chaîne postérieure et position de la barre.",
    [
      `Le **soulevé de terre** est principalement un mouvement de production de force par la **chaîne postérieure** et d'extension de la hanche et du genou.`,
      `La position du **bassin**, du **torse** et de la **barre** influence fortement les moments articulaires, notamment au niveau de la colonne.`,
      `Un principe fondamental : **rapprocher la charge du corps** réduit généralement le bras de levier externe au niveau de la colonne.`,
      `À retenir : barre proche + wedge + tension = deadlift plus sûr et plus efficace.`,
    ],
    ["deadlift", "souleve"],
    CP.exercices,
    {
      q1: [
        "Le soulevé de terre sollicite surtout…",
        "La chaîne postérieure et l'extension hanche/genou",
        ["Uniquement les biceps", "Seulement les mollets", "Aucun muscle"],
        "Fessiers, ischios, dos participent fortement.",
      ],
      q2: [
        "Rapprocher la barre du corps au deadlift…",
        "Réduit généralement le bras de levier sur la colonne",
        ["Augmente toujours le stress lombaire", "N'a aucun effet", "Supprime la gravité"],
        "Barre proche = moment réduit sur le dos.",
      ],
      q3: [
        "La position du bassin et du torse…",
        "Influence les moments articulaires",
        ["Est sans importance", "Fixe la masse de la barre", "Remplace les muscles"],
        "Géométrie = répartition des contraintes.",
      ],
      blank: [
        "Au deadlift, garder la barre ___ du corps limite le moment externe sur la colonne.",
        "proche",
        ["loin", "au-dessus de la tête", "derrière le dos"],
        "Distance barre-colonne = levier externe.",
      ],
      tf1: [
        "La position de la barre influence les contraintes sur la colonne.",
        true,
        "Vrai : bras de levier externe variable.",
      ],
      tf2: [
        "Le deadlift n'implique aucune extension de hanche.",
        false,
        "Faux : extension hanche/genou est centrale.",
      ],
      multi: [
        "Quels principes biomécaniques s'appliquent au deadlift ? (plusieurs réponses)",
        ["Barre proche du corps", "Extension hanche et genou", "Chaîne postérieure sollicitée"],
        ["Barre loin du corps pour plus d'efficacité", "Aucune sollicitation du dos", "Flexion uniquement du coude"],
        "Deadlift = force + géométrie + chaîne postérieure.",
      ],
      order: [
        "Remets dans l'ordre la montée au deadlift conventionnel :",
        [
          "Poussée des pieds dans le sol",
          "Extension des genoux puis des hanches",
          "Barre glissant le long des tibias/cuisses",
          "Lockout hanche-genou vertical",
        ],
        "Séquence d'extension sous charge.",
      ],
      match: [
        "Associe principe et bénéfice au deadlift :",
        [
          ["Barre proche", "Réduit moment externe sur colonne"],
          ["Chaîne postérieure", "Fessiers et ischios producteurs de force"],
          ["Position bassin/torse", "Influence répartition des moments"],
        ],
        "Géométrie clé pour sécurité et performance.",
      ],
      scenario: [
        "La barre s'éloigne du corps en milieu de deadlift. Quel risque biomécanique principal ?",
        "Augmentation du moment externe sur la colonne lombaire",
        [
          "Réduction du travail des fessiers",
          "Disparition de la gravité",
          "Amélioration automatique de la technique",
        ],
        "Barre loin = levier externe accru sur le dos.",
      ],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "La presse à cuisses",
    "Pas un simple squat assis.",
    [
      `La **presse à cuisses** permet de travailler fortement les membres inférieurs tout en limitant certaines exigences de **stabilisation** par rapport à un squat libre.`,
      `La **profondeur**, la **position des pieds** et la **mobilité** de la personne changent les angles de hanche et de genou.`,
      `La presse n'est donc pas simplement « un squat assis » : le vecteur de résistance et le profil de stabilité diffèrent.`,
      `À retenir : presse = outil complémentaire avec sa propre biomécanique.`,
    ],
    ["presse", "jambes"],
    CP.exercices,
    {
      q1: [
        "La presse à cuisses diffère du squat libre car…",
        "Le vecteur de résistance et la stabilisation diffèrent",
        ["Elle ne mobilise pas les jambes", "La gravité disparaît", "Les genoux ne fléchissent pas"],
        "Mécanique et stabilité propres à la machine.",
      ],
      q2: [
        "Sur la presse, changer la position des pieds…",
        "Modifie les angles de hanche et genou",
        ["N'a aucun effet", "Supprime le travail musculaire", "Fixe la colonne en flexion"],
        "Stance = géométrie différente.",
      ],
      q3: [
        "La presse permet souvent…",
        "De charger les jambes avec moins d'exigence de stabilité globale",
        ["De remplacer tout entraînement du tronc", "D'éliminer toute contrainte", "De ne jamais fléchir les genoux"],
        "Stabilité guidée par la machine.",
      ],
      blank: [
        "La presse n'est pas un squat assis : le ___ de résistance est différent.",
        "vecteur",
        ["nom", "coach", "miroir"],
        "Direction de la charge ≠ squat libre.",
      ],
      tf1: [
        "La profondeur sur presse modifie les angles articulaires.",
        true,
        "Vrai : comme au squat, la géométrie change.",
      ],
      tf2: [
        "Presse et squat libre ont exactement la même biomécanique.",
        false,
        "Faux : stabilité et vecteur de force diffèrent.",
      ],
      multi: [
        "En quoi la presse diffère-t-elle du squat libre ? (plusieurs réponses)",
        ["Vecteur de résistance différent", "Moins d'exigence de stabilisation globale", "Angles modifiés par position des pieds"],
        ["Aucune flexion de genou", "Gravité absente", "Articulations immobiles"],
        "Presse = biomécanique propre à la machine.",
      ],
      order: [
        "Remets dans l'ordre l'analyse biomécanique de la presse :",
        [
          "Observer le vecteur de résistance de la machine",
          "Repérer position des pieds et profondeur",
          "Identifier angles hanche et genou",
          "Comparer au squat libre si pertinent",
        ],
        "Ne pas assimiler presse et squat assis.",
      ],
      match: [
        "Associe paramètre et effet sur presse :",
        [
          ["Pieds hauts sur plateforme", "Plus de flexion hanche, moins genou"],
          ["Pieds bas", "Plus de flexion genou"],
          ["Profondeur", "Modifie angles articulaires"],
        ],
        "Stance et profondeur modifient la géométrie.",
      ],
      scenario: [
        "Un pratiquant place les pieds hauts sur la presse pour « cibler les fessiers ». Explication biomécanique ?",
        "Position haute augmente la flexion de hanche et modifie les angles articulaires",
        [
          "Les pieds hauts suppriment le travail des jambes",
          "La machine devient un curl biceps",
          "Aucun changement d'angle articulaire",
        ],
        "Position des pieds = géométrie hanche/genou différente.",
      ],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Le développé couché",
    "Pectoraux, triceps et contrôle d'épaule.",
    [
      `Le **développé couché** implique principalement les pectoraux, les triceps et les muscles participant au contrôle de l'**épaule**.`,
      `La **trajectoire de la barre**, la **largeur de prise**, l'**inclinaison du banc** et la **position des coudes** influencent les moments produits au niveau de l'épaule et du coude.`,
      `Une trajectoire légèrement courbe (forme de J) avec omoplates stables est souvent plus efficace qu'une ligne strictement verticale.`,
      `À retenir : bench = interaction entre barre, épaule, coude et scapula.`,
    ],
    ["bench", "developpe"],
    CP.exercices,
    {
      q1: [
        "Le développé couché sollicite notamment…",
        "Pectoraux, triceps et stabilisateurs d'épaule",
        ["Uniquement les mollets", "Seulement les abdos", "Aucun muscle du haut du corps"],
        "Poussée horizontale multi-musculaire.",
      ],
      q2: [
        "La largeur de prise au bench influence…",
        "Les moments à l'épaule et au coude",
        ["Uniquement la respiration", "La masse de la barre", "La couleur des disques"],
        "Prise large vs serrée change la géométrie.",
      ],
      q3: [
        "La trajectoire de la barre au développé couché…",
        "N'est généralement pas une ligne parfaitement verticale",
        ["Doit rester strictement verticale", "Ne dépend pas des coudes", "Ignore les omoplates"],
        "Légère courbe vers les épaules en lockout.",
      ],
      blank: [
        "Au bench, la position des ___ et des omoplates influence la stabilité.",
        "coudes",
        ["chevilles", "orteils", "genoux"],
        "Coudes et scapula conditionnent l'épaule.",
      ],
      tf1: [
        "L'inclinaison du banc modifie le profil musculaire du développé.",
        true,
        "Vrai : incliné vs plat change les angles.",
      ],
      tf2: [
        "Au développé couché, seuls les pectoraux comptent biomécaniquement.",
        false,
        "Faux : triceps et épaule participent fortement.",
      ],
      multi: [
        "Quels paramètres influencent le bench press ? (plusieurs réponses)",
        ["Largeur de prise", "Trajectoire de la barre", "Position des coudes", "Contrôle scapulaire"],
        ["Couleur du banc", "Type de chaussettes", "Heure du repas"],
        "Bench = interaction barre, épaule, coude, scapula.",
      ],
      order: [
        "Remets dans l'ordre une rep de développé couché efficace :",
        [
          "Omoplates rétractées et déprimées",
          "Descente contrôlée vers la poitrine",
          "Coudes sous la barre en position stable",
          "Poussée en légère courbe vers le lockout",
        ],
        "Trajectoire en J, pas ligne verticale stricte.",
      ],
      match: [
        "Associe paramètre et effet au bench :",
        [
          ["Prise large", "Plus de moment épaule, moins coude"],
          ["Prise serrée", "Plus de travail triceps"],
          ["Banc incliné", "Angles d'épaule modifiés"],
        ],
        "Géométrie de la poussée horizontale.",
      ],
      scenario: [
        "Un pratiquant descend la barre très haut sur la poitrine, coudes à 90° latéralement. Quel ajustement biomécanique réduirait le stress épaule ?",
        "Descendre légèrement plus bas poitrine et rapprocher les coudes (~45-75°)",
        [
          "Écarter encore plus les coudes",
          "Supprimer le contrôle scapulaire",
          "Augmenter la prise au maximum sans limite",
        ],
        "Position coudes et trajectoire modifient moments épaule/coude.",
      ],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Le développé militaire",
    "Épaule, scapula et tronc.",
    [
      `Le **développé au-dessus de la tête** nécessite une combinaison de mouvements de l'épaule, de la **scapula** et du **tronc**.`,
      `La capacité à positionner correctement le bras au-dessus de la tête dépend notamment de la **mobilité** et du **contrôle** de l'épaule et de la cage thoracique.`,
      `Sans extension thoracique et contrôle scapulaire, la charge se reporte sur des compensations (cambrure excessive, inclinaison latérale).`,
      `À retenir : overhead press = force d'épaule + mobilité + stabilité du tronc.`,
    ],
    ["militaire", "overhead"],
    CP.exercices,
    {
      q1: [
        "Le développé militaire requiert…",
        "Épaule, scapula et stabilité du tronc",
        ["Uniquement les mollets", "Seulement les abducteurs de hanche", "Aucun contrôle postural"],
        "Mouvement global du haut du corps.",
      ],
      q2: [
        "Positionner le bras au-dessus de la tête dépend de…",
        "Mobilité et contrôle épaule/thorax",
        ["Uniquement la force des biceps", "La couleur de la barre", "Le type de chaussettes"],
        "Mobilité thoracique et scapulaire clés.",
      ],
      q3: [
        "Sans contrôle scapulaire au overhead press…",
        "Des compensations peuvent apparaître",
        ["Rien ne change", "La gravité disparaît", "Les épaules deviennent inutiles"],
        "Cambrure ou inclinaison compensent parfois.",
      ],
      blank: [
        "Le développé au-dessus de la tête combine mouvement d'épaule et rotation/élévation de la ___.",
        "scapula",
        ["cheville", "mâchoire", "rotule seule"],
        "Omoplate essentielle en poussée verticale.",
      ],
      tf1: [
        "Le tronc participe à la stabilité du développé militaire.",
        true,
        "Vrai : base stable pour pousser la charge.",
      ],
      tf2: [
        "Le développé militaire ne sollicite que le deltoïde sans autre structure.",
        false,
        "Faux : triceps, tronc et scapula participent.",
      ],
      multi: [
        "Quelles structures participent au développé militaire ? (plusieurs réponses)",
        ["Deltoïdes", "Triceps", "Scapula (élévation/rotation)", "Tronc (stabilité)"],
        ["Mollets uniquement", "Ischio-jambiers seuls", "Aucune structure du tronc"],
        "Overhead = mouvement global du haut du corps.",
      ],
      order: [
        "Remets dans l'ordre la montée au développé militaire :",
        [
          "Base stable : tronc gainé, pieds ancrés",
          "Flexion abduction épaule sous contrôle",
          "Rotation/élévation scapulaire en fin de mouvement",
          "Lockout bras au-dessus de la tête",
        ],
        "Épaule + scapula + tronc coordonnés.",
      ],
      match: [
        "Associe composante et rôle overhead :",
        [
          ["Mobilité thoracique", "Permet extension et position bras"],
          ["Scapula", "Rotation vers le haut en fin de mouvement"],
          ["Tronc", "Transmet la force depuis la base"],
        ],
        "Sans mobilité/contrôle, compensations apparaissent.",
      ],
      scenario: [
        "En overhead press, un pratiquant cambrer excessivement le bas du dos pour lockout. Cause biomécanique probable ?",
        "Compensation pour manque de mobilité épaule/thorax ou contrôle scapulaire",
        [
          "Technique optimale recommandée",
          "Les deltoïdes ne fonctionnent qu'en cambrure",
          "La barre devient plus légère en cambrant",
        ],
        "Extension thoracique et scapula nécessaires pour overhead sûr.",
      ],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Les tractions",
    "Tirage : le corps comme charge.",
    [
      `Les **tractions** sont un mouvement de tirage dans lequel le **corps** constitue une grande partie de la charge externe.`,
      `Les muscles du **dos** et des **bras** contribuent à rapprocher le corps de la barre.`,
      `La **prise** (supination, pronation, largeur) et la **trajectoire** modifient la contribution relative des différentes articulations et musculatures.`,
      `À retenir : traction = analyse du tirage + du poids du corps + de la prise.`,
    ],
    ["tractions", "tirage"],
    CP.exercices,
    {
      q1: [
        "En traction, une grande partie de la charge externe est…",
        "Le poids du corps",
        ["Uniquement la barre fixe", "Zéro masse", "Seulement les chaussures"],
        "Tu tires ton corps vers la barre.",
      ],
      q2: [
        "La prise en traction influence…",
        "La contribution relative des muscles et articulations",
        ["Uniquement la couleur de la barre", "La gravité", "Le nom du programme"],
        "Supination vs pronation change le profil.",
      ],
      q3: [
        "Les tractions mobilisent notamment…",
        "Dos et bras",
        ["Uniquement les quadriceps", "Seulement les mollets", "Aucun muscle"],
        "Tirage vertical ou horizontal du corps.",
      ],
      blank: [
        "En traction, l'objectif biomécanique est de rapprocher le ___ de la barre.",
        "corps",
        ["haltère", "banc", "miroir"],
        "Le corps est la masse mobile.",
      ],
      tf1: [
        "Changer la largeur de prise modifie le recrutement relatif.",
        true,
        "Vrai : prise large vs serrée change la géométrie.",
      ],
      tf2: [
        "Toutes les tractions recrutent exactement les mêmes muscles de la même façon.",
        false,
        "Faux : prise et trajectoire modifient le profil.",
      ],
      multi: [
        "Quels paramètres modifient le profil des tractions ? (plusieurs réponses)",
        ["Type de prise (supination/pronation)", "Largeur de prise", "Trajectoire du corps"],
        ["Couleur de la barre", "Marque de magnésie", "Heure de la séance"],
        "Corps = charge externe majeure en traction.",
      ],
      order: [
        "Remets dans l'ordre une traction complète :",
        [
          "Suspension bras tendus (dépression scapulaire)",
          "Initiation du tirage par les omoplates",
          "Flexion coude rapprochant le corps de la barre",
          "Contrôle excentrique à la descente",
        ],
        "Scapula puis bras dans le tirage vertical.",
      ],
      match: [
        "Associe prise et effet relatif :",
        [
          ["Prise supination (chin-up)", "Plus de flexion coude, biceps sollicité"],
          ["Prise pronation (pull-up)", "Plus de travail dorsal relatif"],
          ["Prise large", "Moins d'amplitude coude, plus d'adduction épaule"],
        ],
        "Prise modifie géométrie et recrutement.",
      ],
      scenario: [
        "Un pratiquant fait des tractions prise large et ressent surtout l'échec en bas du dos, pas les bras. Facteur limitant probable ?",
        "Force ou recrutement du grand dorsal / stabilisateurs insuffisant pour la prise choisie",
        [
          "Les tractions ne sollicitent jamais le dos",
          "Prise large supprime le travail des bras",
          "Seuls les mollets limitent les tractions",
        ],
        "Impliqué ≠ limitant : identifier le vrai facteur d'échec.",
      ],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Le rowing",
    "Tirage et stabilisation du tronc.",
    [
      `Le **rowing** combine généralement un mouvement de **tirage** du membre supérieur avec une demande importante de **stabilisation du tronc**.`,
      `Selon la variante (barre, haltère, poulie, T-bar), la **hanche** et la **colonne** peuvent également avoir un rôle important.`,
      `Il faut distinguer le mouvement produit par le **bras** du rôle de stabilisation du **reste du corps**.`,
      `À retenir : rowing = tirage + base stable (tronc, hanche selon variante).`,
    ],
    ["rowing", "tirage"],
    CP.exercices,
    {
      q1: [
        "Le rowing combine surtout…",
        "Tirage du bras et stabilisation du tronc",
        ["Uniquement des sauts", "Seulement de la flexion de cheville", "Aucun travail de dos"],
        "Tirage + base posturale.",
      ],
      q2: [
        "Selon la variante de rowing…",
        "La hanche et la colonne peuvent avoir un rôle variable",
        ["Seul le poignet bouge", "Aucune stabilisation n'est requise", "La barre flotte"],
        "Pendlay vs chest-supported ≠ même exigence.",
      ],
      q3: [
        "Analyser un rowing, c'est distinguer…",
        "Mouvement du bras et stabilisation du reste du corps",
        ["Uniquement le nombre de reps", "La couleur des haltères", "Le BPM"],
        "Deux composantes biomécaniques.",
      ],
      blank: [
        "Le rowing est avant tout un mouvement de ___ horizontal ou incliné.",
        "tirage",
        ["poussée", "saut", "rotation"],
        "Rapprocher la charge vers le torse.",
      ],
      tf1: [
        "Un rowing buste penché demande plus de stabilisation du tronc qu'un rowing assis soutenu.",
        true,
        "Vrai : la base posturale change.",
      ],
      tf2: [
        "En rowing, seul le biceps compte biomécaniquement.",
        false,
        "Faux : dos, épaule et tronc participent.",
      ],
      multi: [
        "Quelles composantes biomécaniques compte le rowing ? (plusieurs réponses)",
        ["Tirage du bras", "Stabilisation du tronc", "Rôle variable de hanche/colonne selon variante"],
        ["Uniquement le poignet", "Aucune stabilisation", "Saut vertical uniquement"],
        "Rowing = tirage + base posturale.",
      ],
      order: [
        "Remets dans l'ordre un rowing barre buste penché :",
        [
          "Position stable : hanche fléchie, tronc rigide",
          "Rétraction scapulaire initiale",
          "Tirage coude vers l'arrière",
          "Contrôle excentrique vers extension",
        ],
        "Base stable avant tirage efficace.",
      ],
      match: [
        "Associe variante et exigence :",
        [
          ["Rowing buste penché", "Fort tronc + hanche"],
          ["Rowing assis soutenu", "Moins de demande posturale"],
          ["Rowing poulie basse", "Tirage horizontal constant"],
        ],
        "Variante = profil de stabilité différent.",
      ],
      scenario: [
        "En rowing haltère unilatéral, le tronc tourne à chaque rep. Quel ajustement biomécanique ?",
        "Renforcer la stabilisation anti-rotation du tronc pendant le tirage",
        [
          "Augmenter la rotation pour plus d'amplitude",
          "Ignorer le tronc, seul le biceps compte",
          "Utiliser une charge plus lourde sans contrôle",
        ],
        "Distinguer mouvement du bras et stabilisation du corps.",
      ],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Le curl biceps",
    "Couple au coude et résistance variable.",
    [
      `Le **curl** semble simple mais constitue un excellent exemple de biomécanique.`,
      `Le biceps produit un **couple** autour du coude. La difficulté dépend fortement de l'**angle du coude** et de la **direction de la résistance**.`,
      `Avec un haltère, la difficulté n'est donc pas identique à tous les endroits du mouvement : gravité + bras de levier variable.`,
      `À retenir : curl = modèle idéal pour visualiser moment et longueur musculaire.`,
    ],
    ["curl", "biceps"],
    CP.exercices,
    {
      q1: [
        "Au curl biceps, l'axe de rotation principal est…",
        "Le coude",
        ["La hanche", "La cheville", "Le genou"],
        "Flexion-extension du coude.",
      ],
      q2: [
        "La difficulté du curl varie car…",
        "L'angle du coude et le bras de levier changent",
        ["La masse de l'haltère change", "La gravité disparaît", "Le biceps s'éteint"],
        "Profil non uniforme dans l'amplitude.",
      ],
      q3: [
        "Le biceps produit au curl…",
        "Un couple de flexion autour du coude",
        ["Une extension de genou", "Une abduction de hanche", "Aucune force"],
        "Agoniste de la flexion du coude.",
      ],
      blank: [
        "Avec un haltère, la résistance reste surtout ___ tout au long du curl.",
        "verticale",
        ["horizontale", "nulle", "latérale fixe"],
        "Gravité domine avec charge libre.",
      ],
      tf1: [
        "Un curl n'est pas également difficile à chaque angle du mouvement.",
        true,
        "Vrai : moment et longueur musculaire varient.",
      ],
      tf2: [
        "La direction de la résistance n'influence pas la difficulté du curl.",
        false,
        "Faux : gravité + géométrie du bras comptent.",
      ],
      multi: [
        "Pourquoi le curl est un bon exemple biomécanique ? (plusieurs réponses)",
        ["Couple autour du coude visible", "Résistance gravitationnelle claire", "Profil de difficulté variable dans l'amplitude"],
        ["Aucune articulation impliquée", "Moment constant partout", "Muscle ne change jamais de longueur"],
        "Modèle pédagogique moment + longueur-tension.",
      ],
      order: [
        "Remets dans l'ordre l'analyse biomécanique du curl :",
        [
          "Identifier l'axe (coude) et le levier (avant-bras)",
          "Déterminer la ligne de résistance (verticale)",
          "Calculer le bras de levier à chaque angle",
          "Relier à la longueur musculaire du biceps",
        ],
        "Curl = visualisation moment + longueur musculaire.",
      ],
      match: [
        "Associe angle du coude et effet au curl haltère :",
        [
          ["90° (milieu)", "Bras de levier maximal, souvent plus dur"],
          ["Coude tendu (bas)", "Levier réduit, muscle allongé"],
          ["Coude fléchi (haut)", "Muscle raccourci"],
        ],
        "Profil non uniforme classique.",
      ],
      scenario: [
        "Tu passes d'un curl haltère à un curl à la poulie basse, même charge ressentie différente. Pourquoi ?",
        "La résistance suit le câble (diagonale) et non la verticale pure de la gravité",
        [
          "Le biceps ne fonctionne qu'avec des haltères",
          "La poulie annule toute tension",
          "La masse change automatiquement",
        ],
        "Direction de résistance modifie le moment au coude.",
      ],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Les extensions de triceps",
    "Position d'épaule et long chef.",
    [
      `Les **extensions de triceps** peuvent être réalisées dans différentes **positions de l'épaule**.`,
      `Cette position influence notamment la longueur du **long chef** du triceps, qui traverse l'épaule et le coude.`,
      `Ainsi, deux extensions de triceps peuvent avoir des profils de résistance et des exigences musculaires différents (overhead vs pushdown).`,
      `À retenir : épaule fléchie vs bras le long du corps = longueur du long chef différente.`,
    ],
    ["triceps", "extension"],
    CP.exercices,
    {
      q1: [
        "Le long chef du triceps traverse…",
        "L'épaule et le coude",
        ["Uniquement le poignet", "La cheville", "Le sternum"],
        "Muscle bi-articulaire du triceps.",
      ],
      q2: [
        "Changer la position de l'épaule en extension de triceps…",
        "Modifie la longueur du long chef",
        ["N'a aucun effet", "Supprime le travail du triceps", "Fixe le coude"],
        "Position épaule = longueur musculaire.",
      ],
      q3: [
        "Overhead extension vs pushdown…",
        "Peuvent avoir des profils de résistance différents",
        ["Sont biomécaniquement identiques", "Ne sollicitent jamais le triceps", "Ignorent le coude"],
        "Géométrie et longueur musculaire diffèrent.",
      ],
      blank: [
        "Le long chef du triceps est un muscle ___ articulaire.",
        "bi",
        ["mono", "tri", "sans"],
        "Épaule + coude = bi-articulaire.",
      ],
      tf1: [
        "La position de l'épaule influence l'étirement du long chef du triceps.",
        true,
        "Vrai : overhead allonge davantage le long chef.",
      ],
      tf2: [
        "Toutes les extensions de triceps ont exactement le même profil musculaire.",
        false,
        "Faux : position épaule et direction de résistance changent le profil.",
      ],
      multi: [
        "Quels facteurs modifient les extensions de triceps ? (plusieurs réponses)",
        ["Position de l'épaule (overhead vs pushdown)", "Longueur du long chef bi-articulaire", "Direction de la résistance"],
        ["Couleur de la corde", "Type de gants", "Heure du repas"],
        "Long chef = sensible à la position d'épaule.",
      ],
      order: [
        "Remets dans l'ordre l'effet de l'épaule sur le long chef :",
        [
          "Identifier les articulations traversées (épaule + coude)",
          "Observer la position de l'épaule (fléchie vs neutre)",
          "Déterminer la longueur du long chef",
          "Prédire le profil de tension",
        ],
        "Overhead allonge davantage le long chef.",
      ],
      match: [
        "Associe variante et effet sur long chef :",
        [
          ["Extension overhead", "Long chef plus allongé"],
          ["Pushdown bras le long", "Long chef moins étiré"],
          ["Long chef", "Traverse épaule et coude"],
        ],
        "Bi-articulaire = position épaule compte.",
      ],
      scenario: [
        "Un pratiquant veut plus d'étirement du long chef du triceps. Quelle variante privilégier biomécaniquement ?",
        "Extension overhead (épaule fléchie, bras derrière la tête ou au-dessus)",
        [
          "Pushdown câble bras le long du corps uniquement",
          "Flexion de coude au curl biceps",
          "Extension de genou au leg extension",
        ],
        "Overhead = allongement maximal du long chef.",
      ],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Les élévations latérales",
    "Bras de levier à l'épaule.",
    [
      `Les **élévations latérales** constituent un excellent exemple de **bras de levier**.`,
      `Lorsque le bras s'éloigne du corps, le **moment externe** au niveau de l'épaule peut augmenter.`,
      `Cela explique pourquoi quelques kilogrammes peuvent devenir extrêmement difficiles lorsque le bras est éloigné du corps, même si la masse reste modeste.`,
      `À retenir : élévation latérale = petit poids, grand levier, grand moment.`,
    ],
    ["elevations", "epaule"],
    CP.exercices,
    {
      q1: [
        "Les élévations latérales comportent surtout…",
        "De l'abduction d'épaule",
        ["De la flexion de hanche", "De l'extension de coude seule", "De la rotation du cou"],
        "Bras qui s'écarte latéralement.",
      ],
      q2: [
        "Quand le bras s'éloigne du corps en élévation latérale…",
        "Le moment externe à l'épaule augmente",
        ["Le moment diminue toujours", "La masse double", "La gravité s'annule"],
        "Bras de levier plus long = plus dur.",
      ],
      q3: [
        "Peu de kilos peuvent sembler très lourds en élévation latérale car…",
        "Le bras de levier est important bras écarté",
        ["Les haltères deviennent plus lourds", "Le deltoïde disparaît", "L'épaule se bloque"],
        "Moment = force × distance.",
      ],
      blank: [
        "En élévation latérale, le moment externe augmente quand le bras de ___ augmente.",
        "levier",
        ["muscle", "temps", "sueur"],
        "Distance perpendiculaire à l'axe d'épaule.",
      ],
      tf1: [
        "Les élévations latérales illustrent bien l'effet du bras de levier.",
        true,
        "Vrai : classique en biomécanique appliquée.",
      ],
      tf2: [
        "En élévation latérale, la difficulté est constante à tous les angles du bras.",
        false,
        "Faux : le moment varie avec l'écartement.",
      ],
      multi: [
        "Pourquoi les élévations latérales illustrent le bras de levier ? (plusieurs réponses)",
        ["Abduction d'épaule", "Moment externe croissant quand le bras s'écarte", "Petit poids peut sembler très lourd"],
        ["Flexion de hanche dominante", "Résistance horizontale uniquement", "Moment constant partout"],
        "Petit poids + grand levier = grand moment.",
      ],
      order: [
        "Remets dans l'ordre l'élévation latérale du bas vers l'horizontale :",
        [
          "Bras le long du corps (levier minimal)",
          "Début d'abduction, moment augmente",
          "Bras à l'horizontale (levier maximal)",
          "Descente contrôlée excentrique",
        ],
        "Moment maximal bras horizontal avec gravité.",
      ],
      match: [
        "Associe position du bras et moment à l'épaule :",
        [
          ["Bras le long du corps", "Moment externe faible"],
          ["Bras à 90° abduction", "Moment externe maximal"],
          ["Haltère 5 kg bras horizontal", "Peut sembler très difficile"],
        ],
        "Classique en biomécanique appliquée.",
      ],
      scenario: [
        "Un pratiquant monte à 12 kg en élévation latérale mais peine avec 6 kg bras à l'horizontale. Explication ?",
        "Le bras de levier à l'épaule double approximativement l'effet du moment malgré la masse réduite",
        [
          "Les haltères de 6 kg sont physiquement plus lourds",
          "Le deltoïde ne fonctionne qu'au-dessus de 10 kg",
          "La gravité disparaît sous 8 kg",
        ],
        "Moment = masse × bras de levier, pas masse seule.",
      ],
    },
    "INTERMEDIATE",
  ),
];
