import type { SeedQuestion } from "./anatomie-quiz-helpers";
import { qcm, tf } from "./anatomie-quiz-helpers";
import { CP } from "./nutrition/checkpoints";
import { gate20 } from "./nutrition/gate-helpers";

export type NutritionGateSeed = {
  checkpointKey: string;
  checkpointOrder: number;
  title: string;
  timeLimitSec: number;
  passThreshold: number;
  questionCount: number;
  xpReward: number;
  questions: SeedQuestion[];
};

export const NUTRITION_GATES: NutritionGateSeed[] = [
  {
    ...CP.macros,
    title: "Checkpoint Macronutriments",
    timeLimitSec: 60,
    passThreshold: 0.9,
    questionCount: 20,
    xpReward: 50,
    questions: gate20(
      qcm(
        "Une calorie (kcal) mesure…",
        "L'énergie apportée par les aliments",
        ["Le poids du muscle", "La quantité d'eau bue", "La vitesse de course"],
        "La kcal = unité d'énergie alimentaire.",
      ),
      qcm(
        "1 g de lipide apporte environ…",
        "9 kcal",
        ["4 kcal", "1 kcal", "0 kcal"],
        "Les lipides sont plus caloriques que protéines et glucides.",
      ),
      qcm(
        "1 g de protéine ou de glucide apporte…",
        "4 kcal",
        ["9 kcal", "7 kcal", "0 kcal"],
        "Protéines et glucides = 4 kcal/g.",
      ),
      tf(
        "Construire et réparer le muscle demande de l'énergie au corps.",
        true,
        "Vrai : la réparation musculaire coûte des calories.",
      ),
      tf(
        "Les calories des boissons (jus, alcool) ne comptent pas dans l'apport énergétique.",
        false,
        "Faux : toutes les calories comptent.",
      ),
      qcm(
        "Les protéines alimentaires sont transformées en…",
        "Acides aminés",
        ["Glucose", "Graisse", "Eau"],
        "La digestion découpe les protéines en acides aminés.",
      ),
      qcm(
        "La digestion d'un repas protéiné dure…",
        "Plusieurs heures",
        ["Quelques secondes", "Exactement 1 minute", "Plusieurs jours"],
        "Les acides aminés arrivent progressivement dans le sang.",
      ),
      tf(
        "Le muscle peut stocker les protéines en réserve pour plus tard.",
        false,
        "Faux : il n'existe pas de réserve protéique dans le corps.",
      ),
      qcm(
        "En musculation, les besoins en protéines tournent souvent autour de…",
        "1,6 à 2,2 g par kg de poids de corps",
        ["0,2 g par kg", "10 g par kg", "0 g par kg"],
        "L'entraînement augmente les besoins protéiques.",
      ),
      qcm(
        "Le glycogène est une réserve de…",
        "Glucose (glucides)",
        ["Protéines", "Graisse", "Eau"],
        "Glycogène = glucose stocké dans muscle et foie.",
      ),
      qcm(
        "Pendant une série lourde, le muscle utilise surtout…",
        "Son propre glycogène",
        ["Les protéines du repas en cours", "Le gras du ventre", "L'eau"],
        "Chaque muscle puise dans sa réserve locale.",
      ),
      tf(
        "Les glucides font grossir automatiquement, quelle que soit la quantité totale de calories.",
        false,
        "Faux : c'est l'excès calorique global qui compte.",
      ),
      qcm(
        "Les glucides lents (avoine, patate) donnent une énergie…",
        "Plus stable sur plusieurs heures",
        ["Instantanée de 5 secondes", "Identique au sucre blanc", "Sans aucun effet"],
        "Index glycémique plus bas = montée plus douce.",
      ),
      qcm(
        "Les lipides servent notamment à…",
        "Fabriquer des hormones et protéger les cellules",
        ["Remplacer les protéines", "Stocker du glycogène", "Produire de l'eau"],
        "Graisses = structure cellulaire + hormones.",
      ),
      qcm(
        "Les vitamines A, D, E et K…",
        "Ont besoin de graisses alimentaires pour être absorbées",
        ["Se trouvent uniquement dans l'eau", "Remplacent les glucides", "Ne servent à rien"],
        "Vitamines liposolubles = absorption avec des lipides.",
      ),
      tf(
        "Supprimer toutes les graisses de l'alimentation est sans conséquence.",
        false,
        "Faux : hormones, cellules et vitamines en dépendent.",
      ),
      qcm(
        "Les oméga-3 (poissons gras, noix) aident surtout à…",
        "Gérer l'inflammation après l'entraînement",
        ["Remplacer les protéines", "Stocker le glycogène", "Produire de l'insuline seule"],
        "Oméga-3 = intérêt anti-inflammatoire.",
      ),
      tf(
        "Sans glucides suffisants, la performance à l'entraînement baisse.",
        true,
        "Vrai : moins de glycogène = moins d'énergie pour les séries.",
      ),
      tf(
        "L'excédent de protéines est stocké comme réserve musculaire directe.",
        false,
        "Faux : pas de stock protéique ; l'excédent est utilisé ou éliminé.",
      ),
      qcm(
        "Parmi les macronutriments, le plus dense en calories est…",
        "Les lipides",
        ["Les protéines", "Les glucides", "L'eau"],
        "9 kcal/g pour les lipides vs 4 kcal/g pour protéines et glucides.",
      ),
    ),
  },
  {
    ...CP.micronutriments,
    title: "Checkpoint Micronutriments",
    timeLimitSec: 60,
    passThreshold: 0.9,
    questionCount: 20,
    xpReward: 50,
    questions: gate20(
      qcm(
        "1 g de lipide apporte combien de kcal ?",
        "9 kcal",
        ["4 kcal", "1 kcal", "0 kcal"],
        "Rappel macronutriments : lipides = plus caloriques.",
      ),
      tf(
        "Le corps dépense de l'énergie même au repos (respiration, circulation).",
        true,
        "Rappel : la dépense énergétique est permanente.",
      ),
      qcm(
        "Le glycogène se stocke surtout dans…",
        "Le muscle et le foie",
        ["Les cheveux", "Les os seuls", "La peau"],
        "Rappel glucides : réserve d'énergie rapide.",
      ),
      tf(
        "L'entraînement augmente les besoins en protéines.",
        true,
        "Rappel protéines : fibres abîmées à réparer.",
      ),
      qcm(
        "Les lipides ralentissent aussi…",
        "La digestion et prolongent la satiété",
        ["La croissance osseuse seule", "La respiration", "Le sommeil profond"],
        "Rappel lipides : effet sur vidange gastrique.",
      ),
      tf(
        "Les vitamines sont des nutriments nécessaires en petites quantités.",
        true,
        "Micronutriments = besoins faibles mais essentiels.",
      ),
      qcm(
        "Les vitamines A, D, E et K sont…",
        "Liposolubles",
        ["Hydrosolubles", "Des protéines", "Des glucides"],
        "Elles s'absorbent avec des graisses alimentaires.",
      ),
      qcm(
        "La vitamine D aide surtout à…",
        "Fixer le calcium sur les os",
        ["Produire du glycogène", "Remplacer les protéines", "Stocker l'eau"],
        "Vitamine D + calcium = santé osseuse sous charge.",
      ),
      qcm(
        "Les vitamines B participent surtout à…",
        "La production d'énergie à partir des aliments",
        ["Le stockage du gras seul", "La digestion des os", "La croissance des cheveux seule"],
        "Cofacteurs du métabolisme énergétique.",
      ),
      tf(
        "Le corps fabrique toutes les vitamines dont il a besoin.",
        false,
        "Faux : la plupart doivent venir de l'alimentation ou du soleil (D).",
      ),
      qcm(
        "Le calcium sert surtout à…",
        "Structurer les os et aider la contraction musculaire",
        ["Produire du glucose", "Remplacer les lipides", "Stocker les protéines"],
        "Os solides + contraction = base de la force.",
      ),
      qcm(
        "Le magnésium intervient notamment dans…",
        "La production d'énergie et la relaxation musculaire",
        ["La digestion des fibres seules", "Le stockage du gras uniquement", "La croissance des cheveux"],
        "Cofacteur clé pour muscles et métabolisme.",
      ),
      qcm(
        "En transpirant à la salle, on perd surtout…",
        "De l'eau et du sodium",
        ["Uniquement des protéines", "Uniquement des vitamines", "Rien du tout"],
        "Sueur = eau + sels minéraux.",
      ),
      qcm(
        "Le fer sert surtout à…",
        "Transporter l'oxygène dans le sang",
        ["Stocker le glycogène", "Fabriquer les os", "Produire de l'eau"],
        "Fer = hémoglobine = oxygène vers les muscles.",
      ),
      qcm(
        "Le zinc intervient notamment dans…",
        "La réparation des tissus et l'immunité",
        ["La digestion des lipides seule", "Le stockage du calcium", "La production de sueur"],
        "Zinc = réparation + défenses immunitaires.",
      ),
      tf(
        "Une carence en fer peut réduire l'endurance à l'entraînement.",
        true,
        "Vrai : moins d'oxygène transporté = fatigue plus rapide.",
      ),
      qcm(
        "L'eau sert notamment à…",
        "Transporter les nutriments et réguler la température",
        ["Remplacer les protéines", "Produire du muscle directement", "Stocker le glycogène"],
        "Eau = transport, thermorégulation, élimination.",
      ),
      qcm(
        "Un bon indicateur d'hydratation en journée est…",
        "Une urine claire",
        ["Une urine très foncée en permanence", "Ne jamais avoir soif", "Boire uniquement du soda"],
        "Couleur de l'urine = repère simple et accessible.",
      ),
      tf(
        "La déshydratation peut réduire la performance à l'entraînement.",
        true,
        "Vrai : moins de fluides = moins de force et de concentration.",
      ),
      tf(
        "Plus on prend d'oligo-éléments en supplément, mieux c'est pour la performance.",
        false,
        "Faux : l'excès peut être toxique ; l'alimentation variée suffit souvent.",
      ),
    ),
  },
  {
    ...CP.equilibre,
    title: "Checkpoint Alimentation équilibrée",
    timeLimitSec: 60,
    passThreshold: 0.9,
    questionCount: 20,
    xpReward: 50,
    questions: gate20(
      qcm(
        "Fruits et légumes apportent surtout…",
        "Vitamines, minéraux et fibres",
        ["Uniquement des protéines", "Uniquement du gras", "Aucun nutriment utile"],
        "Complément micronutriment + fibres.",
      ),
      qcm(
        "Manger plusieurs couleurs de légumes permet…",
        "D'augmenter la diversité des micronutriments",
        ["De supprimer le besoin de protéines", "De ne plus boire d'eau", "De remplacer l'entraînement"],
        "Chaque couleur = profil nutritionnel différent.",
      ),
      tf(
        "Les fruits et légumes remplacent totalement les protéines animales.",
        false,
        "Faux : ils complètent l'assiette, ils ne remplacent pas les protéines.",
      ),
      qcm(
        "Les féculents apportent surtout…",
        "Des glucides complexes",
        ["Des protéines pures", "Des lipides uniquement", "De l'eau seule"],
        "Pain, riz, pâtes = source majeure de glucides.",
      ),
      qcm(
        "Les féculents complets par rapport aux raffinés…",
        "Contiennent plus de fibres et montent la glycémie plus lentement",
        ["N'ont aucun glucide", "Sont toujours sans calories", "Remplacent les protéines"],
        "Complet = fibres + énergie plus stable.",
      ),
      tf(
        "Un féculent isolé ne fait pas grossir : c'est l'excès calorique global qui compte.",
        true,
        "Vrai : pas d'aliment « coupable » seul.",
      ),
      qcm(
        "Des exemples de protéines végétales sont…",
        "Lentilles, tofu et tempeh",
        ["Beurre et crème seuls", "Sucre blanc", "Jus de pomme"],
        "Légumineuses et soy = protéines végétales.",
      ),
      qcm(
        "En musculation, pour les protéines, ce qui compte d'abord c'est…",
        "L'apport total sur la journée",
        ["Une seule source obligatoire", "Ne manger que le soir", "Supprimer les végétaux"],
        "Total journalier > source unique.",
      ),
      tf(
        "Les protéines végétales peuvent suffire à un sportif avec une alimentation variée.",
        true,
        "Vrai : combinaisons et diversité couvrent les besoins.",
      ),
      qcm(
        "Des sources de bonnes graisses alimentaires sont…",
        "Huile d'olive, noix et poissons gras",
        ["Sucre blanc et soda", "Eau gazeuse seule", "Pain blanc sec"],
        "Insaturées + oméga-3 = sources de qualité.",
      ),
      qcm(
        "En musculation, un apport lipidique trop bas peut…",
        "Nuire aux hormones et à la récupération",
        ["Doubler le muscle automatiquement", "Remplacer les protéines", "Supprimer le besoin de sommeil"],
        "Lipides = hormones + cellules + vitamines.",
      ),
      qcm(
        "Les produits laitiers apportent surtout…",
        "Calcium et protéines",
        ["Uniquement du sucre", "Uniquement des lipides", "Aucun nutriment"],
        "Laitiers = calcium + protéines pratiques.",
      ),
      tf(
        "Les laitiers sont la seule source de calcium possible.",
        false,
        "Faux : légumes verts, tofu, sardines et alternatives enrichies en apportent aussi.",
      ),
      qcm(
        "Les fibres alimentaires se trouvent surtout dans…",
        "Légumes, fruits et céréales complètes",
        ["Huile pure", "Eau", "Viande seule"],
        "Végétaux = source principale de fibres.",
      ),
      tf(
        "Augmenter les fibres d'un coup en grande quantité peut causer des ballonnements.",
        true,
        "Vrai : progression douce + eau = meilleure tolérance.",
      ),
      qcm(
        "Une bonne hydratation au quotidien, c'est…",
        "Boire régulièrement sur toute la journée",
        ["Boire uniquement à la salle", "Ne boire que quand on a très soif", "Remplacer l'eau par du soda"],
        "Hydratation = habitude continue.",
      ),
      qcm(
        "Un repas équilibré type combine…",
        "Protéines, féculents, légumes et lipides de qualité",
        ["Uniquement de la viande", "Uniquement du pain", "Uniquement de l'eau"],
        "Structure = macros + légumes + eau.",
      ),
      qcm(
        "Le modèle « demi-assiette légumes » signifie…",
        "Environ la moitié de l'assiette en légumes",
        ["Aucun légume", "Uniquement de la viande", "Supprimer les féculents"],
        "Repère visuel simple pour équilibrer.",
      ),
      tf(
        "Une journée équilibrée inclut de l'eau répartie sur la journée.",
        true,
        "Vrai : hydratation = partie intégrante du quotidien.",
      ),
      tf(
        "Un repas équilibré exclut totalement les féculents.",
        false,
        "Faux : féculents = part importante du carburant musculaire.",
      ),
    ),
  },
  {
    ...CP.energie,
    title: "Checkpoint Besoins énergétiques",
    timeLimitSec: 60,
    passThreshold: 0.9,
    questionCount: 20,
    xpReward: 50,
    questions: gate20(
      qcm(
        "Le métabolisme basal correspond à…",
        "L'énergie brûlée au repos total",
        ["L'énergie brûlée uniquement en courant", "Les calories des boissons", "Le poids du muscle"],
        "MB = dépense au repos, sans activité.",
      ),
      qcm(
        "Le métabolisme basal est influencé notamment par…",
        "La masse musculaire",
        ["La couleur des chaussures", "La marque de complément", "L'heure du coucher seule"],
        "Plus de muscle = MB un peu plus élevé.",
      ),
      tf(
        "Gagner du muscle peut légèrement augmenter le métabolisme basal.",
        true,
        "Vrai : le muscle coûte plus cher en énergie au repos que le gras.",
      ),
      qcm(
        "La dépense énergétique totale comprend…",
        "Métabolisme basal, activité et thermogenèse alimentaire",
        ["Uniquement le sport", "Uniquement le sommeil", "Uniquement les protéines"],
        "DET = MB + activité + digestion.",
      ),
      qcm(
        "La plus grosse part de la DET chez la plupart des gens est…",
        "Le métabolisme basal",
        ["La marche seule", "La thermogenèse alimentaire", "Les étirements"],
        "MB = 60-75 % en général.",
      ),
      qcm(
        "La NEAT désigne…",
        "L'activité non sportive du quotidien",
        ["Uniquement la musculation", "Le sommeil profond", "La digestion seule"],
        "NEAT = marche, escaliers, gestes du quotidien.",
      ),
      tf(
        "Bouger plus au quotidien augmente la dépense énergétique totale.",
        true,
        "Vrai : NEAT + sport = activité dans la DET.",
      ),
      qcm(
        "La thermogenèse alimentaire, c'est…",
        "L'énergie dépensée pour digérer les aliments",
        ["L'énergie du sport uniquement", "Le stockage du gras seul", "La respiration nocturne"],
        "TEF = coût énergétique de la digestion.",
      ),
      qcm(
        "Le macronutriment qui coûte le plus à digérer est…",
        "Les protéines",
        ["Les lipides", "L'eau", "Les vitamines"],
        "Protéines = ~20-30 % de TEF.",
      ),
      qcm(
        "Les besoins caloriques correspondent à…",
        "La dépense énergétique totale moyenne",
        ["Uniquement le métabolisme basal", "Le poids du gras seul", "Les calories des boissons"],
        "Besoins ≈ ce que le corps dépense.",
      ),
      qcm(
        "Pour estimer la DET, on multiplie souvent le MB par…",
        "Un facteur d'activité",
        ["Zéro", "Le nombre de séances au hasard", "L'âge seul"],
        "MB × facteur activité = estimation DET.",
      ),
      qcm(
        "La balance énergétique compare…",
        "Les calories consommées aux calories dépensées",
        ["Les protéines aux lipides", "Le sommeil au sport", "L'eau aux vitamines"],
        "Entrées vs sorties = balance.",
      ),
      tf(
        "La balance énergétique s'interprète mieux sur plusieurs semaines qu'en un jour.",
        true,
        "Vrai : moyenne lissée > pesée isolée.",
      ),
      qcm(
        "En surplus calorique, l'excédent sert notamment à…",
        "Construire du muscle (si on s'entraîne)",
        ["Supprimer le gras", "Remplacer le sommeil", "Bloquer la digestion"],
        "Énergie en plus = possibilité de construire du tissu maigre.",
      ),
      qcm(
        "En déficit trop fort, le corps peut perdre…",
        "Du gras et du muscle",
        ["Uniquement de l'eau", "Rien du tout", "Uniquement des vitamines"],
        "Déficit agressif + peu de protéines = risque musculaire.",
      ),
      qcm(
        "La recomposition est surtout possible chez…",
        "Les débutants ou après une longue pause",
        ["Les champions expérimentés", "Ceux qui ne s'entraînent pas", "Tout le monde également"],
        "Stimulus nouveau = gains plus faciles simultanés.",
      ),
      tf(
        "100 % des calories en surplus deviennent du muscle.",
        false,
        "Faux : une partie est stockée en gras.",
      ),
      tf(
        "L'entraînement lourd aide à préserver le muscle en déficit.",
        true,
        "Vrai : signal au corps de garder les fibres sollicitées.",
      ),
      tf(
        "En déficit prolongé, le corps réduit un peu sa dépense pour s'adapter.",
        true,
        "Vrai : adaptation métabolique = cause fréquente de plateau en sèche.",
      ),
      qcm(
        "En maintien calorique, le poids tend à…",
        "Rester stable",
        ["Baisser rapidement", "Augmenter chaque semaine", "Disparaître"],
        "Entrées ≈ sorties = poids stable.",
      ),
    ),
  },
  {
    ...CP.digestion,
    title: "Checkpoint Digestion",
    timeLimitSec: 60,
    passThreshold: 0.9,
    questionCount: 20,
    xpReward: 50,
    questions: gate20(
      qcm(
        "La digestion commence dans…",
        "La bouche",
        ["L'estomac seulement", "Le foie", "Les muscles"],
        "Mastication et salive = première étape.",
      ),
      qcm(
        "Un repas mixte reste en moyenne dans l'estomac…",
        "2 à 4 heures",
        ["Quelques secondes", "12 heures", "Plusieurs jours"],
        "Vidange gastrique progressive selon la composition du repas.",
      ),
      qcm(
        "Les lipides dans un repas…",
        "Ralentissent la vidange de l'estomac",
        ["Accélèrent toujours la digestion", "Empêchent toute absorption", "Remplacent les protéines"],
        "Repas gras = digestion plus lente et satiété prolongée.",
      ),
      tf(
        "Les nutriments d'un repas arrivent tous instantanément dans le sang.",
        false,
        "Faux : la digestion dure plusieurs heures, par vagues.",
      ),
      qcm(
        "L'absorption des nutriments se fait surtout dans…",
        "L'intestin grêle",
        ["La bouche", "L'estomac seul", "Les poumons"],
        "Paroi intestinale = zone principale d'absorption.",
      ),
      qcm(
        "Les lipides alimentaires passent d'abord surtout dans…",
        "La lymphe",
        ["L'air", "Les os directement", "La bile seule"],
        "Chylomicrons → lymphe → sang.",
      ),
      qcm(
        "La glycémie mesure…",
        "La concentration de glucose dans le sang",
        ["Le poids du muscle", "La quantité de protéines", "Le niveau de fer"],
        "Glycémie = sucre sanguin.",
      ),
      qcm(
        "Les glucides rapides (sucre blanc, jus)…",
        "Font monter la glycémie plus vite",
        ["Ne changent pas la glycémie", "La font toujours baisser", "Remplacent les protéines"],
        "Absorption rapide = pic glycémique plus marqué.",
      ),
      qcm(
        "L'insuline est produite par…",
        "Le pancréas",
        ["Le foie", "Le muscle", "L'estomac"],
        "Îlots de Langerhans du pancréas = source d'insuline.",
      ),
      qcm(
        "Dans le muscle, l'insuline aide à faire entrer…",
        "Le glucose et les acides aminés",
        ["Uniquement le gras", "L'eau seule", "Les vitamines seules"],
        "Double rôle : énergie + matériaux pour la réparation.",
      ),
      tf(
        "L'insuline sert uniquement à stocker du gras, jamais à aider le muscle.",
        false,
        "Faux : elle aide aussi le glucose et les acides aminés à entrer dans le muscle.",
      ),
      qcm(
        "Les réserves de glycogène sont…",
        "Limitées",
        ["Illimitées", "Uniquement dans le gras", "Absentes chez l'humain"],
        "Capacité finie : l'excédent devient gras.",
      ),
      qcm(
        "Le foie stocke du glycogène surtout pour…",
        "Stabiliser la glycémie entre les repas",
        ["Contrôler la respiration", "Produire des muscles", "Digérer les fibres"],
        "Libération de glucose quand tu es à jeun.",
      ),
      qcm(
        "Pendant l'effort, le muscle utilise surtout…",
        "Son propre glycogène",
        ["Le glycogène du foie directement", "Les protéines du repas en cours", "L'alcool"],
        "Réserve locale = carburant des séries.",
      ),
      tf(
        "Le muscle peut donner son glycogène directement à un autre organe pendant l'effort.",
        false,
        "Faux : le glycogène musculaire est utilisé localement.",
      ),
      tf(
        "L'entraînement régulier améliore la sensibilité à l'insuline.",
        true,
        "Vrai : meilleure sensibilité = moins d'insuline nécessaire.",
      ),
      qcm(
        "L'alcool est traité par le foie…",
        "En priorité",
        ["Après tout le gras seulement", "Jamais", "Par les muscles"],
        "Le foie privilégie l'alcool, ce qui retarde d'autres traitements.",
      ),
      tf(
        "En déficit calorique, le corps peut puiser dans les réserves de gras.",
        true,
        "Vrai : mobilisation progressive des triglycérides.",
      ),
      qcm(
        "Les protéines et glucides sont surtout absorbés dans…",
        "L'intestin grêle",
        ["La bouche", "Les poumons", "Les muscles directement"],
        "Paroi intestinale = zone d'absorption principale.",
      ),
      tf(
        "Manger trop vite peut provoquer des ballonnements.",
        true,
        "Vrai : mastication insuffisante = digestion plus difficile.",
      ),
    ),
  },
  {
    ...CP.fibres,
    title: "Checkpoint Fibres",
    timeLimitSec: 60,
    passThreshold: 0.9,
    questionCount: 20,
    xpReward: 50,
    questions: gate20(
      qcm(
        "Les fibres solubles…",
        "Forment un gel dans l'intestin",
        ["Passent sans effet", "Sont digérées comme des protéines", "Remplacent les glucides"],
        "Gel = ralentit sucre et gras.",
      ),
      qcm(
        "Les fibres insolubles aident surtout…",
        "Le transit intestinal",
        ["La production de testostérone", "Le stockage de glycogène", "La respiration"],
        "Volume des selles + absorption d'eau.",
      ),
      qcm(
        "Les fibres solubles se trouvent par exemple dans…",
        "L'avoine et les légumineuses",
        ["Sucre blanc", "Beurre", "Eau minérale"],
        "Solubles = avoine, pommes, lentilles…",
      ),
      tf(
        "Le corps humain digère complètement les fibres alimentaires.",
        false,
        "Faux : elles traversent l'intestin largement intactes.",
      ),
      qcm(
        "La satiété dépend notamment de…",
        "La composition et le volume du repas",
        ["La couleur de l'assiette", "L'heure exacte du coucher", "La marque de complément"],
        "Fibres, protéines, lipides et volume influencent la durée de satiété.",
      ),
      qcm(
        "Le signal « assez mangé » met environ…",
        "15 à 20 minutes",
        ["1 seconde", "3 heures", "24 heures"],
        "Manger lentement laisse le temps au cerveau de réagir.",
      ),
      tf(
        "Un repas volumineux en légumes peut aider la satiété avec peu de calories.",
        true,
        "Vrai : volume sans densité calorique élevée.",
      ),
      qcm(
        "Pour faciliter le transit, il faut surtout…",
        "Fibres et eau suffisante",
        ["Supprimer tous les légumes", "Boire uniquement du jus", "Ne plus manger de protéines"],
        "Volume + hydratation = selles plus souples.",
      ),
      qcm(
        "L'activité physique…",
        "Stimule le transit intestinal",
        ["L'arrête complètement", "Remplace les fibres", "Supprime la digestion"],
        "Mouvement = intestin plus actif.",
      ),
      tf(
        "Il vaut mieux augmenter les fibres progressivement.",
        true,
        "Vrai : adaptation intestinale sur quelques jours.",
      ),
      qcm(
        "Le microbiote intestinal est surtout composé de…",
        "Bactéries bénéfiques",
        ["Muscles", "Os", "Graisse pure"],
        "Écosystème microbien dans le côlon.",
      ),
      qcm(
        "Les prébiotiques sont…",
        "Des fibres qui nourrissent les bonnes bactéries",
        ["Des antibiotiques", "Des protéines animales", "Du sel"],
        "Fibres = carburant du microbiote.",
      ),
      tf(
        "Une alimentation variée en légumes et fibres soutient le microbiote.",
        true,
        "Vrai : diversité alimentaire = diversité microbienne.",
      ),
      qcm(
        "La fermentation des fibres produit surtout…",
        "Des acides gras à chaîne courte (AGCC)",
        ["Du glucose pur", "Des protéines musculaires", "De l'alcool"],
        "AGCC = carburant des cellules intestinales.",
      ),
      qcm(
        "Des ballonnements après légumineuses peuvent venir de…",
        "La fermentation intestinale",
        ["Un manque total de fibres", "Trop de protéines seules", "L'absence d'eau dans le corps"],
        "Fermentation = gaz, normal en quantité modérée.",
      ),
      tf(
        "La fermentation intestinale est toujours nocive.",
        false,
        "Faux : elle produit des composés bénéfiques (AGCC).",
      ),
      qcm(
        "Les piliers d'une bonne santé digestive incluent…",
        "Variété alimentaire, eau et activité physique",
        ["Zéro légume", "Repas uniquement liquides", "Supprimer toutes les fibres"],
        "Base lifestyle + alimentation.",
      ),
      tf(
        "Un intestin confortable favorise une meilleure absorption des nutriments.",
        true,
        "Vrai : paroi saine + transit régulier = absorption optimale.",
      ),
      qcm(
        "Les fibres insolubles se trouvent surtout dans…",
        "Les légumes et céréales complètes",
        ["Le sucre blanc", "L'huile d'olive", "Les sodas"],
        "Peau de légumes, blé complet, son.",
      ),
      tf(
        "Boire peu d'eau peut aggraver la constipation.",
        true,
        "Vrai : fibres + eau = selles plus souples.",
      ),
    ),
  },
  {
    ...CP.etiquettes,
    title: "Checkpoint Étiquettes",
    timeLimitSec: 60,
    passThreshold: 0.9,
    questionCount: 20,
    xpReward: 50,
    questions: gate20(
      qcm(
        "L'étiquette nutritionnelle indique souvent les valeurs pour…",
        "100 g ou 100 ml et parfois par portion",
        ["Uniquement par bouchée", "Par heure", "Par année"],
        "Comparer à 100 g = référence standard.",
      ),
      qcm(
        "Avant de juger un produit « léger », il faut vérifier…",
        "La taille de la portion réelle",
        ["La couleur du packaging", "La date de péremption seule", "Le prix"],
        "Portion réelle vs portion indiquée.",
      ),
      tf(
        "Les chiffres pour 100 g correspondent toujours à ce que tu manges en une fois.",
        false,
        "Faux : ta portion peut être plus grande ou plus petite.",
      ),
      qcm(
        "Dans la liste des ingrédients, le premier est…",
        "Le plus présent en quantité",
        ["Le moins présent", "Un additif obligatoire", "Toujours de l'eau"],
        "Ordre décroissant = plus gros composant en tête.",
      ),
      qcm(
        "Un produit « aux fruits » avec le sucre en premier contient surtout…",
        "Du sucre",
        ["Du fruit frais", "Des protéines", "Des fibres seules"],
        "Ordre de la liste = vérité sur la composition.",
      ),
      tf(
        "« Light » ou « 0 % matière grasse » garantit toujours un produit sain.",
        false,
        "Faux : le produit peut être riche en sucre ou en sel.",
      ),
      qcm(
        "La densité énergétique mesure…",
        "Les calories pour un volume ou poids donné",
        ["La couleur de l'aliment", "Le temps de cuisson", "La quantité d'eau bue"],
        "Plus dense = plus de kcal pour la même quantité.",
      ),
      qcm(
        "En période de déficit, il est utile de privilégier…",
        "Des aliments peu denses (légumes, fruits)",
        ["Uniquement les huiles", "Les boissons sucrées", "L'alcool"],
        "Volume sans excès calorique = satiété.",
      ),
      tf(
        "En prise de masse, les aliments denses aident à atteindre les calories.",
        true,
        "Vrai : oléagineux, avoine, huiles = calories concentrées.",
      ),
      qcm(
        "Si tu doubles la quantité de céréales, tu doubles aussi…",
        "Les calories et sucres",
        ["Uniquement la couleur", "La date de péremption", "Les vitamines automatiquement"],
        "Proportionnel à la quantité consommée.",
      ),
      qcm(
        "Les sucres ajoutés sont…",
        "Incorporés lors de la fabrication",
        ["Uniquement dans les fruits entiers", "Absents des produits industriels", "Identiques à l'eau"],
        "Distincts des sucres naturels du fruit non transformé.",
      ),
      qcm(
        "Sur l'étiquette, « dont sucres » inclut…",
        "Sucres naturels et ajoutés",
        ["Uniquement le sel", "Uniquement les lipides", "Rien du tout"],
        "Pour distinguer, lire la liste des ingrédients.",
      ),
      qcm(
        "Les principales sources de sel en excès sont…",
        "Produits transformés (charcuterie, plats préparés)",
        ["Fruits frais", "Eau pure", "Légumes non salés"],
        "Sel ajouté en industrie.",
      ),
      qcm(
        "Les oméga-3 se trouvent surtout dans…",
        "Poissons gras, lin, noix",
        ["Sucre blanc", "Pain blanc", "Sodas"],
        "EPA/DHA dans poissons gras.",
      ),
      tf(
        "Les graisses trans sont à éviter autant que possible.",
        true,
        "Vrai : huiles hydrogénées = nocives.",
      ),
      qcm(
        "Une barre « protéinée » peut…",
        "Contenir autant de sucre qu'une barre classique",
        ["Ne jamais contenir de sucre", "Remplacer un repas complet seul", "Augmenter le muscle sans entraînement"],
        "Mention protéine ≠ produit sain automatiquement.",
      ),
      tf(
        "Un produit « sport » ou « fitness » est toujours adapté à la musculation.",
        false,
        "Faux : vérifier sucres, sel et macros réels.",
      ),
      qcm(
        "Pour juger un produit, il vaut mieux lire…",
        "Ingrédients et tableau nutritionnel (dos du paquet)",
        ["Uniquement le Nutri-Score", "La couleur du logo", "Le prix seul"],
        "Arrière du paquet = information fiable.",
      ),
      qcm(
        "Les graisses saturées se trouvent surtout dans…",
        "Charcuterie, beurre, fromages gras",
        ["Fruits frais", "Légumes verts", "Eau"],
        "Produits animaux gras = saturées.",
      ),
      tf(
        "Comparer les étiquettes à 100 g aide à choisir entre deux produits.",
        true,
        "Vrai : même référence = comparaison juste.",
      ),
    ),
  },
  {
    ...CP.objectifs,
    title: "Checkpoint Objectifs",
    timeLimitSec: 60,
    passThreshold: 0.9,
    questionCount: 20,
    xpReward: 50,
    questions: gate20(
      qcm(
        "Perdre du poids repose surtout sur…",
        "Un déficit calorique",
        ["Supprimer toutes les protéines", "Ne plus s'entraîner", "Boire uniquement du jus"],
        "Moins d'entrées que de sorties = perte de masse.",
      ),
      qcm(
        "Sans protéines suffisantes en déficit, on risque de perdre…",
        "Du muscle en plus du gras",
        ["Uniquement de l'eau", "Rien du tout", "Uniquement des vitamines"],
        "Acides aminés = préservation musculaire.",
      ),
      qcm(
        "Un déficit calorique modéré recommandé tourne souvent autour de…",
        "10 à 20 %",
        ["80 à 90 %", "0 % toujours", "100 %"],
        "Déficit agressif = fatigue et plateau.",
      ),
      tf(
        "Les fibres et légumes aident à gérer la faim en déficit.",
        true,
        "Vrai : volume sans excès calorique.",
      ),
      qcm(
        "La prise de masse nécessite…",
        "Surplus calorique + protéines + entraînement",
        ["Uniquement des compléments", "Zéro glucide", "Arrêter l'entraînement"],
        "Trois piliers : stimulus, briques, énergie.",
      ),
      qcm(
        "Un surplus modéré recommandé tourne souvent autour de…",
        "200 à 500 kcal/jour",
        ["2000 à 3000 kcal de surplus", "0 kcal", "50 kcal seulement"],
        "Au-delà = surtout du gras.",
      ),
      tf(
        "Plus de calories signifie toujours plus de muscle, sans limite.",
        false,
        "Faux : le corps a un plafond de construction.",
      ),
      qcm(
        "Pendant une séance de musculation classique, le muscle utilise surtout…",
        "Son glycogène stocké",
        ["Le repas en cours de digestion", "Uniquement le gras", "Les vitamines"],
        "Réserve locale = carburant des séries.",
      ),
      qcm(
        "Avant une séance lourde, un repas idéal est pris…",
        "1 à 3 heures avant",
        ["30 secondes avant", "Pendant la séance", "12 heures après"],
        "Temps de digestion suffisant.",
      ),
      tf(
        "Il faut manger dans les 5 minutes après la séance sinon les gains disparaissent.",
        false,
        "Faux : la fenêtre post-effort dure plusieurs heures.",
      ),
      qcm(
        "Un régime favorable au cœur privilégie…",
        "Fruits, légumes, légumineuses, poissons gras",
        ["Charcuterie quotidienne", "Sodas à chaque repas", "Fritures en excès"],
        "Schéma méditerranéen bien documenté.",
      ),
      qcm(
        "Pour ralentir la montée glycémique, on associe glucides à…",
        "Fibres, protéines et lipides",
        ["Uniquement du sucre", "De l'alcool", "Rien du tout"],
        "Repas mixte = absorption progressive.",
      ),
      qcm(
        "La sarcopénie désigne…",
        "La perte progressive de muscle avec l'âge",
        ["La croissance osseuse", "L'augmentation du gras seule", "La digestion rapide"],
        "Sans entraînement + protéines = déclin musculaire.",
      ),
      tf(
        "Il est trop tard pour préserver le muscle après 40 ans.",
        false,
        "Faux : entraînement + protéines aident à tout âge.",
      ),
      qcm(
        "En alimentation végétalienne, le nutriment souvent supplémenté est…",
        "La vitamine B12",
        ["Le sodium", "L'alcool", "Le sucre"],
        "Absente des végétaux purs.",
      ),
      qcm(
        "Pour couvrir les protéines végétales, on combine souvent…",
        "Légumineuses et céréales",
        ["Uniquement du sucre", "Eau seule", "Sel seul"],
        "Complémentarité des acides aminés sur la journée.",
      ),
      tf(
        "On ne peut pas faire de musculation sans manger de viande.",
        false,
        "Faux : alimentation végétarienne bien planifiée suffit.",
      ),
      tf(
        "Le total nutritionnel de la journée compte plus que le timing exact.",
        true,
        "Vrai : base solide > perfection horaire.",
      ),
      qcm(
        "En sèche, l'entraînement lourd sert surtout à…",
        "Préserver le muscle",
        ["Supprimer toute faim", "Remplacer les protéines", "Éliminer le gras en une séance"],
        "Signal au corps de garder les fibres sollicitées.",
      ),
      tf(
        "Une alimentation variée couvre la plupart des micronutriments sans compléments.",
        true,
        "Vrai : diversité alimentaire = base solide pour la plupart.",
      ),
    ),
  },
];
