import { CP } from "./checkpoints";
import { buildLesson } from "./build-lesson";

export const THEME_6_LESSONS = [
  buildLesson(
    "Full Body",
    "2–4 séances, volume distribué.",
    [
      `Le **full body** est particulièrement intéressant avec **2–4 séances**. Exemple : lundi / mercredi / vendredi.`,
      `Chaque séance contient : jambes, poussée, tirage, accessoires. Le volume hebdomadaire est **distribué régulièrement**.`,
      `Idéal pour débutants, agendas chargés ou fréquence élevée par muscle avec peu de jours.`,
      `À retenir : full body = tout le corps chaque séance, volume réparti.`,
    ],
    ["full-body", "split"],
    CP.splits,
    {
      q1: ["Le full body convient souvent avec…", "2 à 4 séances par semaine", ["1 séance par mois", "10 séances par jour", "0 séance"], "Fréquence modérée."],
      q2: ["Chaque séance full body contient typiquement…", "Jambes, poussée, tirage et accessoires", ["Uniquement les biceps", "Seulement le cardio", "Rien"], "Couverture globale."],
      q3: ["Le full body distribue le volume…", "Régulièrement sur la semaine", ["Sur un seul jour", "Sans jambes", "Sans tirage"], "Stimulus fréquent."],
      blank: ["En full body, on entraîne tout le ___ à chaque séance.", "corps", ["mollet seul", "cou seul", "poignet seul"], "Definition du split."],
      tf1: ["Le full body peut convenir aux débutants.", true, "Vrai : fréquence et simplicité."],
      tf2: ["Le full body ne permet jamais de progresser.", false, "Faux : efficace selon contexte."],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Upper / Lower",
    "4 jours : haut / bas alternés.",
    [
      `Exemple **Upper/Lower** :\n\n- Lundi : Upper\n- Mardi : Lower\n- Jeudi : Upper\n- Vendredi : Lower`,
      `Cette structure permet de distribuer un volume relativement important sans multiplier excessivement les séances.`,
      `Bon compromis volume/fréquence pour intermédiaires.`,
      `À retenir : 4 jours, alternance haut/bas du corps.`,
    ],
    ["upper-lower", "split"],
    CP.splits,
    {
      q1: ["Un split Upper/Lower typique sur 4 jours…", "Alterne haut et bas du corps", ["Ne travaille que les bras", "Ignore les jambes", "Est identique au bro split"], "Upper puis Lower."],
      q2: ["Upper/Lower permet…", "Un volume important avec 4 séances", ["Zéro volume", "Uniquement du cardio", "1 muscle par mois"], "Distribution efficace."],
      q3: ["« Upper » inclut typiquement…", "Pectoraux, dos, épaules, bras", ["Uniquement les quadriceps", "Seulement les mollets", "Rien"], "Haut du corps."],
      blank: ["Upper/Lower = alternance entre haut et ___ du corps.", "bas", ["milieu", "côté", "extérieur"], "Structure du split."],
      tf1: ["Upper/Lower peut convenir à un volume modéré-élevé.", true, "Vrai : 2× upper, 2× lower."],
      tf2: ["Upper/Lower nécessite 6 séances obligatoires.", false, "Faux : souvent 4 séances."],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Push / Pull / Legs",
    "PPL : poussée, tirage, jambes.",
    [
      `Structure **PPL** :\n\n- **Push** : pectoraux, épaules, triceps\n- **Pull** : dos, biceps, deltoïdes postérieurs\n- **Legs** : quadriceps, ischio-jambiers, fessiers, mollets`,
      `Le PPL devient particulièrement intéressant lorsque le nombre de séances permet de **répéter la rotation** (ex. 6 jours = 2 cycles).`,
      `Juger le PPL sur ses variables réelles, pas sur le nom.`,
      `À retenir : PPL = regroupement fonctionnel poussée/tirage/jambes.`,
    ],
    ["ppl", "split"],
    CP.splits,
    {
      q1: ["Une séance Push travaille surtout…", "Pectoraux, épaules et triceps", ["Dos et biceps", "Uniquement les jambes", "Rien"], "Mouvements de poussée."],
      q2: ["Une séance Pull inclut…", "Dos, biceps et deltoïdes postérieurs", ["Pectoraux et triceps", "Seulement les mollets", "Abdos uniquement"], "Mouvements de tirage."],
      q3: ["Le PPL est surtout intéressant quand…", "On peut répéter la rotation (ex. 6 jours)", ["On s'entraîne 1×/mois", "On ignore les jambes", "On ne fait que du cardio"], "Fréquence par groupe."],
      blank: ["PPL = Push, Pull et ___.", "Legs", ["Lungs", "Lats", "Lifts"], "Jambes = troisième jour."],
      tf1: ["Le PPL regroupe les muscles par fonction de mouvement.", true, "Vrai : push/pull/legs."],
      tf2: ["Le PPL est le seul split valide scientifiquement.", false, "Faux : plusieurs splits fonctionnent."],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Bro Split et variantes",
    "Poitrine, dos, jambes, épaules, bras.",
    [
      `On peut organiser : poitrine, dos, jambes, épaules, bras — le **bro split** classique.`,
      `Ce format **peut fonctionner**, mais il faut vérifier la **fréquence** et la quantité de travail réalisée en une séance.`,
      `Un split ne doit pas être jugé par son nom mais par ses **variables réelles** : volume, fréquence, effort, récupération.`,
      `À retenir : bro split OK si volume et fréquence sont cohérents.`,
    ],
    ["bro-split", "split"],
    CP.splits,
    {
      q1: ["Le bro split organise souvent…", "Un muscle ou groupe par séance", ["Tout le corps chaque jour", "Uniquement le cardio", "Rien"], "Poitrine/back/legs…"],
      q2: ["Pour évaluer un bro split, il faut vérifier…", "Fréquence et volume par muscle", ["Uniquement le nom", "La couleur du programme", "Le nombre de miroirs"], "Variables réelles."],
      q3: ["Un bro split peut fonctionner si…", "Volume et récupération sont adaptés", ["On ignore la fréquence", "On ne dort jamais", "Volume = 0"], "Contexte compte."],
      blank: ["Ne jugez pas un split par son nom mais par ses ___ réelles.", "variables", ["couleurs", "photos", "hashtags"], "Volume, fréquence, effort."],
      tf1: ["1×/semaine par muscle peut suffire si le stimulus est adéquat.", true, "Vrai : dépend du volume par séance."],
      tf2: ["Le bro split est toujours supérieur au full body.", false, "Faux : dépend du pratiquant."],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Comment choisir le split",
    "Jours → volume → fréquence → distribution.",
    [
      `La question doit être : **combien de jours ?** Puis : quel volume ? Quelle fréquence ? Quelle distribution ?`,
      `Le **split vient après** ces contraintes, pas avant. Ne pas choisir PPL parce que c'est populaire si on ne peut s'entraîner que 3 jours.`,
      `Construire du bas vers le haut : contraintes → variables → structure.`,
      `À retenir : split = conséquence des contraintes, pas point de départ.`,
    ],
    ["choisir-split", "contraintes"],
    CP.splits,
    {
      q1: ["La première question pour choisir un split est…", "Combien de jours disponibles ?", ["Quel est le plus populaire ?", "Quelle couleur ?", "Quel influenceur ?"], "Contrainte n°1."],
      q2: ["Le split doit être choisi après…", "Volume, fréquence et distribution", ["Uniquement le nom du split", "La mode", "Le hasard"], "Variables avant structure."],
      q3: ["Choisir PPL avec seulement 2 jours/semaine…", "Peut ne pas être optimal", ["Est toujours parfait", "Remplace le volume", "Supprime la récupération"], "Adéquation jours/structure."],
      blank: ["Le split vient ___ les contraintes de jours et de volume.", "après", ["avant", "sans", "contre"], "Logique de construction."],
      tf1: ["3 jours/semaine peuvent convenir à un full body.", true, "Vrai : adéquation split/jours."],
      tf2: ["Il faut toujours choisir le split le plus populaire.", false, "Faux : adapter aux contraintes."],
    },
    "INTERMEDIATE",
  ),
];
