import { CP } from "./checkpoints";
import { buildLesson } from "./build-lesson";

export const THEME_9_LESSONS = [
  buildLesson(
    "Construire une spécialisation musculaire",
    "Redistribuer les ressources.",
    [
      `Pour faire progresser fortement un muscle, on peut : augmenter légèrement son volume, augmenter sa fréquence, le placer en début de séance, réduire légèrement le volume d'autres muscles, sélectionner des exercices très efficaces, améliorer la récupération locale.`,
      `La spécialisation est souvent une **redistribution des ressources**, pas simplement une addition infinie de séries.`,
      `Financer la priorité en réduisant ailleurs si nécessaire.`,
      `À retenir : spécialiser = allouer mieux, pas empiler sans limite.`,
    ],
    ["specialisation", "priorite"],
    CP.avance,
    {
      q1: ["Spécialiser un muscle peut inclure…", "Plus de volume, fréquence et meilleure position en séance", ["Le supprimer du programme", "Zéro stimulus", "Uniquement du cardio"], "Leviers multiples."],
      q2: ["La spécialisation est souvent…", "Une redistribution des ressources", ["Ajouter des séries à l'infini", "Ignorer la récupération", "Sans limite"], "Réallouer, pas tout augmenter."],
      q3: ["Pour spécialiser les pecs, on peut…", "Réduire légèrement le volume d'autres muscles", ["Supprimer tout le dos", "Ne plus dormir", "Ignorer la technique"], "Libérer de la récup."],
      blank: ["Spécialiser = souvent ___ les ressources, pas seulement ajouter.", "redistribuer", ["ignorer", "copier", "hasarder"], "Priorité financée ailleurs."],
      tf1: ["Placer le muscle prioritaire en début de séance aide la spécialisation.", true, "Vrai : meilleures séries."],
      tf2: ["Spécialiser = doubler le volume de tout le corps.", false, "Faux : cibler et réallouer."],
    },
    "ADVANCED",
  ),
  buildLesson(
    "Maintenir un muscle avec peu de volume",
    "Stimulus minimal de préservation.",
    [
      `Lorsqu'un muscle n'est plus prioritaire, on peut réduire son volume. Exemple : pectoraux 12 séries → 6 séries.`,
      `Le muscle peut continuer à être stimulé avec **beaucoup moins** de travail qu'il n'en fallait pour maximiser sa progression.`,
      `Cela libère de la récupération pour une autre priorité.`,
      `À retenir : maintien ≠ abandon — moins de séries suffisent souvent.`,
    ],
    ["maintien", "volume"],
    CP.avance,
    {
      q1: ["Maintenir un muscle peut nécessiter…", "Beaucoup moins de volume que pour le faire progresser", ["Zéro série", "Le double du volume", "Uniquement du cardio"], "Stimulus de préservation."],
      q2: ["Réduire un muscle non prioritaire de 12 à 6 séries…", "Peut libérer de la récupération", ["Le détruit toujours", "N'a aucun effet", "Remplace l'entraînement"], "Réallocation des ressources."],
      q3: ["Le maintien musculaire en sèche ou en spécialisation…", "Utilise un volume réduit mais suffisant", ["Ignore tout stimulus", "Nécessite 30 séries", "Est impossible"], "Moins que pour progresser."],
      blank: ["Passer de 12 à 6 séries est un exemple de volume de ___.", "maintien", ["maximal", "nul", "hasard"], "Réduction pour prioriser ailleurs."],
      tf1: ["On peut maintenir un muscle avec moins de séries qu'il n'en faut pour le développer.", true, "Vrai : seuil de maintien < seuil de croissance."],
      tf2: ["Pour maintenir un muscle, il faut toujours garder le volume maximal.", false, "Faux : moins suffit souvent."],
    },
    "ADVANCED",
  ),
  buildLesson(
    "Programmation en prise de masse et en sèche",
    "Adapter le stimulus à la phase.",
    [
      `**Prise de masse** : on cherche généralement à maximiser les adaptations musculaires. Le volume peut être maintenu ou progressivement augmenté si la récupération le permet.`,
      `**Sèche** : la priorité devient de préserver la masse musculaire tout en gérant la fatigue. On peut souvent réduire le volume si nécessaire tout en conservant un stimulus suffisamment intense.`,
      `Le programme doit évoluer avec la **phase nutritionnelle**.`,
      `À retenir : même entraînement rarement optimal en masse et en sèche.`,
    ],
    ["masse", "seche"],
    CP.avance,
    {
      q1: ["En prise de masse, le volume peut…", "Être maintenu ou augmenté si la récupération suit", ["Toujours être minimal", "Être supprimé", "Remplacer la nutrition"], "Maximiser adaptations."],
      q2: ["En sèche, la priorité devient…", "Préserver le muscle en gérant la fatigue", ["Perdre tout le muscle", "Supprimer la force", "Zéro entraînement"], "Maintien musculaire."],
      q3: ["En sèche, on peut souvent…", "Réduire le volume tout en gardant l'intensité d'effort", ["Supprimer toute intensité", "Doubler le volume", "Arrêter les polyarticulaires"], "Stimulus efficace, volume adapté."],
      blank: ["Le programme doit évoluer avec la phase ___.", "nutritionnelle", ["vestimentaire", "musicale", "saisonnière seule"], "Masse vs sèche."],
      tf1: ["En sèche, réduire le volume peut être pertinent.", true, "Vrai : fatigue et récupération limitées."],
      tf2: ["Le même programme est toujours optimal en masse et en sèche.", false, "Faux : adapter selon la phase."],
    },
    "ADVANCED",
  ),
  buildLesson(
    "Construire un programme de zéro",
    "14 étapes de la prescription.",
    [
      `Méthode complète :\n\n1. Objectif\n2. Nombre de séances\n3. Priorités musculaires\n4. Fréquence\n5. Volume initial\n6. Sélection des exercices\n7. Ordre des exercices\n8. Séries et répétitions\n9. RIR/RPE\n10. Repos\n11. Méthode de progression\n12. Durée du bloc\n13. Critères de réussite\n14. Critères de modification`,
      `Un programme professionnel doit avoir **un plan de progression** et **un plan d'ajustement**.`,
      `Ne pas s'arrêter à la liste d'exercices.`,
      `À retenir : prescription + progression + critères de changement.`,
    ],
    ["construire", "methode"],
    CP.avance,
    {
      q1: ["La première étape pour construire un programme est…", "Définir l'objectif", ["Choisir un split populaire", "Copier un PDF", "Maximiser les exercices"], "Objectif d'abord."],
      q2: ["Un programme professionnel inclut…", "Plan de progression et critères de modification", ["Uniquement des exercices", "Rien sur l'effort", "Pas de suivi"], "Prescription + ajustement."],
      q3: ["Avant les exercices, il faut définir…", "Séances disponibles, priorités et volume", ["La musique", "La couleur des haltères", "Le nom du programme"], "Contraintes et variables."],
      blank: ["Étape 9 : définir le ___ ou RPE pour l'effort.", "RIR", ["BPM", "IMC", "GPS"], "Intensité d'effort."],
      tf1: ["Les critères de modification font partie d'un bon programme.", true, "Vrai : quand changer."],
      tf2: ["Il suffit de lister exercices et séries pour un programme complet.", false, "Faux : progression et ajustement essentiels."],
    },
    "ADVANCED",
  ),
  buildLesson(
    "Le système complet de programmation",
    "Évaluer → prescrire → mesurer → ajuster.",
    [
      `La programmation avancée est une **boucle** :\n\n1. **Évaluer** — qui est le pratiquant, niveau, objectif, récupération\n2. **Prescrire** — volume, fréquence, exercices, intensité, effort, progression\n3. **Mesurer** — performances, charges, RIR, poids, récupération\n4. **Analyser** — progresse-t-on ? Si oui, ne changez pas inutilement\n5. **Ajuster** — volume, fréquence, effort, exercices selon le diagnostic\n6. **Recommencer**`,
      `C'est la différence entre **suivre un programme** et **savoir programmer**.`,
      `**Principes absolus** : ne jamais programmer sans objectif ; ne pas ajouter du volume sans raison ; mesurer les performances ; gérer la fatigue ; le meilleur programme est celui qu'on exécute régulièrement.`,
      `**Formule finale** — toujours pouvoir répondre : Qui ? Pourquoi ? Quoi ? Combien ? Combien de fois ? À quelle intensité ? Avec quel effort ? Comment progresser ? Quand modifier ? Comment récupérer ?`,
      `À retenir : programmation = boucle permanente, pas feuille statique.`,
    ],
    ["systeme", "boucle"],
    CP.avance,
    {
      q1: ["La boucle de programmation comprend notamment…", "Évaluer, prescrire, mesurer, analyser, ajuster", ["Copier, coller, oublier", "Uniquement mesurer", "Rien"], "Cycle complet."],
      q2: ["Si le pratiquant progresse…", "Ne pas changer le programme inutilement", ["Tout changer chaque semaine", "Ignorer les progrès", "Arrêter l'entraînement"], "Si ça marche, ne pas casser."],
      q3: ["Savoir programmer vs suivre un programme…", "Implique de construire et ajuster la boucle", ["Est identique", "Ne nécessite pas de mesure", "Ignore l'individualisation"], "Compétence vs exécution."],
      blank: ["La programmation est une boucle : évaluation → prescription → entraînement → mesure → ___ → ajustement.", "analyse", ["hasard", "oubli", "abandon"], "Analyser avant d'ajuster."],
      tf1: ["Mesurer performances et RIR fait partie du système complet.", true, "Vrai : données pour ajuster."],
      tf2: ["Un programme qui fonctionne doit être changé car il devient ennuyeux.", false, "Faux : ne pas changer sans raison."],
    },
    "ADVANCED",
    95,
  ),
];
