import { CP } from "./checkpoints";
import { buildLesson } from "./build-lesson";

export const THEME_5_LESSONS = [
  buildLesson(
    "L'ordre des exercices",
    "Refleter les priorités.",
    [
      `L'ordre dépend des **priorités**. Si les pectoraux sont prioritaires : mouvement pecs principal → second mouvement pecs → dos → épaules → bras.`,
      `Si les bras sont prioritaires, ils peuvent être placés plus tôt, quand la fatigue est moindre.`,
      `Le programme doit **refléter les priorités** dans l'ordre des exercices.`,
      `À retenir : ce qui compte le plus va en premier.`,
    ],
    ["ordre", "priorite"],
    CP.seances,
    {
      q1: ["L'ordre des exercices dépend surtout de…", "Les priorités du programme", ["L'alphabet", "La couleur des machines", "L'heure du repas"], "Priorité = placement."],
      q2: ["Si les pectoraux sont prioritaires…", "Les exercices pecs viennent en premier", ["Les mollets d'abord", "Le cardio uniquement", "Les bras en premier"], "Muscle prioritaire en tête."],
      q3: ["Placer un muscle prioritaire plus tôt permet…", "De l'entraîner avec moins de fatigue accumulée", ["De le négliger", "De réduire le stimulus", "De l'ignorer"], "Fraîcheur = meilleures séries."],
      blank: ["Le programme doit refléter les ___ dans l'ordre des exercices.", "priorités", ["couleurs", "hasards", "miroirs"], "Ordre = hiérarchie."],
      tf1: ["Un muscle secondaire peut être placé après les priorités.", true, "Vrai : ordre logique."],
      tf2: ["L'ordre des exercices n'a aucune importance.", false, "Faux : fatigue et priorité changent le résultat."],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Priorisation musculaire",
    "Plus que « faire plus ».",
    [
      `Un muscle prioritaire peut recevoir : davantage de **séries**, une meilleure **fréquence**, une meilleure **position** dans la séance, davantage de proximité de l'échec, davantage de variations, une meilleure récupération.`,
      `La spécialisation ne consiste donc pas uniquement à « faire plus » — c'est une **redistribution** intelligente des ressources.`,
      `Réduire légèrement ailleurs pour financer la priorité.`,
      `À retenir : spécialiser = allouer mieux, pas seulement ajouter.`,
    ],
    ["priorisation", "specialisation"],
    CP.seances,
    {
      q1: ["Prioriser un muscle peut inclure…", "Plus de séries, meilleure fréquence et position en séance", ["Uniquement moins de repos", "Le supprimer ensuite", "Zéro volume"], "Plusieurs leviers."],
      q2: ["La spécialisation musculaire est…", "Une redistribution des ressources", ["Seulement ajouter des séries infiniment", "Ignorer la récupération", "Sans limite"], "Allouer intelligemment."],
      q3: ["Un muscle prioritaire peut être placé…", "En début de séance", ["Toujours à la fin", "Jamais", "Uniquement le dimanche"], "Position = fraîcheur."],
      blank: ["Prioriser un muscle, ce n'est pas seulement « faire plus », c'est mieux ___.", "allouer", ["ignorer", "copier", "hasarder"], "Redistribution des ressources."],
      tf1: ["Un muscle prioritaire peut recevoir plus de séries et une meilleure fréquence.", true, "Vrai : leviers multiples."],
      tf2: ["Spécialiser un muscle = uniquement doubler le volume sans autre changement.", false, "Faux : redistribution globale."],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Exercices qui se chevauchent",
    "Volume systémique et fatigue partagée.",
    [
      `Exemple : développé couché (pecs, triceps, deltoïdes ant.) + développé militaire (deltoïdes, triceps). Si les deux sont présents avec beaucoup de volume, la fatigue des triceps et épaules peut devenir importante.`,
      `Le programmateur doit regarder le **volume systémique** et les **chevauchements**, pas seulement compter les exercices.`,
      `Planifier le volume bras/épaules en incluant le travail indirect des développés.`,
      `À retenir : les polyarticulaires créent des chevauchements — les intégrer au calcul.`,
    ],
    ["chevauchement", "fatigue"],
    CP.seances,
    {
      q1: ["Développé couché + développé militaire cumulent surtout…", "Triceps et deltoïdes", ["Uniquement les mollets", "Rien", "Seulement le dos"], "Chevauchement haut du corps."],
      q2: ["Le programmateur doit considérer…", "Volume systémique et chevauchements", ["Uniquement le nombre d'exercices", "Seulement les isolations", "Zéro fatigue"], "Fatigue partagée."],
      q3: ["Beaucoup de volume sur développés + isolations triceps…", "Peut surcharger les triceps", ["N'a aucun effet", "Réduit toujours la fatigue", "Supprime le travail indirect"], "Volume direct + indirect."],
      blank: ["Il faut intégrer le travail ___ des polyarticulaires.", "indirect", ["nul", "respiratoire", "cardiaque"], "Ne pas compter deux fois ou surcharger."],
      tf1: ["Deux exercices peuvent fatiguer les mêmes muscles indirectement.", true, "Vrai : chevauchement fréquent."],
      tf2: ["Chaque exercice fatigue uniquement son muscle « étiquette ».", false, "Faux : polyarticulaires = contributions multiples."],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Construire une séance efficace",
    "Priorité → complémentaire → isolation.",
    [
      `Une séance peut suivre cette logique :\n\n1. **Priorité** — muscle ou mouvement principal\n2. **Secondaire** — autre angle ou fonction\n3. **Complémentaire** — muscles secondaires\n4. **Isolation** — ciblage précis\n5. **Optionnel** — abdos, mollets, etc.`,
      `Une bonne séance n'est pas nécessairement **longue**. Elle doit être **productive**.`,
      `Qualité des séries prioritaires > quantité d'exercices inutiles.`,
      `À retenir : structure logique, pas accumulation d'exercices.`,
    ],
    ["structure-seance", "efficacite"],
    CP.seances,
    {
      q1: ["En début de séance on place surtout…", "Le muscle ou mouvement prioritaire", ["Les mollets", "Le cardio long", "L'étirement passif"], "Priorité en premier."],
      q2: ["Une bonne séance est…", "Productive, pas forcément longue", ["Toujours de 3 heures", "Remplie d'exercices au hasard", "Sans structure"], "Efficacité > durée."],
      q3: ["Après le mouvement principal viennent souvent…", "Mouvements secondaires et complémentaires", ["Uniquement le repos", "Rien d'autre", "10 exercices aléatoires"], "Structure progressive."],
      blank: ["Une séance efficace place l'___ en premier.", "priorité", ["fatigue", "hasard", "ennui"], "Muscle/mouvement clé d'abord."],
      tf1: ["L'isolation vient généralement après les mouvements principaux.", true, "Vrai : ciblage précis en fin."],
      tf2: ["Plus une séance est longue, meilleure elle est toujours.", false, "Faux : productivité > durée."],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "La densité d'entraînement",
    "Travail par unité de temps.",
    [
      `La **densité** correspond à la quantité de travail réalisée dans une période donnée. Exemple : 10 séries en 60 minutes vs 10 séries en 90 minutes — densité différente.`,
      `Mais augmenter la densité n'est pas automatiquement bénéfique pour l'hypertrophie. Il faut éviter que des repos trop courts diminuent la **performance**.`,
      `Densité utile = plus de travail qualitatif, pas repos coupés au détriment des reps.`,
      `À retenir : densité ≠ repos ultra-courts si la perf chute.`,
    ],
    ["densite", "repos"],
    CP.seances,
    {
      q1: ["La densité d'entraînement correspond à…", "La quantité de travail par période de temps", ["Le poids corporel", "Le nombre de followers", "La couleur du programme"], "Séries / minute."],
      q2: ["10 séries en 60 min vs 90 min…", "Densité différente", ["Identique", "Sans importance", "Impossible"], "Même volume, temps différent."],
      q3: ["Augmenter la densité n'est pas toujours bénéfique car…", "Des repos trop courts peuvent réduire la performance", ["La gravité change", "Les muscles disparaissent", "Le volume augmente"], "Perf > vitesse de séance."],
      blank: ["Il faut éviter que des repos trop courts ___ la performance.", "diminuent", ["améliorent toujours", "ignorent", "remplacent"], "Qualité des séries prime."],
      tf1: ["Réduire le repos peut augmenter la densité.", true, "Vrai : plus de travail par minute."],
      tf2: ["Pour l'hypertrophie, toujours minimiser le repos est optimal.", false, "Faux : perf peut en souffrir."],
    },
    "INTERMEDIATE",
  ),
];
