import { CP } from "./checkpoints";
import { buildLesson } from "./build-lesson";

export const THEME_7_LESSONS = [
  buildLesson(
    "Microcycle, mésocycle, macrocycle",
    "Semaine, bloc, plan long terme.",
    [
      `**Microcycle** : généralement une semaine d'entraînement.\n\n**Mésocycle** : bloc de plusieurs semaines avec un objectif précis.\n\n**Macrocycle** : ensemble de plusieurs blocs sur le long terme.`,
      `Exemple macrocycle 6 mois : accumulation → progression → spécialisation → récupération → nouveau développement.`,
      `Organiser l'entraînement à plusieurs échelles de temps.`,
      `À retenir : semaine < bloc < plan annuel.`,
    ],
    ["microcycle", "mesocycle", "macrocycle"],
    CP.periodisation,
    {
      q1: ["Un microcycle correspond généralement à…", "Une semaine", ["Un an", "Une séance", "Une rep"], "Échelle hebdomadaire."],
      q2: ["Un mésocycle est…", "Un bloc de plusieurs semaines avec un objectif", ["Une seule série", "Un exercice", "Un repas"], "Bloc intermédiaire."],
      q3: ["Un macrocycle regroupe…", "Plusieurs blocs sur le long terme", ["Une seule séance", "Uniquement le deload", "Rien"], "Vision long terme."],
      blank: ["Le ___ est un bloc de plusieurs semaines (ex. 4–8 semaines).", "mésocycle", ["microcycle", "repas", "miroir"], "Entre semaine et année."],
      tf1: ["On peut enchaîner accumulation, progression et récupération dans un macrocycle.", true, "Vrai : périodisation long terme."],
      tf2: ["Microcycle et macrocycle désignent la même chose.", false, "Faux : semaine vs plan long."],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Progression linéaire",
    "Augmenter progressivement la difficulté.",
    [
      `La **progression linéaire** consiste à augmenter progressivement la difficulté. Exemple : S1 3×10 → S2 3×10 plus lourd → S3 idem → S4 idem.`,
      `Simple et efficace pour certains pratiquants (souvent débutants ou retour).`,
      `Mais cette stratégie devient moins adaptée lorsque les performances **fluctuent** beaucoup ou stagnent longtemps.`,
      `À retenir : linéaire = simple, mais pas éternel.`,
    ],
    ["lineaire", "progression"],
    CP.periodisation,
    {
      q1: ["La progression linéaire consiste à…", "Augmenter progressivement la difficulté", ["Changer tout chaque jour", "Ne jamais progresser", "Réduire chaque semaine"], "Montée régulière."],
      q2: ["Elle est souvent efficace pour…", "Débutants ou retours d'entraînement", ["Tous les niveaux indéfiniment", "Personne", "Uniquement le cardio"], "Phase de gains rapides."],
      q3: ["Elle devient moins adaptée quand…", "Les performances fluctuent et stagnent", ["Tout va parfaitement", "On débute", "On récupère bien"], "Plateau = changer d'approche."],
      blank: ["Progression linéaire : même schéma, charge un peu plus ___ chaque semaine.", "lourde", ["légère", "nulle", "aléatoire"], "Surcharge graduelle."],
      tf1: ["La progression linéaire est simple à appliquer.", true, "Vrai : +charge régulière."],
      tf2: ["La progression linéaire fonctionne pour toujours à tout niveau.", false, "Faux : limite à long terme."],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Périodisation ondulatoire",
    "Variables qui changent dans la semaine.",
    [
      `La **périodisation ondulatoire** : les variables changent davantage au sein de la semaine.`,
      `Exemple : lundi force 5–6 reps, jeudi hypertrophie 8–12 reps.`,
      `Utile lorsque plusieurs qualités doivent être développées simultanément.`,
      `À retenir : ondule = intensité/reps variables dans la même semaine.`,
    ],
    ["ondulatoire", "periodisation"],
    CP.periodisation,
    {
      q1: ["La périodisation ondulatoire change surtout…", "Les variables au sein de la semaine", ["Uniquement l'année", "Rien", "Seulement le cardio"], "Variation intra-semaine."],
      q2: ["Exemple : lundi 5–6 reps, jeudi 8–12 reps…", "C'est une forme d'ondulation", ["C'est identique", "C'est un deload", "C'est du repos"], "Force vs hypertrophie."],
      q3: ["L'ondulation peut servir à…", "Développer plusieurs qualités", ["Supprimer le volume", "Éviter toute progression", "Remplacer la récupération"], "Force + hypertrophie."],
      blank: ["En ondulation, les ___ changent d'une séance à l'autre dans la semaine.", "variables", ["couleurs", "salles", "miroirs"], "Reps, charge, effort."],
      tf1: ["Onduler reps et charge dans la semaine est une stratégie valide.", true, "Vrai : périodisation ondulatoire."],
      tf2: ["Toutes les séances d'une semaine doivent avoir les mêmes reps.", false, "Faux : ondulation varie."],
    },
    "ADVANCED",
  ),
  buildLesson(
    "Accumulation et intensification",
    "Volume puis intensité, puis deload.",
    [
      `On peut construire un bloc ainsi :\n\n- **Accumulation** : volume relativement élevé, effort contrôlé\n- **Intensification** : volume réduit ou stabilisé, intensité plus élevée\n- **Deload** : réduction de la fatigue`,
      `Cette logique permet de gérer la progression sur **plusieurs semaines** sans tout maximiser en même temps.`,
      `Classique en force et en hypertrophie avancée.`,
      `À retenir : accumuler → intensifier → récupérer.`,
    ],
    ["accumulation", "intensification"],
    CP.periodisation,
    {
      q1: ["La phase d'accumulation met l'accent sur…", "Volume élevé, effort contrôlé", ["Repos total", "Zéro volume", "Uniquement le cardio"], "Construire le travail."],
      q2: ["La phase d'intensification…", "Réduit ou stabilise le volume, monte l'intensité", ["Double toujours le volume", "Supprime l'effort", "Ignore la charge"], "Pic de performance."],
      q3: ["Après accumulation + intensification…", "Un deload peut réduire la fatigue", ["Il faut doubler le volume", "On arrête 6 mois", "On ignore la récup"], "Cycle complet."],
      blank: ["Accumulation → intensification → ___.", "deload", ["échec permanent", "abandon", "hasard"], "Gestion fatigue du bloc."],
      tf1: ["Ne pas maximiser volume et intensité en permanence est une bonne logique.", true, "Vrai : phases distinctes."],
      tf2: ["Il faut toujours être en phase d'intensification maximale.", false, "Faux : alterner les phases."],
    },
    "ADVANCED",
  ),
  buildLesson(
    "Quand faire un deload ?",
    "Outil, pas obligation calendaire.",
    [
      `Le **deload** est une période volontairement moins fatigante. Il peut être programmé : après un bloc, quand la fatigue s'accumule, avant une période importante, ou quand un plateau s'accompagne de signes de récupération insuffisante.`,
      `On peut réduire : séries, charge, proximité de l'échec.`,
      `Le deload n'est **pas obligatoirement** nécessaire à une fréquence fixe pour tout le monde.`,
      `À retenir : deload quand la fatigue le justifie, pas par calendrier aveugle.`,
    ],
    ["deload", "fatigue"],
    CP.periodisation,
    {
      q1: ["Un deload sert à…", "Réduire volontairement la fatigue", ["Maximiser le volume", "Supprimer l'entraînement à vie", "Doubler la charge"], "Récupération planifiée."],
      q2: ["On peut deload en réduisant…", "Séries, charge ou proximité de l'échec", ["Uniquement les protéines", "Le sommeil à 0 h", "La motivation"], "Leviers de réduction."],
      q3: ["Le deload est nécessaire…", "Quand la fatigue le justifie, pas forcément à date fixe", ["Chaque lundi obligatoire", "Jamais", "À chaque séance"], "Individualisé."],
      blank: ["Le deload est un ___, pas une obligation calendaire pour tous.", "outil", ["mythe", "punition", "hasard"], "Utiliser avec discernement."],
      tf1: ["Un deload peut suivre un bloc d'accumulation/intensification.", true, "Vrai : logique de cycle."],
      tf2: ["Tout le monde doit deload exactement toutes les 4 semaines.", false, "Faux : dépend de la fatigue."],
    },
    "ADVANCED",
  ),
];
