import { CP } from "./checkpoints";
import { buildLesson } from "./build-lesson";

export const THEME_8_LESSONS = [
  buildLesson(
    "Adapter le programme à la récupération",
    "Observer performances, sommeil, stress.",
    [
      `Deux personnes faisant exactement le même entraînement peuvent récupérer **différemment**. Il faut observer : performances, sommeil, douleurs, motivation, fatigue, poids, stress.`,
      `Le programme doit être ajusté au **retour réel** du pratiquant, pas seulement au plan théorique.`,
      `La récupération guide les ajustements de volume et d'effort.`,
      `À retenir : même programme ≠ même réponse — écouter les signaux.`,
    ],
    ["recuperation", "ajustement"],
    CP.individualisation,
    {
      q1: ["Deux personnes au même programme peuvent…", "Récupérer différemment", ["Réagir identiquement toujours", "Ne jamais progresser", "Ignorer le sommeil"], "Individualité récup."],
      q2: ["Il faut observer notamment…", "Performances, sommeil, stress et fatigue", ["Uniquement le BPM", "La couleur des haltères", "Le nombre de miroirs"], "Signaux de récup."],
      q3: ["Le programme doit s'ajuster selon…", "Le retour réel du pratiquant", ["Uniquement le papier", "La mode", "Le hasard"], "Feedback loop."],
      blank: ["Adapter le programme = réagir au ___ réel du pratiquant.", "retour", ["hasard", "miroir", "hashtag"], "Perf, fatigue, sommeil."],
      tf1: ["Le stress peut influencer la récupération et le programme.", true, "Vrai : facteur systémique."],
      tf2: ["Le même programme convient identiquement à tous sans ajustement.", false, "Faux : individualisation nécessaire."],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Identifier un programme trop facile",
    "Stimulus insuffisant.",
    [
      `Signes possibles : aucune progression, faible stimulation, récupération excellente, entraînement très facile, volume très faible.`,
      `On peut alors tester une augmentation **progressive** du stimulus : volume, effort, charge ou fréquence — une variable à la fois.`,
      `Trop facile = marge pour monter le stimulus.`,
      `À retenir : pas de progrès + facilité = probablement sous-stimulus.`,
    ],
    ["trop-facile", "stimulus"],
    CP.individualisation,
    {
      q1: ["Un programme trop facile peut se manifester par…", "Aucune progression et faible stimulation", ["Fatigue extrême", "Blessures constantes", "Échec systématique"], "Sous-stimulus."],
      q2: ["Si le programme est trop facile, on peut…", "Augmenter progressivement le stimulus", ["Tout changer d'un coup", "Arrêter de s'entraîner", "Réduire le volume"], "Monter une variable."],
      q3: ["Récupération excellente + zéro progression suggère…", "Stimulus peut-être insuffisant", ["Trop de volume", "Deload urgent", "Arrêt définitif"], "Pas assez de travail."],
      blank: ["Programme trop facile : tester une augmentation ___ du stimulus.", "progressive", ["brutale", "nulle", "aléatoire"], "Une variable à la fois."],
      tf1: ["Un volume très faible peut expliquer l'absence de progression.", true, "Vrai : sous MEV possible."],
      tf2: ["Si c'est facile, il faut toujours doubler le volume immédiatement.", false, "Faux : augmentation progressive."],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Identifier un programme trop difficile",
    "Réduire avant de forcer.",
    [
      `Signes possibles : performances en baisse, fatigue persistante, douleurs, récupération insuffisante, motivation en baisse, stagnation prolongée.`,
      `La réponse n'est pas toujours de « forcer davantage ». Il peut être nécessaire de **réduire** le volume ou l'effort.`,
      `Plus n'est pas mieux si la récupération ne suit pas.`,
      `À retenir : signes de surmenage → alléger, pas empiler.`,
    ],
    ["trop-difficile", "surmenage"],
    CP.individualisation,
    {
      q1: ["Un programme trop difficile peut montrer…", "Performances en baisse et fatigue persistante", ["Progression constante", "Récupération parfaite", "Motivation maximale"], "Surmenage."],
      q2: ["Face à un programme trop dur, on peut…", "Réduire volume ou effort", ["Toujours forcer plus", "Supprimer le sommeil", "Doubler les séries"], "Alléger le stimulus."],
      q3: ["Fatigue persistante + stagnation suggèrent…", "Possible excès de charge d'entraînement", ["Besoin de plus de volume", "Programme parfait", "Rien à changer"], "Diagnostic surmenage."],
      blank: ["La réponse n'est pas toujours de forcer davantage, parfois il faut ___.", "réduire", ["ignorer", "abandonner", "hasarder"], "Volume ou effort."],
      tf1: ["Réduire l'effort peut aider quand la fatigue est excessive.", true, "Vrai : gestion de la dose."],
      tf2: ["Si ça ne marche pas, il faut toujours ajouter plus de séries.", false, "Faux : parfois réduire."],
    },
    "INTERMEDIATE",
  ),
  buildLesson(
    "Analyser un plateau",
    "Diagnostiquer avant de modifier.",
    [
      `Lorsqu'une personne stagne, il faut **diagnostiquer** avant de modifier. Questions : progresse-t-on réellement (mesures) ? Sommeil suffisant ? Poids corporel ? Volume approprié ? RIR correct ? Technique stable ? Exercices adaptés ? Fatigue excessive ?`,
      `Un plateau est un **problème à diagnostiquer**, pas automatiquement un manque de volume.`,
      `Checklist systématique avant tout changement.`,
      `À retenir : plateau = enquête, pas réflexe « +séries ».`,
    ],
    ["plateau", "diagnostic"],
    CP.individualisation,
    {
      q1: ["Face à un plateau, il faut d'abord…", "Diagnostiquer la cause", ["Changer tout le programme", "Doubler le volume", "Ignorer les signaux"], "Enquête avant action."],
      q2: ["Questions utiles incluent…", "Sommeil, volume, RIR et technique", ["Couleur des chaussures", "Nombre de likes", "Marque de la salle"], "Facteurs réels."],
      q3: ["Un plateau signifie…", "Un problème à analyser, pas toujours plus de volume", ["Toujours ajouter 10 séries", "Arrêter la musculation", "Rien à faire"], "Diagnostic nuancé."],
      blank: ["Avant de modifier, vérifier si les performances sont bien ___.", "mesurées", ["ignorées", "devinées", "oubliées"], "Logbook et suivi."],
      tf1: ["Le sommeil insuffisant peut causer un plateau.", true, "Vrai : récupération clé."],
      tf2: ["Tout plateau = manque de volume.", false, "Faux : multiples causes possibles."],
    },
    "ADVANCED",
  ),
  buildLesson(
    "Modifier une seule variable",
    "Savoir ce qui a changé le résultat.",
    [
      `Quand le programme ne fonctionne plus, évitez de changer simultanément : exercices, séries, répétitions, fréquence, RIR, repos.`,
      `Sinon, vous ne saurez pas ce qui a produit le changement.`,
      `Bonne pratique : modifier progressivement les variables les plus **pertinentes** selon le diagnostic.`,
      `À retenir : un changement à la fois = apprentissage du programme.`,
    ],
    ["une-variable", "modification"],
    CP.individualisation,
    {
      q1: ["Changer plusieurs variables à la fois…", "Empêche de savoir ce qui a fonctionné", ["Est toujours optimal", "Remplace le diagnostic", "Est obligatoire"], "Confusion causale."],
      q2: ["Bonne pratique : modifier…", "Une variable pertinente à la fois", ["Tout en même temps", "Rien jamais", "Au hasard"], "Contrôle des changements."],
      q3: ["Si on change exercices + séries + fréquence + RIR…", "On ne saura pas ce qui a aidé", ["On apprend beaucoup", "C'est idéal", "Rien ne change"], "Trop de variables."],
      blank: ["Modifier une seule ___ permet d'interpréter le résultat.", "variable", ["personne", "salle", "playlist"], "Méthode scientifique simple."],
      tf1: ["Ajuster le RIR seul peut suffire sans tout changer.", true, "Vrai : levier ciblé."],
      tf2: ["Il faut toujours tout changer quand on stagne.", false, "Faux : changement progressif."],
    },
    "ADVANCED",
  ),
];
