import type { SeedQuestion } from "../anatomie-quiz-helpers";
import { qcm, tf, multi, order, match } from "../anatomie-quiz-helpers";
import { quiz20 } from "./quiz-bank";

export const THEME_5_QUIZZES: SeedQuestion[][] = [
  quiz20(
    qcm("Les fibres solubles forment souvent…", "Un gel dans l'intestin", ["Du glycogène", "Des enzymes musculaires", "De l'alcool"], "Le gel ralentit l'absorption."),
    qcm("Les fibres insolubles aident surtout…", "Le transit", ["La vision", "La contraction seule", "La production d'insuline"], "Elles donnent du volume aux selles."),
    qcm("L'avoine et les légumineuses apportent surtout des fibres…", "Solubles", ["Animales", "Minérales", "Respiratoires"], "Elles peuvent former un gel."),
    qcm("Le blé complet et les légumes feuillus apportent souvent des fibres…", "Insolubles", ["Liquides", "Protéiques", "Alcoolisées"], "Elles soutiennent le volume intestinal."),
    qcm("La plupart des végétaux contiennent…", "Un mélange de fibres", ["Une seule fibre pure", "Uniquement du sucre", "Zéro résidu"], "Les deux familles coexistent souvent."),
    qcm("En sèche, les fibres sont utiles car elles…", "Augmentent la satiété", ["Ajoutent beaucoup d'alcool", "Suppriment le besoin de protéines", "Empêchent toute digestion"], "Elles calent pour peu de calories."),
    qcm("Manger beaucoup de fibres sans eau peut…", "Donner une satiété sèche", ["Hydrater les selles automatiquement", "Accélérer toujours le transit", "Créer du glucose rapide"], "Les fibres ont besoin d'eau."),
    qcm("La distinction soluble/insoluble décrit surtout…", "Le comportement dans l'intestin", ["La couleur des légumes", "Le goût sucré", "La vitesse de mastication"], "Gel ou volume : effets différents."),
    tf("Les fibres solubles peuvent ralentir l'absorption du sucre.", true, "Vrai : le gel freine le passage."),
    tf("Les fibres insolubles n'ont aucun rôle sur le transit.", false, "Faux : elles aident le volume des selles."),
    tf("Tous les aliments végétaux n'apportent qu'un seul type de fibre.", false, "Faux : beaucoup mélangent les deux."),
    tf("Les fibres peuvent améliorer la satiété sans beaucoup de calories.", true, "Vrai : volume et ralentissement digestif."),
    multi("Quels effets sont liés aux fibres solubles ?", ["Formation d'un gel", "Ralentissement de l'absorption"], ["Stockage direct en glycogène", "Production d'oxygène"], "Le gel explique l'effet principal."),
    multi("Quels effets sont liés aux fibres insolubles ?", ["Volume des selles", "Aide au transit"], ["Pic glycémique rapide", "Digestion en acides aminés"], "Elles agissent surtout mécaniquement."),
    order("Remets l'effet des fibres solubles dans l'ordre.", ["Fibres dans l'intestin", "Gel formé", "Absorption ralentie"], "Le gel freine le passage."),
    order("Remets l'effet transit dans l'ordre.", ["Fibres insolubles", "Volume augmenté", "Transit facilité"], "Le volume aide le déplacement."),
    match("Associe type et effet.", [["Solubles", "Gel"], ["Insolubles", "Transit"], ["Mélange", "Végétaux variés"]], "Les deux familles se complètent."),
    match("Associe aliment et fibre dominante.", [["Avoine", "Soluble"], ["Légumes feuillus", "Insoluble"], ["Légumineuses", "Soluble"]], "Ce sont des repères pratiques."),
    qcm("La meilleure stratégie fibres au quotidien est…", "Varier les sources", ["Ne manger que du son", "Éviter tous les végétaux", "Prendre un seul aliment miracle"], "La variété apporte les deux types."),
    qcm("Si les fibres donnent une sensation trop sèche, la première chose à vérifier est…", "L'apport en eau", ["La couleur des aliments", "Le nombre de couverts", "Le timing des chaussures"], "Fibres et eau fonctionnent ensemble."),
  ),
  quiz20(
    qcm("La satiété désigne…", "La sensation durable d'être rassasié", ["La soif", "La force maximale", "La vitesse de digestion seule"], "C'est le signal de repas suffisant."),
    qcm("La satiété dépend notamment…", "Du volume et de la composition du repas", ["De la marque de l'assiette", "De la couleur de la table", "Uniquement de l'heure"], "Plusieurs signaux se combinent."),
    qcm("Protéines et fibres ont souvent pour effet de…", "Mieux caler", ["Accélérer la faim", "Bloquer la respiration", "Supprimer l'eau"], "Elles prolongent la satiété."),
    qcm("Les lipides prolongent la satiété mais…", "Sont denses en calories", ["Ne contiennent aucune énergie", "Remplacent les fibres", "Empêchent les protéines"], "Ils calent, mais montent vite les calories."),
    qcm("Le cerveau met souvent environ…", "15 à 20 minutes à recevoir le signal", ["2 secondes", "6 heures", "2 jours"], "Manger lentement laisse le temps au signal."),
    qcm("Un grand bol de légumes peut aider car il apporte…", "Du volume", ["De l'alcool", "Du gras pur", "Une absence totale de fibres"], "Le volume participe à la satiété."),
    qcm("Un repas seulement sucré et liquide cale souvent…", "Peu longtemps", ["Toujours 8 heures", "Plus que protéines et fibres", "Sans digestion"], "Peu de volume et absorption rapide."),
    qcm("Pour limiter les grignotages, on vise souvent…", "Protéines, fibres et volume", ["Sucre liquide seul", "Zéro repas", "Lipides sans mesure"], "Ce trio aide le contrôle de faim."),
    tf("Deux repas de mêmes calories peuvent caler différemment.", true, "Vrai : composition et volume changent tout."),
    tf("Les lipides n'apportent presque pas de calories.", false, "Faux : ils sont très denses."),
    tf("Manger lentement peut aider le signal de satiété.", true, "Vrai : le cerveau a besoin de temps."),
    tf("Les protéines et fibres sont souvent peu satiétantes.", false, "Faux : elles font partie des meilleurs leviers."),
    multi("Quels éléments augmentent souvent la satiété ?", ["Protéines", "Fibres", "Volume alimentaire"], ["Soda seul"], "Ils multiplient les signaux de rassasiement."),
    multi("Quels points décrivent les lipides ?", ["Prolongent la satiété", "Très caloriques"], ["Sans énergie", "Toujours sans effet digestif"], "Ils calent mais se dosent."),
    order("Remets le signal de satiété dans l'ordre.", ["Repas commence", "Estomac se remplit", "Cerveau reçoit le signal"], "Le signal prend du temps."),
    order("Remets une assiette rassasiante dans l'ordre logique.", ["Base protéinée", "Fibres et légumes", "Lipides dosés"], "On combine les leviers."),
    match("Associe levier et effet.", [["Protéines", "Rassasiement"], ["Fibres", "Volume"], ["Lipides", "Digestion plus lente"]], "Chaque levier joue différemment."),
    match("Associe situation et conséquence.", [["Manger vite", "Signal tardif"], ["Repas volumineux", "Meilleure satiété"], ["Sucre liquide", "Faim rapide"]], "Le comportement compte aussi."),
    qcm("En déficit calorique, le choix le plus malin est souvent…", "Des aliments rassasiants et peu denses", ["Des calories liquides seules", "Supprimer les protéines", "Tout miser sur l'huile"], "Caler aide à tenir le déficit."),
    qcm("La satiété n'est pas une question de calories seules car…", "La forme du repas change les signaux", ["Les calories n'existent pas", "Le cerveau ignore l'estomac", "Les fibres sont du muscle"], "Volume, texture et macros comptent."),
  ),
  quiz20(
    qcm("Le transit désigne…", "Le passage des résidus dans l'intestin", ["La force du biceps", "Le taux de glycogène", "La respiration"], "C'est le rythme intestinal."),
    qcm("Un transit trop lent peut donner…", "Constipation et lourdeur", ["Pic de force", "Meilleure absorption toujours", "Glycémie nulle"], "Les selles restent trop longtemps."),
    qcm("Un transit trop rapide peut réduire…", "Le confort et parfois l'absorption", ["La gravité", "La taille du muscle", "La mastication"], "Le passage est trop court."),
    qcm("Fibres et eau aident car elles rendent les selles…", "Plus volumineuses et souples", ["Plus sèches", "Plus sucrées", "Inexistantes"], "Eau + fibres = meilleur transit."),
    qcm("Augmenter les fibres trop vite peut provoquer…", "Ballonnements", ["Plus de 1RM immédiat", "Absence de gaz à vie", "Moins de besoin d'eau"], "Le tube digestif doit s'adapter."),
    qcm("Le mouvement aide le transit car il…", "Stimule le système digestif", ["Arrête l'intestin", "Remplace l'eau", "Supprime les fibres"], "Marcher peut déjà aider."),
    qcm("La progression des fibres doit être…", "Graduelle", ["Brutale", "Inutile", "Uniquement nocturne"], "L'intestin s'adapte mieux."),
    qcm("Pour un transit confortable, la base est…", "Fibres, eau et mouvement", ["Zéro végétal", "Alcool seul", "Uniquement compléments"], "Les trois leviers sont simples."),
    tf("Les fibres absorbent de l'eau dans l'intestin.", true, "Vrai : surtout les fibres insolubles."),
    tf("Boire assez peut aider le transit.", true, "Vrai : l'eau assouplit les selles."),
    tf("Augmenter les fibres brutalement est toujours confortable.", false, "Faux : ballonnements fréquents."),
    tf("L'activité physique n'a aucun effet sur le transit.", false, "Faux : le mouvement stimule l'intestin."),
    multi("Quels leviers améliorent souvent le transit ?", ["Fibres", "Eau", "Mouvement"], ["Sédentarité totale"], "Transit = matière, hydratation, activité."),
    multi("Quels signes peuvent accompagner un transit lent ?", ["Constipation", "Lourdeur"], ["Glycémie parfaite garantie", "Plus de fibres musculaires"], "Le ralentissement se ressent."),
    order("Remets une augmentation de fibres dans l'ordre.", ["Ajouter une petite portion", "Boire assez", "Observer le confort"], "La progression évite l'inconfort."),
    order("Remets l'effet fibres-eau dans l'ordre.", ["Fibres arrivent", "Eau retenue", "Selles plus souples"], "L'eau donne l'effet utile."),
    match("Associe situation et effet.", [["Transit lent", "Constipation"], ["Transit rapide", "Inconfort"], ["Mouvement", "Stimulation"]], "Le rythme influence le confort."),
    match("Associe levier et rôle.", [["Eau", "Souplesse"], ["Fibres", "Volume"], ["Marche", "Motricité"]], "Les leviers se complètent."),
    qcm("Si les fibres te ballonnent, la réaction la plus logique est…", "Réduire puis remonter progressivement", ["Doubler d'un coup", "Supprimer toute eau", "Arrêter tout mouvement"], "Le microbiote et l'intestin s'adaptent."),
    qcm("Un transit confortable compte pour l'entraînement car…", "Il évite lourdeur et gêne en séance", ["Il remplace l'échauffement", "Il augmente directement le biceps", "Il bloque la fatigue"], "Le confort digestif aide le focus."),
  ),
  quiz20(
    qcm("Le microbiote intestinal regroupe surtout…", "Des bactéries utiles", ["Des os", "Des fibres musculaires", "Du glycogène pur"], "C'est un écosystème microbien."),
    qcm("Il se situe surtout dans…", "Le côlon", ["Le tibia", "Les poumons", "Le biceps"], "Le côlon abrite une grande densité bactérienne."),
    qcm("Une diversité alimentaire soutient…", "Un microbiote plus varié", ["Une absence de bactéries", "La suppression des fibres", "Le stockage d'air"], "Différents aliments nourrissent différents microbes."),
    qcm("Les prébiotiques sont…", "Des fibres qui nourrissent les bactéries utiles", ["Des antibiotiques", "Des protéines de poulet", "Des minéraux sans rôle"], "Prébiotique = nourriture du microbiote."),
    qcm("Un microbiote utile peut participer à…", "La digestion de certaines fibres", ["La contraction directe du muscle", "La fabrication des chaussures", "La respiration pulmonaire"], "Il fermente ce que nous digérons mal."),
    qcm("Stress prolongé et alimentation pauvre en fibres peuvent…", "Appauvrir le microbiote", ["Le rendre automatiquement parfait", "Créer du glycogène", "Supprimer le côlon"], "Le mode de vie influence l'écosystème."),
    qcm("Un microbiote varié est associé à…", "Une meilleure santé digestive", ["Moins de besoin d'eau", "Plus d'ultra-transformés", "Une digestion bloquée"], "La diversité augmente la résilience."),
    qcm("Les probiotiques peuvent aider parfois, mais la base reste…", "Une alimentation variée", ["Un seul complément", "Zéro légume", "Uniquement du sucre"], "Le quotidien nourrit le microbiote."),
    tf("Toutes les bactéries intestinales sont dangereuses.", false, "Faux : beaucoup sont utiles ou neutres."),
    tf("Les fibres servent de nourriture à certaines bactéries.", true, "Vrai : c'est l'effet prébiotique."),
    tf("La diversité alimentaire peut soutenir la diversité microbienne.", true, "Vrai : plus de substrats différents."),
    tf("Un régime très pauvre en fibres peut appauvrir le microbiote.", true, "Vrai : il manque de carburant."),
    multi("Quels éléments soutiennent le microbiote ?", ["Fibres", "Diversité alimentaire", "Légumes variés"], ["Zéro végétal"], "La variété nourrit l'écosystème."),
    multi("Quels facteurs peuvent le perturber ?", ["Stress prolongé", "Antibiotiques", "Très peu de fibres"], ["Légumes variés"], "Plusieurs contraintes réduisent la diversité."),
    order("Remets l'effet prébiotique dans l'ordre.", ["Fibres consommées", "Bactéries nourries", "Microbiote soutenu"], "Les fibres servent de substrat."),
    order("Remets une stratégie diversité dans l'ordre.", ["Varier les végétaux", "Apporter plusieurs fibres", "Nourrir différents microbes"], "La diversité de l'assiette compte."),
    match("Associe terme et définition.", [["Microbiote", "Écosystème bactérien"], ["Prébiotiques", "Fibres nourricières"], ["Côlon", "Zone riche en bactéries"]], "Les notions sont liées."),
    match("Associe facteur et effet probable.", [["Variété", "Diversité"], ["Stress chronique", "Perturbation"], ["Fibres", "Nourriture bactérienne"]], "Le microbiote répond au mode de vie."),
    qcm("Acheter un probiotique sans changer l'assiette est limité car…", "Les bactéries ont besoin de substrats", ["Les fibres sont inutiles", "Le côlon n'existe pas", "Le stress aide toujours"], "Il faut nourrir l'écosystème."),
    qcm("La vision la plus juste du microbiote est…", "Un partenaire influencé par tes habitudes", ["Un ennemi à éliminer", "Un muscle à entraîner directement", "Un organe sans lien avec l'alimentation"], "Il évolue avec l'alimentation et le stress."),
  ),
  quiz20(
    qcm("La fermentation intestinale est réalisée surtout par…", "Les bactéries du microbiote", ["Les os", "Les poumons", "Les biceps"], "Les microbes fermentent certaines fibres."),
    qcm("Elle se produit surtout dans…", "Le côlon", ["La bouche uniquement", "Le tibia", "La peau"], "Le côlon abrite le microbiote dense."),
    qcm("La fermentation produit notamment…", "Des AGCC", ["Du glycogène musculaire", "De l'oxygène pur", "Des os"], "AGCC = acides gras à chaîne courte."),
    qcm("Les AGCC peuvent nourrir…", "Les cellules de la paroi intestinale", ["Les cheveux uniquement", "Les chaussures", "L'air inspiré"], "Le butyrate est un carburant du côlon."),
    qcm("Un peu de gaz après fibres est…", "Normal", ["Toujours dangereux", "Impossible", "Un signe de muscle"], "Fermentation = gaz modérés possibles."),
    qcm("Trop de fibres d'un coup peut causer…", "Ballonnements", ["Plus de force instantanée", "Absence de fermentation", "Moins de bactéries toujours"], "Le microbiote doit s'adapter."),
    qcm("La progression des fibres sert à…", "Limiter l'inconfort", ["Éliminer tous les gaz", "Bloquer les AGCC", "Supprimer l'eau"], "On laisse le temps d'adaptation."),
    qcm("AGCC signifie…", "Acides gras à chaîne courte", ["Acides glucidiques très courts", "Apports gras sans calories", "Absorption générale du calcium"], "C'est le nom des produits utiles."),
    tf("La fermentation intestinale est toujours nocive.", false, "Faux : elle produit aussi des composés utiles."),
    tf("Les gaz peuvent être une conséquence normale de la fermentation.", true, "Vrai : surtout avec certaines fibres."),
    tf("Les AGCC soutiennent la paroi intestinale.", true, "Vrai : ils nourrissent les cellules du côlon."),
    tf("Augmenter les fibres progressivement peut réduire l'inconfort.", true, "Vrai : le microbiote s'adapte."),
    multi("Quels produits viennent de la fermentation ?", ["AGCC", "Gaz"], ["Glycogène musculaire", "Oxygène pur"], "Fermentation = composés utiles et gaz."),
    multi("Quels comportements limitent les ballonnements ?", ["Progression", "Variété", "Eau suffisante"], ["Hausse brutale"], "L'adaptation réduit l'inconfort."),
    order("Remets la fermentation dans l'ordre.", ["Fibres arrivent au côlon", "Bactéries fermentent", "AGCC produits"], "Les bactéries transforment les fibres."),
    order("Remets l'adaptation dans l'ordre.", ["Petite hausse de fibres", "Microbiote s'adapte", "Confort amélioré"], "La régularité aide."),
    match("Associe terme et rôle.", [["AGCC", "Nourrissent la paroi"], ["Gaz", "Effet normal"], ["Microbiote", "Fermentation"]], "Ces effets vont ensemble."),
    match("Associe situation et conseil.", [["Ballonnements", "Augmenter plus doucement"], ["Peu de fibres", "Ajouter progressivement"], ["Confort correct", "Maintenir la variété"]], "Le dosage dépend du ressenti."),
    qcm("Avoir des gaz après plus de légumineuses ne signifie pas forcément…", "Un problème grave", ["Une fermentation", "Une adaptation en cours", "Un besoin de progression"], "Un peu de gaz est physiologique."),
    qcm("La bonne nuance sur la fermentation est qu'elle…", "Est utile mais dose-dépendante", ["Doit être supprimée", "Remplace toutes les enzymes", "N'existe que chez les sportifs"], "Trop vite gêne, progressivement aide."),
  ),
  quiz20(
    qcm("Une bonne santé digestive repose surtout sur…", "Variété, eau et mouvement", ["Zéro fibres", "Alcool et stress", "Repas ultra-rapides"], "Les bases sont simples."),
    qcm("Les ultra-transformés peuvent gêner car ils sont souvent…", "Pauvres en fibres", ["Trop riches en villosités", "Sans calories", "Toujours probiotiques"], "Ils remplacent souvent les végétaux."),
    qcm("Le stress chronique peut agir sur…", "L'axe intestin-cerveau", ["La longueur du fémur", "La couleur du glucose", "Le nombre de dents"], "Stress et digestion communiquent."),
    qcm("Le confort digestif en séance aide surtout…", "Le focus et la performance ressentie", ["À remplacer l'échauffement", "À supprimer le sommeil", "À créer du muscle sans effort"], "Moins de gêne = meilleure séance."),
    qcm("Manger trop vite peut diminuer…", "Le confort digestif", ["La gravité", "La teneur en protéines", "La présence d'eau"], "La mastication prépare la digestion."),
    qcm("L'eau soutient la digestion car elle aide…", "Le transit et les selles", ["La formation d'alcool", "La suppression des fibres", "Le stockage d'air"], "Hydratation et transit sont liés."),
    qcm("La variété alimentaire apporte…", "Différents types de fibres et micronutriments", ["Un seul nutriment", "Aucune fibre", "Uniquement des calories vides"], "Elle soutient l'intestin."),
    qcm("Une digestion saine n'est pas…", "Un détail secondaire", ["Utile au quotidien", "Liée au confort", "Influencée par l'eau"], "Elle influence l'énergie et les séances."),
    tf("Le mouvement régulier soutient le confort intestinal.", true, "Vrai : il stimule la motricité."),
    tf("Le stress peut aggraver certains inconforts digestifs.", true, "Vrai : l'axe intestin-cerveau est réel."),
    tf("Les ultra-transformés remplacent parfaitement les fibres.", false, "Faux : ils en apportent souvent peu."),
    tf("Le confort digestif peut influencer une séance.", true, "Vrai : ballonnements et crampes gênent."),
    multi("Quels piliers soutiennent la santé digestive ?", ["Variété alimentaire", "Eau", "Mouvement"], ["Stress chronique"], "Ce sont les bases durables."),
    multi("Quels facteurs peuvent dégrader le confort ?", ["Repas ultra-transformés fréquents", "Stress", "Manque d'eau"], ["Marche régulière"], "Ces facteurs pèsent sur l'intestin."),
    order("Remets une routine digestive simple dans l'ordre.", ["Varier l'assiette", "Boire régulièrement", "Bouger chaque jour"], "Les habitudes se renforcent."),
    order("Remets l'effet stress dans l'ordre.", ["Stress prolongé", "Axe intestin-cerveau activé", "Confort perturbé"], "Le cerveau influence l'intestin."),
    match("Associe pilier et effet.", [["Eau", "Transit"], ["Mouvement", "Motricité"], ["Variété", "Microbiote"]], "Les piliers couvrent plusieurs mécanismes."),
    match("Associe facteur et risque.", [["Ultra-transformés", "Peu de fibres"], ["Stress", "Inconfort"], ["Manger vite", "Mastication faible"]], "Les habitudes changent le confort."),
    qcm("Avant une séance, optimiser la digestion signifie surtout…", "Éviter les repas trop lourds et trop rapides", ["Chercher l'aliment parfait", "Supprimer toute fibre à vie", "Boire zéro eau"], "Le confort dépend du timing et du volume."),
    qcm("La meilleure approche long terme est…", "Des bases régulières plutôt qu'un remède miracle", ["Un complément unique", "Zéro variété", "Ignorer les symptômes"], "La santé digestive répond aux habitudes."),
  ),
];
