import type { SeedQuestion } from "../anatomie-quiz-helpers";
import { qcm, tf, multi, order, match } from "../anatomie-quiz-helpers";
import { quiz20 } from "./quiz-bank";

export const THEME_6_QUIZZES: SeedQuestion[][] = [
  quiz20(
    qcm("Sur une étiquette, pourquoi comparer aussi pour 100 g ?", "Pour comparer deux produits à quantité égale", ["Pour connaître le prix exact", "Pour éviter de lire les ingrédients", "Parce que la portion est toujours identique"], "100 g standardise la comparaison."),
    qcm("La colonne « par portion » sert surtout à estimer…", "Ce que tu manges réellement", ["La composition de tout le rayon", "La qualité des additifs", "Le Nutri-Score seul"], "La portion traduit l'apport pratique."),
    qcm("Les macros indiquées regroupent surtout…", "Glucides, lipides et protéines", ["Vitamines, eau et additifs", "Sel, arômes et conservateurs", "Fibres, fer et calcium seuls"], "Ce sont les grands fournisseurs d'énergie."),
    qcm("Si une portion fait 50 g, la valeur pour 100 g est…", "Deux fois la portion", ["La moitié de la portion", "Toujours identique", "Impossible à relier"], "100 g = deux portions de 50 g."),
    qcm("Le Nutri-Score est utile mais limité car il…", "Ne résume pas tout le contexte alimentaire", ["Mesure la force musculaire", "Liste tous les allergènes", "Remplace les quantités mangées"], "C'est un repère, pas une analyse complète."),
    qcm("Pour choisir entre deux céréales, le plus solide est de comparer…", "Sucre, fibres et énergie pour 100 g", ["La taille du paquet seule", "La couleur du logo", "Le nom le plus sportif"], "Comparer les chiffres utiles évite le marketing."),
    qcm("Les protéines sur l'étiquette sont exprimées en général en…", "Grammes", ["Millilitres", "Degrés", "Scores de satiété"], "Les macros sont indiquées en grammes."),
    qcm("Une portion indiquée par la marque peut être…", "Plus petite que la portion vraiment servie", ["Toujours exacte pour tout le monde", "Obligatoirement 100 g", "Sans calories"], "Les portions marketing peuvent sous-estimer l'assiette."),
    tf("Lire seulement la face avant du paquet suffit pour juger un aliment.", false, "Le dos contient les valeurs et ingrédients."),
    tf("La valeur pour 100 g aide à comparer deux produits de tailles différentes.", true, "Même base, comparaison plus juste."),
    tf("Le Nutri-Score ne dit pas si une portion est adaptée à ton objectif.", true, "La quantité reste à gérer."),
    tf("Les glucides, lipides et protéines apportent tous exactement les mêmes calories par gramme.", false, "Lipides environ 9 kcal/g, glucides et protéines environ 4."),
    multi("À vérifier sur une étiquette complète :", ["Valeurs pour 100 g", "Liste d'ingrédients"], ["Photo du paquet", "Police du logo"], "Le fond est au dos du paquet."),
    multi("Signes utiles pour comparer deux snacks :", ["Calories pour 100 g", "Protéines et fibres"], ["Nom « fitness »", "Couleur verte seule"], "Les chiffres comptent plus que l'allégation."),
    order("Comparer deux produits emballés", ["Regarder pour 100 g", "Comparer macros et fibres", "Ramener à sa portion réelle"], "Standardiser, lire, puis adapter."),
    order("Estimer l'apport d'un bol de céréales", ["Peser ou estimer le bol", "Lire les valeurs par 100 g", "Calculer selon la quantité servie"], "La portion réelle change le total."),
    match("Associe l'élément à son rôle", [["100 g", "Comparer"], ["Portion", "Estimer son assiette"], ["Nutri-Score", "Repère rapide"]], "Chaque info a un usage précis."),
    match("Associe macro et énergie approximative", [["Glucides", "4 kcal/g"], ["Protéines", "4 kcal/g"], ["Lipides", "9 kcal/g"]], "Les lipides sont plus denses."),
    qcm("Réflexion : un produit Nutri-Score A peut quand même poser problème si…", "La portion consommée est énorme", ["Il contient des protéines", "Il affiche les valeurs pour 100 g", "Il a une liste d'ingrédients"], "La dose fait aussi le résultat."),
    qcm("Réflexion : pour une sèche, l'étiquette aide surtout à…", "Relier calories, satiété et portion", ["Éliminer tous les glucides", "Choisir le paquet le plus cher", "Ignorer les fibres"], "Le but est de tenir le déficit sans faim excessive."),
  ),
  quiz20(
    qcm("Dans une liste d'ingrédients, le premier ingrédient est…", "Le plus présent en poids", ["Le plus sain", "Le plus cher", "Le plus calorique forcément"], "L'ordre est décroissant."),
    qcm("Un additif noté E suivi d'un nombre est…", "Un additif autorisé identifié", ["Une vitamine obligatoire", "Un allergène certain", "Une dose de protéines"], "E indique une codification européenne."),
    qcm("Les allergènes sont souvent indiqués…", "En gras ou dans une mention dédiée", ["Uniquement sur la face avant", "Par une couleur Nutri-Score", "Jamais sur les produits emballés"], "Ils doivent être clairement repérables."),
    qcm("« Light » signifie surtout…", "Allégé sur un critère précis", ["Toujours sain", "Sans calories", "Plus riche en fibres"], "Il faut regarder en quoi c'est allégé."),
    qcm("Si sucre, sirop de glucose et miel apparaissent tôt, cela suggère…", "Beaucoup de sucres ajoutés", ["Une absence de glucides", "Un produit forcément riche en protéines", "Un aliment brut"], "Plusieurs noms peuvent additionner les sucres."),
    qcm("Une liste très longue avec beaucoup d'arômes et additifs indique souvent…", "Un produit très transformé", ["Un aliment toujours meilleur", "Un produit sans sel", "Un fruit entier"], "Long ne veut pas toujours dire mauvais, mais signale une transformation."),
    qcm("Pour une personne allergique, le plus important est de lire…", "La mention d'allergènes", ["Le slogan", "Le prix au kilo seul", "Le dessin du paquet"], "La sécurité passe avant les macros."),
    qcm("Un ingrédient « huile végétale » sans précision est…", "Moins informatif qu'une huile nommée", ["Toujours de l'huile d'olive", "Un allergène obligatoire", "Une protéine"], "La précision aide à juger la qualité."),
    tf("Les ingrédients sont listés du plus au moins présent.", true, "C'est la règle de lecture."),
    tf("Tous les additifs sont automatiquement dangereux.", false, "Le risque dépend du composé et de la dose."),
    tf("Un produit light peut rester très sucré ou très salé.", true, "Allégé ne veut pas dire équilibré."),
    tf("Les allergènes ne concernent que les produits laitiers.", false, "Gluten, arachide, soja, fruits à coque, etc."),
    multi("Indices d'un produit très transformé :", ["Liste très longue", "Nombreux arômes/additifs"], ["Un seul ingrédient", "Légume brut"], "Plus il y a d'étapes, plus la vigilance monte."),
    multi("À regarder avant d'acheter un produit « light » :", ["Sur quoi porte l'allègement", "Sucres, sel et calories"], ["La promesse seule", "La photo de silhouette"], "Le détail compte."),
    order("Lire une liste d'ingrédients", ["Repérer les premiers ingrédients", "Chercher sucres/gras/sel cachés", "Vérifier allergènes et additifs"], "L'ordre donne déjà beaucoup d'information."),
    order("Évaluer un produit « protéiné »", ["Lire la quantité de protéines", "Comparer sucre et calories", "Décider selon ton objectif"], "Le mot protéiné ne suffit pas."),
    match("Associe mention et sens", [["E300", "Additif codé"], ["En gras", "Allergène possible"], ["Light", "Allégé sur un critère"]], "Les mentions ont des rôles différents."),
    match("Associe ingrédient et vigilance", [["Sirop de glucose", "Sucre ajouté"], ["Huile hydrogénée", "Graisse à limiter"], ["Arachide", "Allergène"]], "Identifier les familles aide."),
    qcm("Réflexion : un biscuit « sans sucre ajouté » peut quand même apporter beaucoup de calories via…", "Les farines et les graisses", ["L'eau", "Les vitamines", "L'air dans le paquet"], "Sans sucre ajouté ne veut pas dire sans énergie."),
    qcm("Réflexion : la meilleure réaction face à une longue liste d'ingrédients est de…", "Lire les premiers éléments et les points sensibles", ["Jeter sans réfléchir", "Croire le slogan", "Ignorer les allergènes"], "Nuance : on vérifie, puis on décide."),
  ),
  quiz20(
    qcm("La densité énergétique correspond aux…", "Calories par volume ou poids d'aliment", ["Protéines par muscle", "Vitamines par euro", "Fibres par minute"], "Elle relie énergie et quantité visible."),
    qcm("Les lipides sont denses car ils apportent environ…", "9 kcal par gramme", ["1 kcal par gramme", "4 kcal par litre", "0 kcal"], "Ils concentrent beaucoup d'énergie."),
    qcm("Les légumes non frits ont souvent une densité énergétique…", "Basse", ["Très haute", "Identique à l'huile", "Nulle en nutriments"], "Beaucoup d'eau et fibres, peu de calories."),
    qcm("En sèche, choisir des aliments peu denses peut aider à…", "Manger plus de volume pour moins de calories", ["Supprimer la faim à vie", "Créer du muscle sans protéines", "Éviter toute planification"], "Volume et fibres soutiennent la satiété."),
    qcm("Les fruits secs sont plus denses que les fruits frais car ils contiennent moins…", "D'eau", ["De glucides", "De minéraux", "De goût"], "Retirer l'eau concentre les calories."),
    qcm("Une poignée de noix est saine mais peut être dense à cause des…", "Lipides", ["Fibres insolubles seules", "Vitamines B", "Arômes naturels"], "Qualité et calories sont deux sujets."),
    qcm("À masse égale, l'huile apporte généralement plus de calories que…", "Des courgettes", ["Du beurre de cacahuète", "Des noix", "Du chocolat"], "L'huile est presque pur lipide."),
    qcm("En prise de masse, les aliments plus denses peuvent aider quand…", "L'appétit limite l'apport", ["On veut perdre du poids vite", "On doit boire moins d'eau", "On évite les protéines"], "Plus d'énergie dans moins de volume."),
    tf("Densité énergétique élevée signifie toujours mauvais aliment.", false, "Tout dépend de la dose et du contexte."),
    tf("L'eau et les fibres baissent souvent la densité énergétique.", true, "Elles ajoutent du volume avec peu d'énergie."),
    tf("Un aliment sec peut devenir plus calorique par 100 g qu'une version fraîche.", true, "Moins d'eau = énergie concentrée."),
    tf("Les légumes sont toujours caloriques dès qu'ils sont verts.", false, "La plupart sont peu denses hors friture/sauce."),
    multi("Aliments souvent peu denses :", ["Légumes", "Soupes riches en légumes"], ["Huile", "Chips"], "Eau et volume font la différence."),
    multi("Aliments utiles mais denses :", ["Noix", "Huile d'olive"], ["Concombre", "Salade nature"], "Ils peuvent être bons, mais à doser."),
    order("Utiliser la densité en sèche", ["Choisir une base volumineuse", "Ajouter protéines et fibres", "Doser les aliments denses"], "On garde la satiété sans exploser les calories."),
    order("Composer un snack de prise de masse", ["Choisir une base digeste", "Ajouter une source dense", "Vérifier la tolérance digestive"], "Surplus oui, inconfort non."),
    match("Associe aliment et densité typique", [["Huile", "Très dense"], ["Légumes", "Peu dense"], ["Fruits secs", "Plus dense que frais"]], "L'eau change beaucoup la densité."),
    match("Associe objectif et stratégie", [["Sèche", "Volume peu calorique"], ["Masse", "Énergie facile"], ["Maintien", "Portions stables"]], "La densité se pilote selon le but."),
    qcm("Réflexion : en sèche, une salade devient vite dense si on ajoute beaucoup…", "D'huile et de noix", ["De concombre", "De laitue", "D'eau"], "Les ajouts gras changent le bilan."),
    qcm("Réflexion : en prise de masse, forcer uniquement des légumes très volumineux peut…", "Rendre le surplus difficile à atteindre", ["Garantir plus de muscle", "Supprimer le besoin de protéines", "Augmenter les calories sans limite"], "Trop de volume peut bloquer l'appétit."),
  ),
  quiz20(
    qcm("La portion indiquée sur un paquet est…", "Une référence, pas forcément ta portion", ["Toujours ce que tu manges", "Toujours 100 g", "Une valeur médicale"], "Elle peut être plus petite que le service réel."),
    qcm("Si tu doubles la portion d'un aliment, tu doubles aussi…", "Calories et macros", ["Uniquement les protéines", "Le Nutri-Score", "Les allergènes"], "Deux fois la quantité = deux fois l'apport."),
    qcm("Peser quelques fois un aliment sert surtout à…", "Calibrer son estimation visuelle", ["Peser toute sa vie obligatoirement", "Changer sa valeur nutritionnelle", "Réduire les calories"], "C'est un apprentissage pratique."),
    qcm("Au restaurant, les portions sont souvent…", "Plus difficiles à estimer", ["Toujours identiques à l'étiquette", "Sans matières grasses", "Mesurées au gramme près"], "Sauces et quantités sont moins visibles."),
    qcm("Une portion réelle plus grande que celle indiquée signifie…", "Un apport réel plus élevé", ["Une baisse des calories", "Un produit plus sain", "Un changement d'ingrédients"], "La quantité pilote le total."),
    qcm("Pour le riz ou les pâtes, il faut préciser si le poids est…", "Cru ou cuit", ["Bio ou non", "Dans une assiette blanche", "Mangé le soir"], "L'eau de cuisson change le poids."),
    qcm("Une cuillère d'huile versée au hasard peut ajouter vite…", "Beaucoup de calories", ["Beaucoup de protéines", "Du calcium", "Zéro énergie"], "L'huile est très dense."),
    qcm("Le meilleur usage du pesage est souvent…", "Temporaire et éducatif", ["Punitif", "Réservé aux athlètes pros", "Inutile pour tout le monde"], "Quelques repères suffisent souvent."),
    tf("Doubler une portion double aussi le sel indiqué pour cette portion.", true, "Même logique pour tous les nutriments."),
    tf("La portion du paquet est toujours adaptée à ton objectif.", false, "Objectif, faim et contexte comptent."),
    tf("Au restaurant, les sauces peuvent changer fortement le total calorique.", true, "Elles sont souvent riches en graisses/sucre."),
    tf("Peser un aliment modifie ses calories.", false, "Le pesage mesure, il ne transforme pas."),
    multi("Pour mieux estimer ses portions :", ["Peser quelques repas types", "Comparer cru/cuit"], ["Changer d'assiette à chaque bouchée", "Ignorer les huiles"], "Les repères concrets aident."),
    multi("Au restaurant, points à surveiller :", ["Sauces et huiles", "Taille réelle de l'assiette"], ["Police du menu", "Couleur des serviettes"], "L'invisible peut compter."),
    order("Calibrer une portion maison", ["Servir comme d'habitude", "Peser la quantité", "Comparer aux valeurs nutritionnelles"], "On apprend sur sa vraie assiette."),
    order("Gérer un repas au restaurant", ["Choisir une base cohérente", "Identifier sauces et fritures", "Ajuster les autres repas si besoin"], "Flexibilité sans perdre le cap."),
    match("Associe situation et réflexe", [["Pâtes", "Cru ou cuit"], ["Huile", "Doser"], ["Restaurant", "Estimer avec marge"]], "Chaque cas a son piège."),
    match("Associe changement et effet", [["Portion doublée", "Calories doublées"], ["Sauce ajoutée", "Apport parfois élevé"], ["Pesage", "Meilleure estimation"]], "La quantité reste centrale."),
    qcm("Réflexion : si ton poids stagne malgré un déficit prévu, une cause fréquente est…", "Des portions sous-estimées", ["Trop d'eau dans les légumes", "Un Nutri-Score trop bon", "Des protéines notées en grammes"], "Les petites erreurs répétées s'additionnent."),
    qcm("Réflexion : pour rester sociable au restaurant, la stratégie la plus réaliste est de…", "Estimer et ajuster sans obsession", ["Tout annuler", "Ne manger que du pain", "Ignorer totalement l'objectif"], "La constance tolère de l'approximation."),
  ),
  quiz20(
    qcm("Les sucres ajoutés sont des sucres…", "Ajoutés pendant fabrication ou préparation", ["Présents naturellement dans un fruit entier", "Toujours sans calories", "Uniquement salés"], "Ils ne viennent pas seulement de la matrice naturelle."),
    qcm("Les sucres naturels d'un fruit entier arrivent avec…", "Fibres, eau et micronutriments", ["Trans gras", "Sodium pur", "Alcool"], "La matrice alimentaire change l'effet."),
    qcm("Sur l'étiquette, « dont sucres » indique…", "La part de sucres dans les glucides", ["Les protéines cachées", "Le sel ajouté", "Les calories des lipides"], "C'est une sous-ligne des glucides."),
    qcm("Un soda classique de 250 ml peut apporter environ…", "20 à 30 g de sucres", ["1 g de protéines", "0 kcal garanties", "100 g de fibres"], "Les boissons sucrées montent vite."),
    qcm("Un nom caché de sucre peut être…", "Sirop de glucose-fructose", ["Sel iodé", "Eau gazeuse", "Huile de colza"], "Les sucres ont plusieurs noms."),
    qcm("Le miel reste nutritionnellement…", "Une source de sucres", ["Une protéine complète", "Un aliment sans énergie", "Un substitut de légumes"], "Naturel ne veut pas dire illimité."),
    qcm("Réduire les boissons sucrées aide souvent car elles…", "Rassasient peu pour leurs calories", ["Apportent beaucoup de fibres", "Suppriment la soif durablement", "Sont sans glucides"], "Les calories liquides passent facilement."),
    qcm("Un yaourt aux fruits sucré peut contenir…", "Des sucres ajoutés en plus du lactose", ["Seulement de l'eau", "Des lipides trans obligatoires", "Zéro glucide"], "Lait + sucre ajouté peuvent s'additionner."),
    tf("Tous les sucres d'une pomme entière sont des sucres ajoutés.", false, "Ils sont naturellement présents."),
    tf("« Dont sucres » ne distingue pas toujours clairement ajouté et naturel.", true, "Il donne le total des sucres."),
    tf("Les boissons sucrées peuvent rendre le déficit calorique plus difficile.", true, "Elles rassasient peu."),
    tf("Le sirop d'agave n'apporte aucune calorie car il est naturel.", false, "Il reste riche en sucres."),
    multi("Noms possibles de sucres ajoutés :", ["Dextrose", "Sirop de glucose"], ["Sel", "Fibres"], "La liste d'ingrédients révèle les ajouts."),
    multi("Sources à limiter si l'objectif est le contrôle calorique :", ["Sodas", "Confiseries"], ["Fruits entiers", "Légumineuses nature"], "On cible surtout les sucres ajoutés peu rassasiants."),
    order("Repérer les sucres d'un produit", ["Lire les glucides", "Regarder « dont sucres »", "Chercher les noms de sucre dans les ingrédients"], "Valeurs + ingrédients se complètent."),
    order("Réduire progressivement les boissons sucrées", ["Mesurer la fréquence actuelle", "Remplacer une partie par eau ou zéro", "Garder les exceptions choisies"], "La progression tient mieux."),
    match("Associe terme et catégorie", [["Fructose du fruit entier", "Naturel"], ["Sirop de glucose", "Ajouté"], ["Dont sucres", "Indication totale"]], "Le contexte du sucre compte."),
    match("Associe produit et vigilance", [["Soda", "20-30 g possibles"], ["Miel", "Sucre concentré"], ["Fruit entier", "Fibres + eau"]], "Même goût sucré, effets différents."),
    qcm("Réflexion : remplacer un soda par un fruit entier change surtout…", "La satiété et la matrice alimentaire", ["La gravité terrestre", "La présence de protéines complètes", "Le besoin de dormir"], "Fibres et mastication comptent."),
    qcm("Réflexion : le bon objectif n'est pas zéro sucre, mais…", "Limiter les ajouts peu utiles et garder le contexte", ["Supprimer tous les fruits", "Boire seulement du jus", "Compter le sucre sans calories"], "Nuance : quantité, source et usage."),
  ),
  quiz20(
    qcm("Le sodium est un composant principal du…", "Sel", ["Sucre", "Glycogène", "Collagène"], "Sel de table = chlorure de sodium."),
    qcm("La recommandation OMS est d'environ moins de…", "5 g de sel par jour", ["50 g par jour", "0 g absolu", "5 kg par mois"], "Repère populationnel, pas diagnostic individuel."),
    qcm("Une grande partie du sel consommé vient souvent…", "Des produits transformés", ["De l'eau plate", "Des fruits frais", "Du riz nature non salé"], "Pain, charcuteries, plats préparés, sauces."),
    qcm("Un excès de sel peut favoriser chez certains…", "Tension artérielle plus élevée", ["Synthèse directe de muscle", "Perte de graisse locale", "Absence de soif"], "La sensibilité varie, mais le lien est solide."),
    qcm("Une hausse rapide de sel peut augmenter temporairement…", "La rétention d'eau", ["La masse osseuse", "Les fibres musculaires", "La vitamine C"], "Le corps ajuste l'eau et le sodium."),
    qcm("Pour cuisiner moins salé, on peut utiliser…", "Épices, herbes, ail ou citron", ["Plus de sucre seulement", "Aucun goût", "Uniquement friture"], "Aromates = goût sans tout miser sur le sel."),
    qcm("Sur une étiquette, il faut distinguer parfois…", "Sel et sodium", ["Protéines et fibres comme synonymes", "Calories et grammes d'eau", "Vitamines et additifs identiques"], "1 g sodium n'est pas 1 g de sel."),
    qcm("Les sportifs qui transpirent beaucoup peuvent avoir des besoins…", "Variables selon chaleur et durée", ["Toujours nuls", "Identiques en toute saison", "Sans rapport avec l'eau"], "Contexte d'entraînement important."),
    tf("Le sel est inutile au corps humain.", false, "Le sodium est nécessaire, l'excès pose problème."),
    tf("Les plats préparés peuvent contenir beaucoup de sel sans goût très salé.", true, "Le sel est souvent discret."),
    tf("Réduire le sel peut se faire en travaillant les épices.", true, "Le palais s'adapte."),
    tf("La recommandation de 5 g de sel par jour signifie 5 g de sodium pur.", false, "Sel et sodium ne sont pas équivalents."),
    multi("Sources fréquentes de sel caché :", ["Charcuteries", "Sauces industrielles"], ["Pomme nature", "Eau plate"], "Les transformés pèsent lourd."),
    multi("Aides pour moins saler :", ["Herbes et épices", "Citron ou vinaigre"], ["Doubler la sauce soja", "Ajouter du sel avant de goûter"], "On construit le goût autrement."),
    order("Réduire le sel d'un plat maison", ["Goûter avant de saler", "Ajouter épices et acidité", "Saler légèrement si besoin"], "On dose après avoir donné du goût."),
    order("Évaluer le sel d'une journée", ["Lire les étiquettes clés", "Repérer sauces/charcuteries", "Ajuster les repas suivants"], "Les gros contributeurs guident l'action."),
    match("Associe notion et effet", [["Sodium", "Composant du sel"], ["Excès chronique", "Tension possible"], ["Épices", "Goût sans sel"]], "Les leviers sont simples."),
    match("Associe aliment et vigilance sel", [["Sauce soja", "Très salée"], ["Plat préparé", "Sel caché"], ["Fruit frais", "Très faible"]], "Tout ne contribue pas pareil."),
    qcm("Réflexion : après un repas très salé, le poids du lendemain peut monter surtout par…", "Rétention d'eau", ["Gain de graisse immédiat", "Croissance osseuse", "Plus de fibres musculaires"], "Eau et glycogène bougent vite."),
    qcm("Réflexion : pour un hypertendu, la meilleure attitude est…", "Suivre l'avis médical et surveiller le sel", ["Prendre plus de sel sans contrôle", "Ignorer les étiquettes", "Remplacer les médicaments par des épices"], "Nutrition et soin médical se complètent."),
  ),
  quiz20(
    qcm("Les graisses saturées sont indiquées sur l'étiquette dans la ligne…", "Dont acides gras saturés", ["Dont protéines", "Dont vitamines", "Dont fibres insolubles"], "C'est la sous-ligne des lipides."),
    qcm("Les graisses insaturées se trouvent souvent dans…", "Huiles végétales, noix et poissons gras", ["Sodas", "Bonbons gélifiés", "Eau minérale"], "Sources courantes de lipides de meilleure qualité."),
    qcm("Les oméga-3 sont des graisses…", "Insaturées", ["Trans industrielles", "Sans calories", "Protéiques"], "Ils appartiennent aux acides gras polyinsaturés."),
    qcm("Les graisses trans industrielles sont à…", "Limiter fortement", ["Augmenter au maximum", "Confondre avec l'eau", "Chercher pour la performance"], "Elles sont défavorables au risque cardio."),
    qcm("Une huile hydrogénée peut signaler…", "Des graisses trans possibles", ["Des fibres ajoutées", "Une protéine végétale", "Un minéral"], "Hydrogénation = vigilance."),
    qcm("Le beurre est plutôt riche en…", "Graisses saturées", ["Oméga-3 uniquement", "Glucides complexes", "Fibres"], "À doser dans l'ensemble alimentaire."),
    qcm("La qualité des graisses dépend aussi de…", "La source et la quantité", ["La couleur du bouchon", "La taille du ticket", "Le nom anglais"], "On juge le pattern global."),
    qcm("Les poissons gras apportent notamment…", "EPA et DHA", ["Glucose pur", "Trans industriels", "Aucun lipide"], "Ce sont des oméga-3 marins."),
    tf("Toutes les graisses doivent être supprimées pour être en bonne santé.", false, "Elles sont nécessaires."),
    tf("L'étiquette distingue souvent lipides totaux et saturés.", true, "C'est une lecture importante."),
    tf("Les graisses trans industrielles sont une cible prioritaire de limitation.", true, "Consensus fort sur ce point."),
    tf("Les oméga-3 sont des protéines complètes.", false, "Ce sont des lipides."),
    multi("Sources utiles d'insaturés :", ["Noix", "Huile d'olive"], ["Soda", "Sucre blanc"], "Les plantes grasses et poissons aident."),
    multi("À limiter côté qualité des graisses :", ["Graisses trans", "Excès de saturées"], ["Oméga-3", "Lipides des noix en portion adaptée"], "La qualité n'est pas tout ou rien."),
    order("Lire les graisses d'une étiquette", ["Regarder les lipides totaux", "Lire les saturés", "Chercher huiles hydrogénées si besoin"], "Total, qualité, ingrédients."),
    order("Améliorer son profil de graisses", ["Réduire trans et fritures fréquentes", "Doser saturés", "Ajouter sources insaturées"], "On remplace plus qu'on interdit."),
    match("Associe graisse et source", [["Oméga-3", "Poissons gras"], ["Saturées", "Beurre"], ["Insaturées", "Huile d'olive"]], "Les sources guident les choix."),
    match("Associe mention et action", [["Dont saturés", "Surveiller"], ["Hydrogénée", "Vigilance trans"], ["Noix", "Doser mais utile"]], "La lecture devient pratique."),
    qcm("Réflexion : une huile d'olive reste à doser car…", "Elle est très calorique", ["Elle ne contient aucun lipide", "Elle est toujours toxique", "Elle remplace les protéines"], "Bonne qualité ne veut pas dire calories nulles."),
    qcm("Réflexion : le meilleur message sur les graisses est…", "Choisir de bonnes sources et gérer les quantités", ["Tout supprimer", "Manger uniquement du beurre", "Ignorer les saturés"], "Nuance : qualité et dose."),
  ),
  quiz20(
    qcm("Le marketing alimentaire met souvent en avant…", "Une promesse simple en face avant", ["Toute la liste d'ingrédients", "Le détail du sodium", "Les limites du produit"], "La face avant vend, le dos informe."),
    qcm("Un produit « protéiné » peut rester…", "Très sucré ou très calorique", ["Sans énergie", "Toujours meilleur", "Sans ingrédients"], "Il faut lire les valeurs."),
    qcm("Le mot « fitness » sur un paquet signifie…", "Une allégation marketing non suffisante", ["Un aliment médical", "Zéro sucre", "Un déficit garanti"], "Le mot ne remplace pas l'analyse."),
    qcm("La meilleure source d'information est souvent…", "Le dos du paquet", ["La mascotte", "Le slogan", "La couleur verte"], "Valeurs et ingrédients y sont."),
    qcm("Une allégation nutritionnelle porte généralement sur…", "Un aspect précis du produit", ["Tous les effets santé possibles", "Ta dépense calorique", "Ton sommeil"], "Riche en fibres, réduit en sucre, etc."),
    qcm("« Sans gluten » est essentiel pour certains, mais ne signifie pas…", "Automatiquement plus sain", ["Adapté aux coeliaques", "Une information de composition", "Sans blé dans certains cas"], "Utile médicalement, pas label minceur."),
    qcm("Un packaging vert peut suggérer santé mais…", "Ne prouve rien seul", ["Garantit 30 g de protéines", "Réduit les calories", "Supprime le sel"], "Le design influence la perception."),
    qcm("Pour déjouer le marketing, il faut comparer…", "Promesse, valeurs et ingrédients", ["Deux mascottes", "La taille des photos", "Le bruit du paquet"], "On confronte le discours aux données."),
    tf("La face avant du paquet est conçue pour vendre.", true, "Elle sélectionne les infos favorables."),
    tf("Un produit « naturel » est toujours adapté à tous les objectifs.", false, "Naturel ne dit ni dose ni calories."),
    tf("Les allégations peuvent être vraies mais incomplètes.", true, "Elles ciblent un point précis."),
    tf("Lire le dos du paquet aide à vérifier une promesse marketing.", true, "C'est le réflexe clé."),
    multi("Promesses à vérifier au dos :", ["Light", "Protéiné"], ["Code-barres", "Forme du paquet"], "Les mots vendeurs doivent être contrôlés."),
    multi("Données qui contredisent parfois le marketing :", ["Sucres élevés", "Calories élevées"], ["Logo bleu", "Photo appétissante"], "Les chiffres tranchent."),
    order("Analyser une allégation", ["Lire la promesse", "Vérifier valeurs et ingrédients", "Comparer à un produit simple"], "La comparaison calme l'effet marketing."),
    order("Choisir une barre « fitness »", ["Lire calories et protéines", "Regarder sucres et graisses", "Décider selon faim et objectif"], "Pas de verdict sans contexte."),
    match("Associe mot marketing et vérification", [["Light", "Calories/sucres/gras"], ["Protéiné", "Grammes de protéines"], ["Naturel", "Ingrédients et portion"]], "Chaque promesse se teste."),
    match("Associe zone du paquet et rôle", [["Face avant", "Attirer"], ["Dos", "Informer"], ["Allégation", "Mettre un point en avant"]], "Le design et l'information n'ont pas le même but."),
    qcm("Réflexion : deux produits « fitness » peuvent être très différents surtout par…", "Leurs calories, sucres et protéines réels", ["Leur couleur", "Leur nom anglais", "La taille de l'image"], "Les données battent l'impression."),
    qcm("Réflexion : l'attitude la plus fiable face aux slogans est de…", "Vérifier sans devenir parano", ["Croire tout", "Refuser tout emballage", "Ne lire que la face avant"], "Esprit critique, pas obsession."),
  ),
];
