import type { SeedQuestion } from "../anatomie-quiz-helpers";
import { qcm, tf, multi, order, match } from "../anatomie-quiz-helpers";
import { quiz20 } from "./quiz-bank";

export const THEME_7_QUIZZES: SeedQuestion[][] = [
  quiz20(
    qcm("Pour perdre du poids, le levier principal est…", "Un déficit calorique", ["Un surplus massif", "Supprimer l'eau", "Manger uniquement le soir"], "La perte de masse grasse demande une balance énergétique négative."),
    qcm("Un déficit modéré réaliste se situe souvent autour de…", "10 à 20 % des besoins", ["80 à 90 % des besoins", "0 % exactement", "200 % des besoins"], "Modéré = plus tenable et moins risqué."),
    qcm("En perte de poids, les protéines aident surtout à…", "Préserver la masse musculaire", ["Remplacer le sommeil", "Annuler toutes les calories", "Bloquer la digestion"], "Avec musculation, elles protègent mieux le muscle."),
    qcm("La musculation pendant une sèche sert à…", "Envoyer un signal de maintien musculaire", ["Transformer la graisse en muscle", "Supprimer le besoin de déficit", "Faire disparaître la faim"], "Le corps garde mieux ce qui est utilisé."),
    qcm("Les fibres sont utiles en déficit car elles augmentent…", "La satiété", ["La densité calorique", "Les trans industriels", "La déshydratation"], "Elles ajoutent volume et ralentissent la digestion."),
    qcm("La tendance de poids se juge plutôt sur…", "Plusieurs semaines", ["Une seule pesée", "Une heure après le repas", "La couleur de l'assiette"], "Eau, sel et glycogène brouillent le quotidien."),
    qcm("Un déficit trop agressif augmente le risque de…", "Faim, fatigue et perte de muscle", ["Croissance musculaire optimale", "Hydratation parfaite", "Digestion toujours meilleure"], "Plus vite n'est pas toujours mieux."),
    qcm("Pour rendre la perte durable, il vaut mieux viser…", "Des habitudes répétables", ["Une interdiction totale de tout plaisir", "Un régime de trois jours", "Un seul aliment miracle"], "L'adhérence gagne sur la perfection."),
    tf("Un déficit calorique est nécessaire pour perdre de la graisse.", true, "C'est la base physiologique."),
    tf("Une pesée isolée suffit à conclure que le plan échoue.", false, "Il faut regarder la tendance."),
    tf("Protéines et musculation aident à limiter la perte de muscle.", true, "Le signal mécanique et les acides aminés se complètent."),
    tf("Les fibres sont inutiles si les calories sont contrôlées.", false, "Elles aident à tenir le contrôle."),
    multi("Priorités en perte de poids :", ["Déficit modéré", "Protéines suffisantes"], ["Surplus calorique", "Boissons sucrées illimitées"], "On protège l'adhérence et le muscle."),
    multi("Indicateurs plus fiables qu'une seule pesée :", ["Moyenne hebdomadaire", "Tour de taille"], ["Poids après un repas salé", "Humeur d'une journée"], "La tendance réduit le bruit."),
    order("Mettre en place une perte de poids", ["Estimer ses apports", "Créer un déficit modéré", "Suivre la tendance sur semaines"], "Mesurer, ajuster, patienter."),
    order("Limiter la faim en déficit", ["Construire une base protéinée", "Ajouter légumes et fibres", "Garder quelques aliments plaisir dosés"], "Tenir compte de la satiété aide."),
    match("Associe levier et rôle", [["Déficit", "Perte de graisse"], ["Protéines", "Maintien musculaire"], ["Fibres", "Satiété"]], "Chaque levier répond à un problème."),
    match("Associe signal et interprétation", [["Poids journalier", "Variable"], ["Moyenne semaines", "Tendance"], ["Déficit extrême", "Risque d'abandon"]], "Le contexte évite les conclusions rapides."),
    qcm("Réflexion : si la balance monte après un repas salé en sèche, le plus probable est…", "Une variation d'eau", ["Un gain massif de graisse", "Une absence de déficit certaine", "Une transformation du muscle"], "Le sel et les glucides modifient l'eau."),
    qcm("Réflexion : le meilleur déficit est celui qui…", "Fait progresser tout en restant tenable", ["Affame le plus possible", "Ignore l'entraînement", "Supprime toutes les sorties"], "Durable bat spectaculaire."),
  ),
  quiz20(
    qcm("Pour prendre de la masse, il faut généralement…", "Un surplus calorique", ["Un déficit constant", "Zéro glucide", "Moins de protéines"], "Construire du tissu demande énergie et entraînement."),
    qcm("Un surplus souvent conseillé est d'environ…", "200 à 500 kcal par jour", ["2000 à 5000 kcal par jour", "0 kcal toujours", "Uniquement 20 kcal par mois"], "Assez pour progresser, sans excès inutile."),
    qcm("Le muscle a un plafond de gain car…", "La synthèse musculaire est limitée", ["Les calories deviennent toutes du muscle", "Le sommeil est inutile", "Les protéines n'ont aucun rôle"], "Le surplus au-delà augmente surtout le gras."),
    qcm("Répartir les protéines sur la journée aide à…", "Stimuler plusieurs fois la synthèse musculaire", ["Éviter toute calorie", "Remplacer l'entraînement", "Supprimer la digestion"], "Plusieurs prises facilitent l'apport total."),
    qcm("Une prise de masse de qualité demande aussi…", "Une progression à l'entraînement", ["Uniquement manger plus", "Aucun repos", "Que des compléments"], "Le surplus sans stimulus construit peu de muscle."),
    qcm("La variété alimentaire en masse sert à…", "Couvrir micronutriments et digestion", ["Réduire toutes les calories", "Empêcher l'appétit", "Remplacer l'eau"], "Santé et performance soutiennent la progression."),
    qcm("Si le poids monte trop vite, il faut souvent…", "Réduire légèrement le surplus", ["Doubler encore les calories", "Arrêter les protéines", "Supprimer les légumes"], "Trop rapide = plus de gras probable."),
    qcm("Les glucides en prise de masse aident notamment à…", "Soutenir l'entraînement", ["Créer des fibres musculaires sans effort", "Remplacer les acides aminés", "Annuler les lipides"], "Ils alimentent les séances."),
    tf("Plus le surplus est grand, plus le gain musculaire est illimité.", false, "Le muscle ne suit pas sans plafond."),
    tf("Un petit surplus est souvent plus propre qu'un énorme surplus.", true, "Moins de prise de gras inutile."),
    tf("Les protéines doivent être suffisantes, pas seulement les calories.", true, "Le matériau compte."),
    tf("La variété n'a aucun intérêt en prise de masse.", false, "Micronutriments, fibres et santé digestive comptent."),
    multi("Bases d'une prise de masse efficace :", ["Surplus modéré", "Progression musculation"], ["Déficit sévère", "Sommeil sacrifié"], "Énergie + stimulus + récupération."),
    multi("Signes d'un surplus trop haut :", ["Prise de gras rapide", "Poids qui grimpe très vite"], ["Force stable en baisse calorique", "Faim permanente"], "Le rythme informe l'ajustement."),
    order("Lancer une prise de masse", ["Fixer un petit surplus", "Suivre poids et performances", "Ajuster après quelques semaines"], "On pilote avec des données."),
    order("Répartir les protéines", ["Prévoir 3 à 5 repas", "Inclure une source protéinée", "Compléter selon l'apport total"], "La répartition facilite la régularité."),
    match("Associe élément et rôle", [["Surplus", "Énergie"], ["Protéines", "Matériau"], ["Musculation", "Signal"]], "Les trois sont complémentaires."),
    match("Associe situation et réponse", [["Poids trop rapide", "Baisser un peu"], ["Appétit faible", "Aliments plus denses"], ["Digestion lourde", "Répartir les repas"]], "L'ajustement dépend du blocage."),
    qcm("Réflexion : manger 1500 kcal de plus que besoin chaque jour augmente surtout le risque de…", "Prendre beaucoup de gras", ["Doubler le muscle garanti", "Ne plus avoir besoin de dormir", "Supprimer les courbatures"], "Le plafond musculaire limite le bénéfice."),
    qcm("Réflexion : une prise de masse réussie se juge par…", "Poids, mensurations, force et aspect sur la durée", ["Un seul repas énorme", "Le nombre de shakers", "Le slogan du programme"], "Plusieurs indices évitent les illusions."),
  ),
  quiz20(
    qcm("Avant une séance, un repas pris 1 à 3 h avant doit être surtout…", "Digeste et riche en énergie utile", ["Très gras et énorme pour tous", "Sans eau", "Uniquement protéiné sans glucides"], "Le timing dépend de la tolérance."),
    qcm("Le glycogène sert principalement de réserve de…", "Glucides dans muscle et foie", ["Graisses trans", "Sodium osseux", "Fibres digestives"], "Il alimente les efforts intenses."),
    qcm("Pendant une séance intense, les glucides aident surtout à…", "Maintenir l'effort", ["Remplacer la technique", "Annuler la fatigue nerveuse", "Créer du muscle sans repos"], "Le carburant soutient la performance."),
    qcm("Après l'effort, la récupération nutritionnelle se joue sur…", "Les heures qui suivent", ["Les 30 secondes uniques", "Trois jours sans manger", "Uniquement le lendemain soir"], "La fenêtre existe, mais elle est large."),
    qcm("L'hydratation influence…", "Performance et thermorégulation", ["La couleur des protéines", "Le nombre d'os", "Le Nutri-Score"], "Même légère déshydratation peut gêner."),
    qcm("Un repas pré-entraînement trop gras peut…", "Ralentir la digestion", ["Accélérer toujours la séance", "Supprimer le besoin d'eau", "Augmenter le glycogène immédiatement"], "Les lipides ralentissent la vidange gastrique."),
    qcm("Pour une séance longue, l'apport en glucides peut devenir…", "Plus important", ["Toujours inutile", "Dangereux par définition", "Réservé au sommeil"], "Durée et intensité changent les besoins."),
    qcm("La boisson de base pour la plupart des séances reste…", "L'eau", ["L'alcool", "L'huile", "Le soda obligatoire"], "Simple et efficace, sauf cas longs/intenses."),
    tf("Le repas pré-séance doit être adapté à la tolérance digestive.", true, "Le bon repas est aussi celui qui passe bien."),
    tf("Le glycogène n'a aucun rôle dans les efforts intenses.", false, "Il est central pour l'intensité."),
    tf("Le post-effort n'est pas une fenêtre magique de quelques minutes seulement.", true, "Les heures suivantes comptent."),
    tf("L'hydratation peut influencer la performance.", true, "Déshydratation = baisse possible."),
    multi("Avant l'entraînement, souvent utile :", ["Glucides digestes", "Hydratation"], ["Repas énorme très gras", "Alcool"], "Objectif : énergie sans lourdeur."),
    multi("Après l'effort, priorités fréquentes :", ["Protéines", "Glucides selon effort"], ["Jeûne forcé toujours", "Sel illimité sans contexte"], "On recharge et répare selon la séance."),
    order("Préparer un repas pré-séance", ["Choisir des glucides digestes", "Ajouter protéines modérées", "Laisser 1 à 3 h selon tolérance"], "Digestion et énergie doivent cohabiter."),
    order("Récupérer après une séance dure", ["Boire suffisamment", "Manger protéines", "Recharger en glucides si besoin"], "Hydratation, réparation, carburant."),
    match("Associe notion et rôle", [["Glycogène", "Réserve de glucides"], ["Hydratation", "Thermorégulation"], ["Protéines", "Réparation"]], "Performance et récupération ont plusieurs leviers."),
    match("Associe timing et priorité", [["1-3 h avant", "Digestion"], ["Pendant long effort", "Carburant possible"], ["Après", "Récupération"]], "Le moment change l'objectif."),
    qcm("Réflexion : si tu as mal au ventre à l'entraînement, il faut d'abord tester…", "Un repas plus léger ou plus éloigné", ["Plus de gras juste avant", "Moins d'eau systématiquement", "Un arrêt des glucides à vie"], "La tolérance individuelle prime."),
    qcm("Réflexion : après une séance courte de musculation, le plus important est surtout…", "Atteindre les apports de la journée", ["Boire du sucre immédiatement quoi qu'il arrive", "Manger dans les 2 minutes", "Éviter toute protéine"], "Le total quotidien reste majeur."),
  ),
  quiz20(
    qcm("Pour la santé cardio, un pilier alimentaire est…", "Plus de végétaux variés", ["Plus de trans industriels", "Zéro fibre", "Sel sans limite"], "Fruits, légumes, légumineuses et céréales complètes aident."),
    qcm("Les oméga-3 sont associés notamment à…", "Une meilleure santé cardiovasculaire", ["Une hausse des trans", "Une absence de calories", "Une digestion impossible"], "Effets modestes mais utiles dans un pattern global."),
    qcm("Limiter les produits ultra-transformés aide souvent car ils sont riches en…", "Sel, sucres ou graisses de mauvaise qualité", ["Fibres intactes uniquement", "Eau pure", "Vitamine C garantie"], "Le profil moyen est défavorable."),
    qcm("La musculation peut aider la santé cardio en améliorant…", "Composition corporelle et sensibilité à l'insuline", ["La rigidité des artères à coup sûr", "Le besoin de légumes", "La consommation de tabac"], "Force et cardio ne sont pas opposés."),
    qcm("Les légumineuses sont intéressantes car elles apportent…", "Fibres et protéines végétales", ["Trans industriels", "Alcool", "Sodium pur"], "Bon profil pour satiété et santé."),
    qcm("Un excès chronique de sel peut contribuer à…", "Une tension plus élevée", ["Plus de vitamine D", "Moins de besoin d'eau", "Plus de muscle direct"], "La réponse varie, mais le risque existe."),
    qcm("Une stratégie cardio-protectrice réaliste est de…", "Remplacer une partie des produits transformés par des aliments simples", ["Tout changer en un jour", "Supprimer tous les lipides", "Ne manger que des compléments"], "Les substitutions durables comptent."),
    qcm("Les graisses trans industrielles sont plutôt…", "Défavorables au risque cardiovasculaire", ["Recommandées quotidiennement", "Sans effet connu", "Des protéines"], "À limiter fortement."),
    tf("Les végétaux apportent souvent fibres, potassium et micronutriments.", true, "Ces éléments soutiennent la santé cardio."),
    tf("La musculation est inutile pour la santé cardiométabolique.", false, "Elle améliore plusieurs marqueurs."),
    tf("Limiter les ultra-transformés peut réduire sel et calories cachées.", true, "C'est un levier simple."),
    tf("Les oméga-3 sont des graisses trans.", false, "Ce sont des polyinsaturés."),
    multi("Choix favorables au coeur :", ["Légumineuses", "Poissons gras"], ["Charcuteries fréquentes", "Fritures industrielles"], "On augmente les aliments protecteurs."),
    multi("Leviers cardio côté mode de vie :", ["Musculation régulière", "Activité d'endurance"], ["Sédentarité", "Sommeil sacrifié en permanence"], "L'assiette n'est qu'une partie."),
    order("Améliorer une journée pour le coeur", ["Ajouter une portion de végétaux", "Choisir une graisse de qualité", "Limiter un produit très transformé"], "Petits remplacements, effet cumulé."),
    order("Lire un produit pour santé cardio", ["Regarder sel", "Lire saturés/trans possibles", "Vérifier fibres"], "Sel, graisses, fibres orientent le choix."),
    match("Associe aliment et intérêt", [["Légumineuses", "Fibres"], ["Poisson gras", "Oméga-3"], ["Charcuterie", "Sel élevé possible"]], "Les familles ont des profils différents."),
    match("Associe levier et effet", [["Végétaux", "Micronutriments"], ["Musculation", "Sensibilité insuline"], ["Ultra-transformés", "À limiter"]], "Le pattern complet protège mieux."),
    qcm("Réflexion : pour le coeur, supprimer toutes les graisses serait une erreur car…", "Certaines graisses sont utiles", ["Les trans sont indispensables", "L'huile n'a pas de calories", "Les oméga-3 sont des sucres"], "Qualité et quantité, pas interdiction totale."),
    qcm("Réflexion : le meilleur changement cardio est souvent celui que tu peux…", "Répéter longtemps", ["Faire une seule fois", "Subir trois jours", "Compenser par un slogan"], "La santé cardio répond aux habitudes."),
  ),
  quiz20(
    qcm("La glycémie correspond au taux de…", "Glucose dans le sang", ["Sel dans l'os", "Lipides dans le muscle", "Protéines dans l'air"], "C'est le sucre sanguin."),
    qcm("Un repas mixte aide souvent la glycémie car il combine…", "Glucides, protéines, lipides et fibres", ["Sucre seul", "Eau seule", "Sel seul"], "La digestion est plus progressive."),
    qcm("L'activité physique améliore la sensibilité à…", "L'insuline", ["La caféine uniquement", "La vitamine C", "La lumière"], "Les muscles utilisent mieux le glucose."),
    qcm("Pour une glycémie plus stable, il est utile d'éviter souvent…", "Les gros apports de sucre isolé", ["Les protéines maigres", "Les légumes", "Les légumineuses"], "Sucre seul = pic plus facile."),
    qcm("Les fibres ralentissent l'absorption des glucides en…", "Rendant la digestion plus progressive", ["Transformant le sucre en muscle", "Bloquant toute énergie", "Ajoutant du sodium"], "Elles modulent la vitesse."),
    qcm("En cas de diabète, les conseils nutritionnels doivent être…", "Adaptés avec un suivi médical", ["Génériques et sans contrôle", "Remplacés par du hasard", "Fondés sur les réseaux sociaux"], "Traitement, risques et contexte changent tout."),
    qcm("Marcher après un repas peut aider à…", "Utiliser une partie du glucose", ["Empêcher toute digestion", "Supprimer les calories", "Créer des vitamines"], "L'activité musculaire capte du glucose."),
    qcm("Un jus de fruit est souvent moins stable qu'un fruit entier car il manque…", "Une partie des fibres et de la mastication", ["Tout le sucre", "Toute l'eau", "Toute couleur"], "La matrice change l'absorption."),
    tf("Un repas mixte peut ralentir la montée de glycémie.", true, "Protéines, lipides et fibres ralentissent."),
    tf("L'activité physique peut améliorer la sensibilité à l'insuline.", true, "Effet reconnu, surtout régulier."),
    tf("En diabète, il faut ignorer l'avis médical si on mange mieux.", false, "Le suivi est essentiel."),
    tf("Tous les glucides ont exactement le même effet chez tout le monde.", false, "Quantité, matrice et personne comptent."),
    multi("Pour stabiliser la glycémie :", ["Ajouter fibres", "Associer protéines aux glucides"], ["Boire du sucre seul souvent", "Rester immobile en permanence"], "Le contexte du repas compte."),
    multi("Situations demandant prudence médicale :", ["Diabète traité", "Hypoglycémies répétées"], ["Choisir une salade", "Lire une étiquette"], "Certains cas nécessitent un professionnel."),
    order("Composer un repas plus stable", ["Choisir une source de glucides", "Ajouter protéines et fibres", "Ajuster la portion"], "Mixité et dose font la stabilité."),
    order("Réagir à des pics fréquents", ["Observer les repas déclencheurs", "Ajouter activité légère", "Demander un suivi si diabète"], "On agit sans jouer au médecin."),
    match("Associe élément et effet", [["Fibres", "Absorption ralentie"], ["Insuline", "Entrée du glucose"], ["Marche", "Utilisation musculaire"]], "Les mécanismes sont simples."),
    match("Associe aliment et impact typique", [["Fruit entier", "Plus stable"], ["Soda", "Pic rapide"], ["Repas mixte", "Progressif"]], "La matrice modifie la réponse."),
    qcm("Réflexion : un pic de glycémie après bonbon seul est plus probable qu'après repas complet car…", "Le sucre est moins freiné", ["Les fibres accélèrent tout", "Les protéines sont du sucre", "L'eau supprime l'insuline"], "Le repas complet ralentit l'entrée du glucose."),
    qcm("Réflexion : pour une personne diabétique sportive, le plus sûr est de…", "Coordonner alimentation, activité et traitement avec un professionnel", ["Copier un influenceur", "Arrêter tout glucide sans avis", "Ignorer les hypoglycémies"], "La sécurité prime."),
  ),
  quiz20(
    qcm("La sarcopénie désigne surtout…", "La perte de masse et fonction musculaire liée à l'âge", ["Une allergie au lait", "Un excès de fibres", "Un type de sucre"], "Elle touche muscle et autonomie."),
    qcm("Avec l'âge, les besoins en protéines peuvent être…", "Plus élevés ou plus prioritaires", ["Toujours nuls", "Remplacés par le sucre", "Sans lien avec le muscle"], "Le muscle répond moins fort au stimulus."),
    qcm("La vitamine D et le calcium soutiennent surtout…", "Santé osseuse et fonction musculaire", ["Stockage du sel uniquement", "Production de trans", "Digestion du gluten"], "Ils comptent pour os et mouvements."),
    qcm("La vitamine B12 mérite attention chez les personnes âgées car…", "Son absorption peut diminuer", ["Elle devient toxique dans les légumes", "Elle remplace les protéines", "Elle n'existe que dans l'eau"], "Déficit possible, surtout selon alimentation et santé digestive."),
    qcm("La sensation de soif avec l'âge tend souvent à…", "Diminuer", ["Doubler toujours", "Disparaître uniquement chez les sportifs", "Mesurer les protéines"], "Il faut parfois boire par routine."),
    qcm("La musculation chez les seniors aide à…", "Préserver force et autonomie", ["User automatiquement les os", "Bloquer la vitamine D", "Supprimer toute récupération"], "Le renforcement est un vrai outil santé."),
    qcm("Répartir les protéines sur la journée peut aider car…", "Chaque repas stimule la synthèse musculaire", ["La nuit annule les apports", "Les protéines deviennent du sel", "Cela remplace les calories"], "La régularité compte."),
    qcm("Un senior qui mange peu doit prioriser…", "Protéines, énergie et micronutriments", ["Calories vides uniquement", "Sodas seuls", "Zéro lipide"], "Densité nutritionnelle importante."),
    tf("La sarcopénie concerne seulement l'apparence physique.", false, "Elle touche force, mobilité et risque de chute."),
    tf("La soif peut être moins fiable avec l'âge.", true, "Le signal diminue souvent."),
    tf("La vitamine D et le calcium sont liés à la santé osseuse.", true, "Ils participent au maintien osseux."),
    tf("Les personnes âgées n'ont jamais besoin de protéines.", false, "Elles en ont souvent besoin autant ou plus."),
    multi("Points clés du vieillissement nutritionnel :", ["Protéines suffisantes", "Hydratation régulière"], ["Jeûne extrême imposé", "Éviter toute musculation"], "On protège muscle et autonomie."),
    multi("Micronutriments à surveiller souvent :", ["Vitamine D", "Vitamine B12"], ["Graisses trans", "Alcool"], "Les besoins dépendent du contexte médical."),
    order("Protéger le muscle avec l'âge", ["Faire du renforcement adapté", "Manger assez de protéines", "Récupérer et dormir suffisamment"], "Stimulus, matériau, récupération."),
    order("Limiter le risque de déshydratation", ["Prévoir des moments pour boire", "Observer urine et chaleur", "Adapter avec médecin si traitement"], "Soif et médicaments changent le risque."),
    match("Associe notion et importance", [["Sarcopénie", "Force/autonomie"], ["B12", "Absorption à surveiller"], ["Calcium", "Os"]], "Les priorités changent avec l'âge."),
    match("Associe pratique et bénéfice", [["Musculation adaptée", "Maintien force"], ["Protéines réparties", "Synthèse stimulée"], ["Boire régulièrement", "Hydratation"]], "Les routines simples aident."),
    qcm("Réflexion : chez une personne âgée avec petit appétit, le meilleur repas est souvent…", "Dense en protéines et micronutriments", ["Très volumineux mais pauvre en nutriments", "Uniquement sucré", "Sans boisson"], "Chaque bouchée doit compter."),
    qcm("Réflexion : si une personne âgée prend des traitements, l'hydratation doit être discutée car…", "Certains médicaments modifient les besoins ou risques", ["L'eau devient inutile", "La soif mesure la B12", "Les protéines bloquent tout"], "Le contexte médical compte."),
  ),
  quiz20(
    qcm("Une alimentation végétarienne équilibrée est…", "Possible si elle est planifiée", ["Toujours carencée", "Toujours supérieure sans effort", "Sans protéines"], "La qualité dépend des choix."),
    qcm("Associer légumineuses et céréales aide à…", "Compléter les acides aminés", ["Créer de la vitamine B12", "Supprimer les fibres", "Augmenter les trans"], "Exemple : lentilles + riz."),
    qcm("Le fer végétal est mieux absorbé avec…", "Vitamine C", ["Café pendant le repas", "Graisses trans", "Sel uniquement"], "Agrumes, poivron ou kiwi peuvent aider."),
    qcm("La vitamine B12 est indispensable à supplémenter surtout en…", "Véganisme", ["Régime riche en poisson", "Alimentation omnivore variée toujours", "Consommation d'eau"], "Les sources fiables végétales sont insuffisantes."),
    qcm("Les légumineuses apportent souvent…", "Protéines, fibres et glucides", ["B12 fiable", "Graisses trans", "Zéro calorie"], "Elles sont centrales en végétarisme."),
    qcm("Le tofu, tempeh et soja sont des sources de…", "Protéines végétales", ["Sel pur", "Vitamine C uniquement", "Collagène animal"], "Pratiques pour atteindre l'apport."),
    qcm("Un piège végétarien fréquent est de manger surtout…", "Produits raffinés pauvres en protéines", ["Légumineuses variées", "Fruits et légumes", "Noix en portion"], "Végétarien ne veut pas automatiquement dire équilibré."),
    qcm("Le zinc et l'iode peuvent aussi nécessiter attention selon…", "Les choix alimentaires", ["La couleur du paquet", "Le nombre de repas sur photo", "La météo seule"], "Certains micronutriments demandent un plan."),
    tf("Végétarien peut couvrir les protéines avec de bons choix.", true, "Légumineuses, soja, oeufs/laitages si inclus."),
    tf("Les végans doivent prendre la B12 au sérieux.", true, "Supplément ou aliment enrichi fiable."),
    tf("La vitamine C peut améliorer l'absorption du fer végétal.", true, "Elle augmente l'absorption du fer non héminique."),
    tf("Riz blanc + bonbons suffit à rendre un régime végétarien équilibré.", false, "Il manque protéines et micronutriments."),
    multi("Sources protéiques végétariennes utiles :", ["Lentilles", "Tofu"], ["Soda", "Sucre blanc"], "Elles apportent des acides aminés."),
    multi("À surveiller en végétarisme/véganisme :", ["B12", "Fer"], ["Additifs E sans contexte", "Couleur de l'assiette seule"], "Planifier évite les carences."),
    order("Construire un repas végétarien complet", ["Choisir légumineuse ou soja", "Ajouter céréale ou féculent", "Ajouter légumes riches en vitamine C"], "Protéines, énergie, absorption du fer."),
    order("Sécuriser un régime végan", ["Prévoir B12 fiable", "Varier protéines végétales", "Contrôler fer/iode/oméga-3 selon contexte"], "Le véganisme demande plus de vigilance."),
    match("Associe aliment et rôle", [["Lentilles", "Protéines + fer"], ["Poivron", "Vitamine C"], ["B12", "Supplément fiable en végan"]], "Les associations améliorent l'équilibre."),
    match("Associe combinaison et intérêt", [["Riz + haricots", "Acides aminés complétés"], ["Thé au repas", "Fer moins absorbé"], ["Kiwi", "Aide le fer végétal"]], "Les détails changent l'absorption."),
    qcm("Réflexion : un végétarien qui progresse en musculation doit surtout vérifier…", "Apport protéique total et qualité des sources", ["La présence d'un slogan bio", "L'absence totale de glucides", "Le nombre de couleurs du paquet"], "La progression demande matière et entraînement."),
    qcm("Réflexion : le meilleur message sur le végétarisme est…", "Possible et sain si bien construit", ["Impossible pour les sportifs", "Automatiquement parfait", "Sans besoin de B12 en végan"], "Nuance : faisable, mais planifié."),
  ),
];
