import type { SeedQuestion } from "../anatomie-quiz-helpers";
import { qcm, tf, multi, order, match } from "../anatomie-quiz-helpers";
import { quiz20 } from "./quiz-bank";

export const THEME_4_QUIZZES: SeedQuestion[][] = [
  quiz20(
    qcm("La digestion commence principalement dans…", "La bouche", ["Le muscle", "Le foie", "Le côlon uniquement"], "Mastication et salive lancent le travail."),
    qcm("Après la bouche, le bol alimentaire passe surtout par…", "L'estomac puis l'intestin", ["Les reins puis les poumons", "Le cœur puis les os", "Les muscles puis la peau"], "Trajet simple : bouche, estomac, intestin."),
    qcm("Un repas mixte reste souvent dans l'estomac environ…", "2 à 4 heures", ["10 minutes", "12 à 18 heures", "3 jours"], "La vidange gastrique est progressive."),
    qcm("Les lipides ont tendance à…", "Ralentir la vidange gastrique", ["Accélérer tous les repas", "Bloquer les enzymes", "Se transformer directement en muscle"], "Le gras prolonge souvent la digestion."),
    qcm("Les enzymes digestives servent à…", "Découper les nutriments", ["Stocker le glycogène", "Transporter l'oxygène", "Fabriquer les os"], "Elles rendent les molécules absorbables."),
    qcm("Les protéines sont découpées surtout en…", "Acides aminés", ["Glycogène", "Fibres", "Eau"], "Les acides aminés sont les unités absorbables."),
    qcm("Les glucides digestibles finissent surtout en…", "Glucose ou sucres simples", ["Triglycérides uniquement", "Vitamines", "Cellulose"], "Ils sont simplifiés avant absorption."),
    qcm("Pour éviter la lourdeur avant séance, il vaut mieux souvent…", "Laisser du temps au repas", ["Manger très gras juste avant", "Ne jamais boire", "Avaler sans mâcher"], "La digestion demande du délai."),
    tf("Tous les nutriments arrivent dans le sang d'un seul coup.", false, "Faux : l'arrivée se fait par vagues."),
    tf("Un repas très gras peut être plus lourd près d'un entraînement.", true, "Vrai : les lipides ralentissent la vidange."),
    tf("La digestion se limite à l'estomac.", false, "Faux : bouche, estomac et intestin participent."),
    tf("Les enzymes rendent les nutriments plus faciles à absorber.", true, "Vrai : elles découpent les grosses molécules."),
    multi("Quels éléments participent directement à la digestion ?", ["Mastication", "Enzymes", "Estomac"], ["Tibia"], "La digestion combine mécanique et chimie."),
    multi("Quels facteurs peuvent ralentir l'arrivée des nutriments ?", ["Repas riche en lipides", "Gros volume alimentaire"], ["Respiration nasale", "Couleur de l'assiette"], "Volume et gras ralentissent souvent."),
    order("Remets le trajet digestif dans l'ordre.", ["Bouche", "Estomac", "Intestin"], "C'est le parcours principal du repas."),
    order("Remets ces étapes dans l'ordre.", ["Mastiquer", "Brasser dans l'estomac", "Absorber dans l'intestin"], "On prépare avant d'absorber."),
    match("Associe chaque élément à son rôle.", [["Bouche", "Mastication"], ["Estomac", "Brassage"], ["Intestin", "Absorption"]], "Chaque zone a un rôle dominant."),
    match("Associe chaque nutriment à une unité absorbable.", [["Protéines", "Acides aminés"], ["Glucides", "Glucose"], ["Lipides", "Acides gras"]], "La digestion découpe en petites unités."),
    qcm("Si tu as souvent l'estomac lourd à la séance, le premier ajustement logique est…", "Avancer ou alléger le repas", ["Ajouter beaucoup de friture", "Supprimer toute eau", "Manger plus vite"], "Le timing et la composition comptent."),
    qcm("Dire que la digestion est progressive signifie que…", "Les nutriments arrivent peu à peu", ["Rien n'est absorbé", "Tout arrive instantanément", "Seuls les lipides comptent"], "Le corps absorbe au fil du repas digéré."),
  ),
  quiz20(
    qcm("L'absorption des nutriments se fait surtout dans…", "L'intestin grêle", ["La bouche", "L'estomac seul", "Les poumons"], "C'est la grande zone d'échange."),
    qcm("Les villosités intestinales servent à…", "Augmenter la surface d'absorption", ["Produire la force", "Stocker le gras", "Filtrer l'air"], "Plus de surface = plus d'échanges."),
    qcm("Le glucose absorbé passe principalement dans…", "Le sang", ["La lymphe d'abord", "Les os", "La vessie"], "Il rejoint vite la circulation sanguine."),
    qcm("Les acides aminés passent surtout dans…", "Le sang", ["Les cheveux", "La bile", "L'air"], "Ils circulent vers les tissus."),
    qcm("Les lipides alimentaires passent d'abord souvent par…", "La lymphe", ["Le cerveau directement", "Les reins uniquement", "La salive"], "Leur transport initial diffère."),
    qcm("Sans villosités efficaces, l'absorption serait…", "Beaucoup moins performante", ["Instantanée", "Inutile", "Limitée aux lipides"], "La surface d'échange est essentielle."),
    qcm("L'intestin grêle est important car il…", "Fait entrer les nutriments dans le corps", ["Fabrique les quadriceps", "Stocke tout le glycogène", "Élimine l'oxygène"], "Digérer ne suffit pas : il faut absorber."),
    qcm("L'absorption concerne surtout…", "Le passage vers les liquides corporels", ["La mastication seule", "La transpiration", "La contraction musculaire"], "Les nutriments traversent la paroi."),
    tf("Glucose et acides aminés empruntent surtout le sang.", true, "Vrai : ils rejoignent la circulation sanguine."),
    tf("Les lipides suivent exactement le même trajet que le glucose.", false, "Faux : ils passent souvent d'abord par la lymphe."),
    tf("Les villosités diminuent la surface d'absorption.", false, "Faux : elles l'augmentent fortement."),
    tf("L'intestin grêle est une zone majeure d'absorption.", true, "Vrai : c'est son rôle central."),
    multi("Quels nutriments passent surtout dans le sang après absorption ?", ["Glucose", "Acides aminés"], ["Fibres intactes", "Air"], "Glucose et AA rejoignent le sang."),
    multi("Quels éléments favorisent l'absorption intestinale ?", ["Grande surface", "Villosités"], ["Moins de paroi", "Absence d'intestin"], "La structure de l'intestin aide les échanges."),
    order("Remets le parcours du glucose dans l'ordre.", ["Digestion des glucides", "Absorption intestinale", "Passage dans le sang"], "Le glucose doit d'abord être libéré."),
    order("Remets ces étapes dans l'ordre.", ["Nutriment dans l'intestin", "Traversée de la paroi", "Circulation vers les tissus"], "Absorber, c'est franchir la paroi."),
    match("Associe voie et nutriment.", [["Glucose", "Sang"], ["Acides aminés", "Sang"], ["Lipides", "Lymphe"]], "Les lipides ont une voie particulière."),
    match("Associe structure et fonction.", [["Villosités", "Surface"], ["Intestin grêle", "Absorption"], ["Sang", "Transport"]], "Structure et fonction sont liées."),
    qcm("Un repas peut être digéré mais mal utilisé si…", "L'absorption est perturbée", ["La mastication est parfaite", "Les villosités fonctionnent bien", "Le sang transporte normalement"], "Digestion et absorption sont deux étapes."),
    qcm("La nuance importante sur les lipides est qu'ils…", "Entrent plus lentement via la lymphe", ["Ne sont jamais absorbés", "Deviennent du glucose pur", "Passent par les poumons"], "Leur transport est plus indirect."),
  ),
  quiz20(
    qcm("La glycémie désigne…", "La concentration de glucose dans le sang", ["La taille des muscles", "Le taux de fibres", "La quantité d'eau bue"], "Glycémie = sucre sanguin."),
    qcm("Les glucides rapides ont tendance à…", "Faire monter la glycémie plus vite", ["Ne jamais être absorbés", "Baisser toujours la glycémie", "Se transformer en fibres"], "Leur absorption est plus rapide."),
    qcm("Les glucides plus lents donnent souvent…", "Une montée glycémique plus progressive", ["Une absence totale d'énergie", "Un pic toujours plus fort", "Un effet sans digestion"], "Leur digestion est plus graduelle."),
    qcm("Pendant un effort intense, le muscle utilise beaucoup…", "De glucose", ["De fibres", "D'alcool", "De calcium seul"], "Le glucose soutient les efforts intenses."),
    qcm("Les fibres dans un repas…", "Ralentissent l'entrée du glucose", ["Accélèrent toujours le pic", "Annulent les calories", "Bloque les protéines"], "Elles adoucissent la montée."),
    qcm("Les lipides dans un repas glucidique peuvent…", "Ralentir la montée glycémique", ["Supprimer l'insuline", "Créer du glycogène illimité", "Empêcher toute absorption"], "Ils ralentissent la vidange gastrique."),
    qcm("Un jus sucré seul provoque souvent…", "Une montée rapide", ["Une digestion impossible", "Une satiété très longue", "Une absence de glucose"], "Liquide sucré = absorption rapide."),
    qcm("Une glycémie stable aide surtout à…", "Maintenir énergie et concentration", ["Éviter toute digestion", "Remplacer le sommeil", "Créer du muscle sans entraînement"], "Moins de montagnes russes énergétiques."),
    tf("La glycémie correspond au glucose sanguin.", true, "Vrai : c'est sa concentration dans le sang."),
    tf("Les fibres peuvent ralentir la réponse glycémique.", true, "Vrai : elles freinent l'absorption."),
    tf("Tous les glucides montent la glycémie à la même vitesse.", false, "Faux : forme et repas changent la vitesse."),
    tf("Le glucose n'a aucun lien avec l'effort intense.", false, "Faux : c'est un carburant majeur."),
    multi("Quels éléments ralentissent souvent la montée du glucose ?", ["Fibres", "Lipides"], ["Jus sucré seul", "Bonbon à jeun"], "Le repas mixte ralentit l'entrée du sucre."),
    multi("Quels choix donnent souvent une énergie plus stable ?", ["Avoine", "Légumineuses"], ["Soda seul", "Sucre pur seul"], "Glucides riches en fibres = montée plus douce."),
    order("Remets la réponse après un repas glucidique dans l'ordre.", ["Digestion des glucides", "Glucose absorbé", "Glycémie qui monte"], "Le sucre sanguin monte après absorption."),
    order("Remets ces étapes d'effort dans l'ordre.", ["Glycémie disponible", "Muscle capte du glucose", "Énergie pour l'effort"], "Le glucose devient carburant."),
    match("Associe l'aliment à l'effet probable.", [["Jus sucré", "Montée rapide"], ["Lentilles", "Montée plus lente"], ["Repas gras", "Vidange ralentie"]], "La matrice du repas change la vitesse."),
    match("Associe notion et définition.", [["Glucose", "Sucre simple"], ["Glycémie", "Concentration sanguine"], ["Fibres", "Frein digestif"]], "Ces notions structurent la réponse glycémique."),
    qcm("Avant une séance, choisir des glucides lents peut aider si l'objectif est…", "Éviter un coup de fatigue rapide", ["Dormir immédiatement", "Bloquer l'absorption", "Supprimer l'eau"], "Une entrée plus progressive peut stabiliser l'énergie."),
    qcm("Un pic glycémique n'est pas toujours un problème, mais il dépend surtout…", "Du contexte et du repas complet", ["De la couleur du sucre", "Du nom de l'aliment seul", "De la taille des chaussures"], "La nuance vient du contexte."),
  ),
  quiz20(
    qcm("L'insuline est produite par…", "Le pancréas", ["Le foie", "Le tibia", "L'estomac uniquement"], "Le pancréas sécrète l'insuline."),
    qcm("L'insuline est surtout libérée quand…", "La glycémie monte", ["La glycémie disparaît", "On arrête de respirer", "Les fibres deviennent du muscle"], "Elle répond à l'arrivée de glucose."),
    qcm("Un rôle majeur de l'insuline est de…", "Aider le glucose à entrer dans les cellules", ["Empêcher toute digestion", "Casser les os", "Créer des fibres alimentaires"], "Elle range le glucose."),
    qcm("Dans le muscle, l'insuline aide aussi l'entrée…", "Des acides aminés", ["De l'air", "Des fibres intactes", "De la bile"], "Elle soutient la réparation."),
    qcm("L'entraînement régulier améliore souvent…", "La sensibilité à l'insuline", ["L'intolérance à l'eau", "La couleur du sang", "La production de fibres"], "Le muscle devient plus réceptif."),
    qcm("Une meilleure sensibilité signifie que…", "Moins d'insuline peut suffire", ["Plus de sucre reste dehors", "Le pancréas s'arrête", "Les muscles refusent le glucose"], "Les cellules répondent mieux."),
    qcm("Après l'effort, le muscle est souvent…", "Plus réceptif aux nutriments", ["Fermé au glucose", "Incapable d'utiliser les AA", "Sans circulation sanguine"], "L'entraînement augmente la captation."),
    qcm("Présenter l'insuline comme uniquement mauvaise est…", "Trop simpliste", ["Toujours exact", "Scientifique à 100 %", "Sans lien avec le muscle"], "Elle a des rôles utiles."),
    tf("L'insuline aide à faire baisser la glycémie.", true, "Vrai : elle facilite l'entrée du glucose."),
    tf("Le pancréas produit l'insuline.", true, "Vrai : c'est l'organe principal."),
    tf("L'insuline empêche toujours le muscle de récupérer.", false, "Faux : elle aide aussi les acides aminés."),
    tf("L'entraînement peut améliorer la sensibilité à l'insuline.", true, "Vrai : surtout avec régularité."),
    multi("Quels rôles sont liés à l'insuline ?", ["Faire entrer le glucose", "Aider l'entrée des acides aminés"], ["Digérer les fibres", "Former la bile"], "Elle facilite le rangement des nutriments."),
    multi("Qu'est-ce qui peut soutenir une meilleure sensibilité à l'insuline ?", ["Entraînement régulier", "Masse musculaire active"], ["Sédentarité prolongée", "Sommeil toujours nul"], "Le muscle entraîné capte mieux le glucose."),
    order("Remets la réponse insulinique dans l'ordre.", ["Repas glucidique", "Glycémie qui monte", "Insuline libérée"], "Le signal suit la montée du glucose."),
    order("Remets ces étapes dans l'ordre.", ["Insuline circulante", "Glucose entre dans les cellules", "Glycémie redescend"], "Elle aide à normaliser la glycémie."),
    match("Associe organe et rôle.", [["Pancréas", "Insuline"], ["Muscle", "Captation du glucose"], ["Sang", "Transport du glucose"]], "Chaque acteur a sa place."),
    match("Associe terme et sens.", [["Sensibilité", "Réponse efficace"], ["Insuline", "Hormone de rangement"], ["Acides aminés", "Matériaux musculaires"]], "Les termes expliquent le mécanisme."),
    qcm("Après une séance, protéines + glucides peuvent être pertinents car…", "Le muscle capte mieux nutriments et glucose", ["L'insuline disparaît", "Les fibres bloquent tout", "Le foie cesse de fonctionner"], "Le contexte post-effort est favorable."),
    qcm("La bonne nuance sur l'insuline est qu'elle…", "Stocke et soutient aussi la récupération", ["Stocke seulement du gras", "Est inutile chez le sportif", "Remplace l'entraînement"], "Elle n'est ni magique ni ennemie."),
  ),
  quiz20(
    qcm("Le glycogène est une forme de stockage…", "Du glucose", ["Des fibres", "De l'alcool", "Du fer"], "C'est une réserve de glucides."),
    qcm("Les réserves de glycogène sont…", "Rapides mais limitées", ["Illimitées", "Inutiles", "Uniquement dans les os"], "Elles servent vite mais se remplissent."),
    qcm("Le gras corporel est une réserve…", "Abondante et longue durée", ["Très limitée", "Sans énergie", "De glucose pur"], "Il stocke beaucoup d'énergie."),
    qcm("Pour la performance en musculation, le glycogène musculaire aide surtout…", "Les séries intenses", ["La pousse des cheveux", "La digestion des fibres", "La respiration seule"], "Il alimente les efforts répétés."),
    qcm("Quand les apports dépassent longtemps les dépenses, l'excédent peut finir…", "Stocké en gras", ["Évaporé", "Transformé en eau uniquement", "Bloqué dans l'estomac"], "L'énergie excédentaire se stocke."),
    qcm("Le glycogène se trouve surtout dans…", "Foie et muscles", ["Poumons et peau", "Cheveux et ongles", "Os et dents"], "Ce sont les deux grands stocks."),
    qcm("À effort modéré prolongé, le corps utilise davantage…", "Le gras", ["Les fibres intactes", "Le calcium seul", "L'oxygène comme calorie"], "Le gras soutient les efforts longs."),
    qcm("Une réserve limitée signifie que…", "Elle peut se vider à l'effort", ["Elle est infinie", "Elle n'existe pas", "Elle remplace le repas"], "Le glycogène baisse avec l'utilisation."),
    tf("Le glycogène est une réserve rapide.", true, "Vrai : utile pour les efforts intenses."),
    tf("Le gras corporel contient beaucoup d'énergie stockée.", true, "Vrai : réserve longue durée."),
    tf("Les réserves de glycogène sont illimitées.", false, "Faux : leur capacité est finie."),
    tf("Tout excédent chronique reste toujours en glycogène.", false, "Faux : le surplus peut devenir gras."),
    multi("Quelles réserves stockent de l'énergie ?", ["Glycogène", "Triglycérides"], ["Fibres alimentaires", "Vitamines sans calories"], "Glycogène et gras sont énergétiques."),
    multi("Quels points décrivent le glycogène ?", ["Rapide", "Limité"], ["Abondant sans limite", "Non utilisable par le muscle"], "C'est un stock efficace mais fini."),
    order("Remets le stockage après surplus glucidique dans l'ordre.", ["Glucose disponible", "Glycogène rempli", "Excédent stocké autrement"], "La capacité du glycogène est limitée."),
    order("Remets l'utilisation pendant une série dans l'ordre.", ["Glycogène musculaire", "Glucose libéré localement", "Énergie pour contraction"], "Le muscle utilise son stock."),
    match("Associe réserve et caractéristique.", [["Glycogène", "Rapide"], ["Gras", "Abondant"], ["Muscle", "Stock local"]], "Chaque stock a son profil."),
    match("Associe contexte et réserve dominante.", [["Série intense", "Glycogène"], ["Déficit prolongé", "Gras"], ["Entre repas", "Foie"]], "Le contexte oriente le carburant."),
    qcm("Pour maintenir de bonnes performances, un apport glucidique cohérent aide surtout à…", "Recharger le glycogène", ["Créer des fibres", "Supprimer les lipides", "Bloquer l'insuline"], "Le stock de glucides soutient l'effort."),
    qcm("Le gras n'est pas un mauvais stock : il est surtout…", "Une réserve utile mais facile à accumuler en surplus", ["Un poison sans fonction", "Du muscle caché", "Un glucide rapide"], "La nuance dépend du bilan énergétique."),
  ),
  quiz20(
    qcm("Le foie aide à réguler…", "La glycémie", ["La longueur des os", "La couleur des muscles", "La quantité d'air"], "Il libère ou stocke du glucose."),
    qcm("Le glycogène musculaire est utilisé surtout par…", "Le muscle qui le stocke", ["Le cerveau directement", "Le poumon", "Un autre muscle à distance"], "C'est une réserve locale."),
    qcm("Le tissu adipeux stocke l'énergie sous forme de…", "Triglycérides", ["Fibres", "Glycogène illimité", "Vitamines seules"], "Les triglycérides sont la forme de gras stocké."),
    qcm("L'alcool est traité par le foie…", "En priorité", ["Jamais", "Seulement par les muscles", "Après les fibres"], "Le foie priorise sa dégradation."),
    qcm("Entre les repas, le foie peut…", "Libérer du glucose", ["Créer des villosités", "Contracter le quadriceps", "Stocker l'air"], "Il stabilise le sucre sanguin."),
    qcm("Pendant l'effort, le muscle pioche surtout dans…", "Son glycogène local", ["Le glycogène du voisin", "Les fibres alimentaires intactes", "La salive"], "Le stock musculaire reste local."),
    qcm("Le gras corporel est mobilisé surtout…", "Progressivement en déficit", ["Instantanément après chaque bouchée", "Uniquement en dormant", "Jamais"], "La mobilisation dépend du contexte énergétique."),
    qcm("Le foie est central car il…", "Coordonne plusieurs carburants", ["Remplace tous les muscles", "Absorbe toutes les fibres", "Produit la mastication"], "Il oriente stockage et libération."),
    tf("Le foie peut aider à stabiliser la glycémie.", true, "Vrai : il stocke et libère du glucose."),
    tf("Le muscle partage facilement son glycogène avec tout le corps.", false, "Faux : il l'utilise surtout localement."),
    tf("Les triglycérides sont une forme de stockage du gras.", true, "Vrai : c'est le stock du tissu adipeux."),
    tf("L'alcool passe sans priorité dans le foie.", false, "Faux : il est traité en priorité."),
    multi("Quels rôles appartiennent au foie ?", ["Stocker du glycogène", "Libérer du glucose"], ["Contracter les fibres musculaires", "Former les selles"], "Le foie régule la disponibilité du glucose."),
    multi("Quels éléments stockent de l'énergie ?", ["Muscles", "Foie", "Tissu adipeux"], ["Poumons"], "Ces tissus gèrent des stocks différents."),
    order("Remets la régulation entre deux repas dans l'ordre.", ["Glycémie baisse", "Foie libère du glucose", "Glycémie stabilisée"], "Le foie sert de tampon."),
    order("Remets le traitement de l'alcool dans l'ordre.", ["Alcool arrive au foie", "Dégradation prioritaire", "Autres traitements ralentis"], "Le foie donne priorité à l'alcool."),
    match("Associe tissu et rôle.", [["Foie", "Régule la glycémie"], ["Muscle", "Utilise son glycogène"], ["Tissu adipeux", "Stocke les triglycérides"]], "Trois tissus, trois rôles."),
    match("Associe carburant et lieu.", [["Glycogène hépatique", "Foie"], ["Glycogène local", "Muscle"], ["Triglycérides", "Gras"]], "Les stocks ne sont pas interchangeables."),
    qcm("Boire de l'alcool près d'un objectif nutritionnel complique surtout car…", "Le foie le traite en priorité", ["Il devient du glycogène musculaire", "Il améliore l'absorption des fibres", "Il supprime la glycémie"], "La priorité hépatique peut retarder le reste."),
    qcm("La meilleure synthèse est…", "Foie régule, muscle consomme, gras réserve", ["Foie contracte, muscle filtre, gras digère", "Tout fait la même chose", "Seul le foie stocke l'énergie"], "Chaque tissu a une fonction dominante."),
  ),
];
